package com.increase.api.models

import java.time.LocalDate
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class AchTransferSimulationTest {

    @Test
    fun createAchTransferSimulation() {
        val achTransferSimulation =
            AchTransferSimulation.builder()
                .transaction(
                    AchTransferSimulation.Transaction.builder()
                        .accountId("string")
                        .amount(123L)
                        .currency(AchTransferSimulation.Transaction.Currency.CAD)
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .description("string")
                        .id("string")
                        .routeId("string")
                        .routeType(AchTransferSimulation.Transaction.RouteType.ACCOUNT_NUMBER)
                        .source(
                            AchTransferSimulation.Transaction.Source.builder()
                                .category(
                                    AchTransferSimulation.Transaction.Source.Category
                                        .ACCOUNT_TRANSFER_INTENTION
                                )
                                .accountTransferIntention(
                                    AchTransferSimulation.Transaction.Source
                                        .AccountTransferIntention
                                        .builder()
                                        .amount(123L)
                                        .currency(
                                            AchTransferSimulation.Transaction.Source
                                                .AccountTransferIntention
                                                .Currency
                                                .CAD
                                        )
                                        .description("string")
                                        .destinationAccountId("string")
                                        .sourceAccountId("string")
                                        .transferId("string")
                                        .build()
                                )
                                .achCheckConversionReturn(
                                    AchTransferSimulation.Transaction.Source
                                        .AchCheckConversionReturn
                                        .builder()
                                        .amount(123L)
                                        .returnReasonCode("string")
                                        .build()
                                )
                                .achCheckConversion(
                                    AchTransferSimulation.Transaction.Source.AchCheckConversion
                                        .builder()
                                        .amount(123L)
                                        .fileId("string")
                                        .build()
                                )
                                .achTransferIntention(
                                    AchTransferSimulation.Transaction.Source.AchTransferIntention
                                        .builder()
                                        .amount(123L)
                                        .accountNumber("string")
                                        .routingNumber("string")
                                        .statementDescriptor("string")
                                        .transferId("string")
                                        .build()
                                )
                                .achTransferRejection(
                                    AchTransferSimulation.Transaction.Source.AchTransferRejection
                                        .builder()
                                        .transferId("string")
                                        .build()
                                )
                                .achTransferReturn(
                                    AchTransferSimulation.Transaction.Source.AchTransferReturn
                                        .builder()
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .returnReasonCode(
                                            AchTransferSimulation.Transaction.Source
                                                .AchTransferReturn
                                                .ReturnReasonCode
                                                .INSUFFICIENT_FUND
                                        )
                                        .transferId("string")
                                        .transactionId("string")
                                        .build()
                                )
                                .cardDisputeAcceptance(
                                    AchTransferSimulation.Transaction.Source.CardDisputeAcceptance
                                        .builder()
                                        .acceptedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .cardDisputeId("string")
                                        .transactionId("string")
                                        .build()
                                )
                                .cardRefund(
                                    AchTransferSimulation.Transaction.Source.CardRefund.builder()
                                        .id("string")
                                        .amount(123L)
                                        .currency(
                                            AchTransferSimulation.Transaction.Source.CardRefund
                                                .Currency
                                                .CAD
                                        )
                                        .cardSettlementTransactionId("string")
                                        .merchantCity("string")
                                        .merchantState("string")
                                        .merchantCountry("string")
                                        .merchantName("string")
                                        .merchantCategoryCode("string")
                                        .type(
                                            AchTransferSimulation.Transaction.Source.CardRefund.Type
                                                .CARD_REFUND
                                        )
                                        .build()
                                )
                                .cardSettlement(
                                    AchTransferSimulation.Transaction.Source.CardSettlement
                                        .builder()
                                        .id("string")
                                        .cardAuthorization("string")
                                        .amount(123L)
                                        .currency(
                                            AchTransferSimulation.Transaction.Source.CardSettlement
                                                .Currency
                                                .CAD
                                        )
                                        .presentmentAmount(123L)
                                        .presentmentCurrency("string")
                                        .merchantCity("string")
                                        .merchantState("string")
                                        .merchantCountry("string")
                                        .merchantName("string")
                                        .merchantCategoryCode("string")
                                        .pendingTransactionId("string")
                                        .type(
                                            AchTransferSimulation.Transaction.Source.CardSettlement
                                                .Type
                                                .CARD_SETTLEMENT
                                        )
                                        .build()
                                )
                                .cardRevenuePayment(
                                    AchTransferSimulation.Transaction.Source.CardRevenuePayment
                                        .builder()
                                        .amount(123L)
                                        .currency(
                                            AchTransferSimulation.Transaction.Source
                                                .CardRevenuePayment
                                                .Currency
                                                .CAD
                                        )
                                        .periodStart(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .periodEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .transactedOnAccountId("string")
                                        .build()
                                )
                                .checkDepositAcceptance(
                                    AchTransferSimulation.Transaction.Source.CheckDepositAcceptance
                                        .builder()
                                        .amount(123L)
                                        .currency(
                                            AchTransferSimulation.Transaction.Source
                                                .CheckDepositAcceptance
                                                .Currency
                                                .CAD
                                        )
                                        .accountNumber("string")
                                        .routingNumber("string")
                                        .auxiliaryOnUs("string")
                                        .serialNumber("string")
                                        .checkDepositId("string")
                                        .build()
                                )
                                .checkDepositReturn(
                                    AchTransferSimulation.Transaction.Source.CheckDepositReturn
                                        .builder()
                                        .amount(123L)
                                        .returnedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .currency(
                                            AchTransferSimulation.Transaction.Source
                                                .CheckDepositReturn
                                                .Currency
                                                .CAD
                                        )
                                        .checkDepositId("string")
                                        .transactionId("string")
                                        .returnReason(
                                            AchTransferSimulation.Transaction.Source
                                                .CheckDepositReturn
                                                .ReturnReason
                                                .ACH_CONVERSION_NOT_SUPPORTED
                                        )
                                        .build()
                                )
                                .checkTransferIntention(
                                    AchTransferSimulation.Transaction.Source.CheckTransferIntention
                                        .builder()
                                        .addressLine1("string")
                                        .addressLine2("string")
                                        .addressCity("string")
                                        .addressState("string")
                                        .addressZip("string")
                                        .amount(123L)
                                        .currency(
                                            AchTransferSimulation.Transaction.Source
                                                .CheckTransferIntention
                                                .Currency
                                                .CAD
                                        )
                                        .recipientName("string")
                                        .transferId("string")
                                        .build()
                                )
                                .checkTransferReturn(
                                    AchTransferSimulation.Transaction.Source.CheckTransferReturn
                                        .builder()
                                        .transferId("string")
                                        .returnedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .fileId("string")
                                        .reason(
                                            AchTransferSimulation.Transaction.Source
                                                .CheckTransferReturn
                                                .Reason
                                                .MAIL_DELIVERY_FAILURE
                                        )
                                        .transactionId("string")
                                        .build()
                                )
                                .checkTransferRejection(
                                    AchTransferSimulation.Transaction.Source.CheckTransferRejection
                                        .builder()
                                        .transferId("string")
                                        .build()
                                )
                                .checkTransferStopPaymentRequest(
                                    AchTransferSimulation.Transaction.Source
                                        .CheckTransferStopPaymentRequest
                                        .builder()
                                        .transferId("string")
                                        .transactionId("string")
                                        .requestedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .type(
                                            AchTransferSimulation.Transaction.Source
                                                .CheckTransferStopPaymentRequest
                                                .Type
                                                .CHECK_TRANSFER_STOP_PAYMENT_REQUEST
                                        )
                                        .build()
                                )
                                .disputeResolution(
                                    AchTransferSimulation.Transaction.Source.DisputeResolution
                                        .builder()
                                        .amount(123L)
                                        .currency(
                                            AchTransferSimulation.Transaction.Source
                                                .DisputeResolution
                                                .Currency
                                                .CAD
                                        )
                                        .disputedTransactionId("string")
                                        .build()
                                )
                                .empyrealCashDeposit(
                                    AchTransferSimulation.Transaction.Source.EmpyrealCashDeposit
                                        .builder()
                                        .amount(123L)
                                        .bagId("string")
                                        .depositDate(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .build()
                                )
                                .feePayment(
                                    AchTransferSimulation.Transaction.Source.FeePayment.builder()
                                        .amount(123L)
                                        .currency(
                                            AchTransferSimulation.Transaction.Source.FeePayment
                                                .Currency
                                                .CAD
                                        )
                                        .build()
                                )
                                .inboundAchTransfer(
                                    AchTransferSimulation.Transaction.Source.InboundAchTransfer
                                        .builder()
                                        .amount(123L)
                                        .originatorCompanyName("string")
                                        .originatorCompanyDescriptiveDate("string")
                                        .originatorCompanyDiscretionaryData("string")
                                        .originatorCompanyEntryDescription("string")
                                        .originatorCompanyId("string")
                                        .receiverIdNumber("string")
                                        .receiverName("string")
                                        .traceNumber("string")
                                        .build()
                                )
                                .inboundCheck(
                                    AchTransferSimulation.Transaction.Source.InboundCheck.builder()
                                        .amount(123L)
                                        .currency(
                                            AchTransferSimulation.Transaction.Source.InboundCheck
                                                .Currency
                                                .CAD
                                        )
                                        .checkNumber("string")
                                        .checkFrontImageFileId("string")
                                        .checkRearImageFileId("string")
                                        .build()
                                )
                                .inboundInternationalAchTransfer(
                                    AchTransferSimulation.Transaction.Source
                                        .InboundInternationalAchTransfer
                                        .builder()
                                        .amount(123L)
                                        .foreignExchangeIndicator("string")
                                        .foreignExchangeReferenceIndicator("string")
                                        .foreignExchangeReference("string")
                                        .destinationCountryCode("string")
                                        .destinationCurrencyCode("string")
                                        .foreignPaymentAmount(123L)
                                        .foreignTraceNumber("string")
                                        .internationalTransactionTypeCode("string")
                                        .originatingCurrencyCode("string")
                                        .originatingDepositoryFinancialInstitutionName("string")
                                        .originatingDepositoryFinancialInstitutionIdQualifier(
                                            "string"
                                        )
                                        .originatingDepositoryFinancialInstitutionId("string")
                                        .originatingDepositoryFinancialInstitutionBranchCountry(
                                            "string"
                                        )
                                        .originatorCity("string")
                                        .originatorCompanyEntryDescription("string")
                                        .originatorCountry("string")
                                        .originatorIdentification("string")
                                        .originatorName("string")
                                        .originatorPostalCode("string")
                                        .originatorStreetAddress("string")
                                        .originatorStateOrProvince("string")
                                        .paymentRelatedInformation("string")
                                        .paymentRelatedInformation2("string")
                                        .receiverIdentificationNumber("string")
                                        .receiverStreetAddress("string")
                                        .receiverCity("string")
                                        .receiverStateOrProvince("string")
                                        .receiverCountry("string")
                                        .receiverPostalCode("string")
                                        .receivingCompanyOrIndividualName("string")
                                        .receivingDepositoryFinancialInstitutionName("string")
                                        .receivingDepositoryFinancialInstitutionIdQualifier(
                                            "string"
                                        )
                                        .receivingDepositoryFinancialInstitutionId("string")
                                        .receivingDepositoryFinancialInstitutionCountry("string")
                                        .traceNumber("string")
                                        .build()
                                )
                                .inboundRealTimePaymentsTransferConfirmation(
                                    AchTransferSimulation.Transaction.Source
                                        .InboundRealTimePaymentsTransferConfirmation
                                        .builder()
                                        .amount(123L)
                                        .currency(
                                            AchTransferSimulation.Transaction.Source
                                                .InboundRealTimePaymentsTransferConfirmation
                                                .Currency
                                                .CAD
                                        )
                                        .creditorName("string")
                                        .debtorName("string")
                                        .debtorAccountNumber("string")
                                        .debtorRoutingNumber("string")
                                        .transactionIdentification("string")
                                        .remittanceInformation("string")
                                        .build()
                                )
                                .inboundWireDrawdownPaymentReversal(
                                    AchTransferSimulation.Transaction.Source
                                        .InboundWireDrawdownPaymentReversal
                                        .builder()
                                        .amount(123L)
                                        .description("string")
                                        .inputCycleDate(LocalDate.parse("2019-12-27"))
                                        .inputSequenceNumber("string")
                                        .inputSource("string")
                                        .inputMessageAccountabilityData("string")
                                        .previousMessageInputMessageAccountabilityData("string")
                                        .previousMessageInputCycleDate(
                                            LocalDate.parse("2019-12-27")
                                        )
                                        .previousMessageInputSequenceNumber("string")
                                        .previousMessageInputSource("string")
                                        .build()
                                )
                                .inboundWireDrawdownPayment(
                                    AchTransferSimulation.Transaction.Source
                                        .InboundWireDrawdownPayment
                                        .builder()
                                        .amount(123L)
                                        .beneficiaryAddressLine1("string")
                                        .beneficiaryAddressLine2("string")
                                        .beneficiaryAddressLine3("string")
                                        .beneficiaryName("string")
                                        .beneficiaryReference("string")
                                        .description("string")
                                        .inputMessageAccountabilityData("string")
                                        .originatorAddressLine1("string")
                                        .originatorAddressLine2("string")
                                        .originatorAddressLine3("string")
                                        .originatorName("string")
                                        .originatorToBeneficiaryInformation("string")
                                        .build()
                                )
                                .inboundWireReversal(
                                    AchTransferSimulation.Transaction.Source.InboundWireReversal
                                        .builder()
                                        .amount(123L)
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .description("string")
                                        .inputCycleDate(LocalDate.parse("2019-12-27"))
                                        .inputSequenceNumber("string")
                                        .inputSource("string")
                                        .inputMessageAccountabilityData("string")
                                        .previousMessageInputMessageAccountabilityData("string")
                                        .previousMessageInputCycleDate(
                                            LocalDate.parse("2019-12-27")
                                        )
                                        .previousMessageInputSequenceNumber("string")
                                        .previousMessageInputSource("string")
                                        .receiverFinancialInstitutionInformation("string")
                                        .financialInstitutionToFinancialInstitutionInformation(
                                            "string"
                                        )
                                        .transactionId("string")
                                        .build()
                                )
                                .inboundWireTransfer(
                                    AchTransferSimulation.Transaction.Source.InboundWireTransfer
                                        .builder()
                                        .amount(123L)
                                        .beneficiaryAddressLine1("string")
                                        .beneficiaryAddressLine2("string")
                                        .beneficiaryAddressLine3("string")
                                        .beneficiaryName("string")
                                        .beneficiaryReference("string")
                                        .description("string")
                                        .inputMessageAccountabilityData("string")
                                        .originatorAddressLine1("string")
                                        .originatorAddressLine2("string")
                                        .originatorAddressLine3("string")
                                        .originatorName("string")
                                        .originatorToBeneficiaryInformationLine1("string")
                                        .originatorToBeneficiaryInformationLine2("string")
                                        .originatorToBeneficiaryInformationLine3("string")
                                        .originatorToBeneficiaryInformationLine4("string")
                                        .originatorToBeneficiaryInformation("string")
                                        .build()
                                )
                                .interestPayment(
                                    AchTransferSimulation.Transaction.Source.InterestPayment
                                        .builder()
                                        .amount(123L)
                                        .currency(
                                            AchTransferSimulation.Transaction.Source.InterestPayment
                                                .Currency
                                                .CAD
                                        )
                                        .periodStart(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .periodEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .accruedOnAccountId("string")
                                        .build()
                                )
                                .internalSource(
                                    AchTransferSimulation.Transaction.Source.InternalSource
                                        .builder()
                                        .amount(123L)
                                        .currency(
                                            AchTransferSimulation.Transaction.Source.InternalSource
                                                .Currency
                                                .CAD
                                        )
                                        .reason(
                                            AchTransferSimulation.Transaction.Source.InternalSource
                                                .Reason
                                                .BANK_MIGRATION
                                        )
                                        .build()
                                )
                                .cardRouteRefund(
                                    AchTransferSimulation.Transaction.Source.CardRouteRefund
                                        .builder()
                                        .amount(123L)
                                        .currency(
                                            AchTransferSimulation.Transaction.Source.CardRouteRefund
                                                .Currency
                                                .CAD
                                        )
                                        .merchantAcceptorId("string")
                                        .merchantCity("string")
                                        .merchantCountry("string")
                                        .merchantDescriptor("string")
                                        .merchantState("string")
                                        .merchantCategoryCode("string")
                                        .build()
                                )
                                .cardRouteSettlement(
                                    AchTransferSimulation.Transaction.Source.CardRouteSettlement
                                        .builder()
                                        .amount(123L)
                                        .currency(
                                            AchTransferSimulation.Transaction.Source
                                                .CardRouteSettlement
                                                .Currency
                                                .CAD
                                        )
                                        .merchantAcceptorId("string")
                                        .merchantCity("string")
                                        .merchantCountry("string")
                                        .merchantDescriptor("string")
                                        .merchantState("string")
                                        .merchantCategoryCode("string")
                                        .build()
                                )
                                .realTimePaymentsTransferAcknowledgement(
                                    AchTransferSimulation.Transaction.Source
                                        .RealTimePaymentsTransferAcknowledgement
                                        .builder()
                                        .amount(123L)
                                        .destinationAccountNumber("string")
                                        .destinationRoutingNumber("string")
                                        .remittanceInformation("string")
                                        .transferId("string")
                                        .build()
                                )
                                .sampleFunds(
                                    AchTransferSimulation.Transaction.Source.SampleFunds.builder()
                                        .originator("string")
                                        .build()
                                )
                                .wireDrawdownPaymentIntention(
                                    AchTransferSimulation.Transaction.Source
                                        .WireDrawdownPaymentIntention
                                        .builder()
                                        .amount(123L)
                                        .accountNumber("string")
                                        .routingNumber("string")
                                        .messageToRecipient("string")
                                        .transferId("string")
                                        .build()
                                )
                                .wireDrawdownPaymentRejection(
                                    AchTransferSimulation.Transaction.Source
                                        .WireDrawdownPaymentRejection
                                        .builder()
                                        .transferId("string")
                                        .build()
                                )
                                .wireTransferIntention(
                                    AchTransferSimulation.Transaction.Source.WireTransferIntention
                                        .builder()
                                        .amount(123L)
                                        .accountNumber("string")
                                        .routingNumber("string")
                                        .messageToRecipient("string")
                                        .transferId("string")
                                        .build()
                                )
                                .wireTransferRejection(
                                    AchTransferSimulation.Transaction.Source.WireTransferRejection
                                        .builder()
                                        .transferId("string")
                                        .build()
                                )
                                .build()
                        )
                        .type(AchTransferSimulation.Transaction.Type.TRANSACTION)
                        .build()
                )
                .declinedTransaction(
                    AchTransferSimulation.DeclinedTransaction.builder()
                        .accountId("string")
                        .amount(123L)
                        .currency(AchTransferSimulation.DeclinedTransaction.Currency.CAD)
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .description("string")
                        .id("string")
                        .routeId("string")
                        .routeType(
                            AchTransferSimulation.DeclinedTransaction.RouteType.ACCOUNT_NUMBER
                        )
                        .source(
                            AchTransferSimulation.DeclinedTransaction.Source.builder()
                                .category(
                                    AchTransferSimulation.DeclinedTransaction.Source.Category
                                        .ACH_DECLINE
                                )
                                .achDecline(
                                    AchTransferSimulation.DeclinedTransaction.Source.AchDecline
                                        .builder()
                                        .amount(123L)
                                        .originatorCompanyName("string")
                                        .originatorCompanyDescriptiveDate("string")
                                        .originatorCompanyDiscretionaryData("string")
                                        .originatorCompanyId("string")
                                        .reason(
                                            AchTransferSimulation.DeclinedTransaction.Source
                                                .AchDecline
                                                .Reason
                                                .ACH_ROUTE_CANCELED
                                        )
                                        .receiverIdNumber("string")
                                        .receiverName("string")
                                        .traceNumber("string")
                                        .build()
                                )
                                .cardDecline(
                                    AchTransferSimulation.DeclinedTransaction.Source.CardDecline
                                        .builder()
                                        .merchantAcceptorId("string")
                                        .merchantDescriptor("string")
                                        .merchantCategoryCode("string")
                                        .merchantCity("string")
                                        .merchantCountry("string")
                                        .network(
                                            AchTransferSimulation.DeclinedTransaction.Source
                                                .CardDecline
                                                .Network
                                                .VISA
                                        )
                                        .networkDetails(
                                            AchTransferSimulation.DeclinedTransaction.Source
                                                .CardDecline
                                                .NetworkDetails
                                                .builder()
                                                .visa(
                                                    AchTransferSimulation.DeclinedTransaction.Source
                                                        .CardDecline
                                                        .NetworkDetails
                                                        .Visa
                                                        .builder()
                                                        .electronicCommerceIndicator(
                                                            AchTransferSimulation
                                                                .DeclinedTransaction
                                                                .Source
                                                                .CardDecline
                                                                .NetworkDetails
                                                                .Visa
                                                                .ElectronicCommerceIndicator
                                                                .MAIL_PHONE_ORDER
                                                        )
                                                        .pointOfServiceEntryMode(
                                                            PointOfServiceEntryMode.MANUAL
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .amount(123L)
                                        .currency(
                                            AchTransferSimulation.DeclinedTransaction.Source
                                                .CardDecline
                                                .Currency
                                                .CAD
                                        )
                                        .reason(
                                            AchTransferSimulation.DeclinedTransaction.Source
                                                .CardDecline
                                                .Reason
                                                .CARD_NOT_ACTIVE
                                        )
                                        .merchantState("string")
                                        .realTimeDecisionId("string")
                                        .digitalWalletTokenId("string")
                                        .build()
                                )
                                .checkDecline(
                                    AchTransferSimulation.DeclinedTransaction.Source.CheckDecline
                                        .builder()
                                        .amount(123L)
                                        .auxiliaryOnUs("string")
                                        .reason(
                                            AchTransferSimulation.DeclinedTransaction.Source
                                                .CheckDecline
                                                .Reason
                                                .ACH_ROUTE_CANCELED
                                        )
                                        .build()
                                )
                                .inboundRealTimePaymentsTransferDecline(
                                    AchTransferSimulation.DeclinedTransaction.Source
                                        .InboundRealTimePaymentsTransferDecline
                                        .builder()
                                        .amount(123L)
                                        .currency(
                                            AchTransferSimulation.DeclinedTransaction.Source
                                                .InboundRealTimePaymentsTransferDecline
                                                .Currency
                                                .CAD
                                        )
                                        .reason(
                                            AchTransferSimulation.DeclinedTransaction.Source
                                                .InboundRealTimePaymentsTransferDecline
                                                .Reason
                                                .ACCOUNT_NUMBER_CANCELED
                                        )
                                        .creditorName("string")
                                        .debtorName("string")
                                        .debtorAccountNumber("string")
                                        .debtorRoutingNumber("string")
                                        .transactionIdentification("string")
                                        .remittanceInformation("string")
                                        .build()
                                )
                                .internationalAchDecline(
                                    AchTransferSimulation.DeclinedTransaction.Source
                                        .InternationalAchDecline
                                        .builder()
                                        .amount(123L)
                                        .foreignExchangeIndicator("string")
                                        .foreignExchangeReferenceIndicator("string")
                                        .foreignExchangeReference("string")
                                        .destinationCountryCode("string")
                                        .destinationCurrencyCode("string")
                                        .foreignPaymentAmount(123L)
                                        .foreignTraceNumber("string")
                                        .internationalTransactionTypeCode("string")
                                        .originatingCurrencyCode("string")
                                        .originatingDepositoryFinancialInstitutionName("string")
                                        .originatingDepositoryFinancialInstitutionIdQualifier(
                                            "string"
                                        )
                                        .originatingDepositoryFinancialInstitutionId("string")
                                        .originatingDepositoryFinancialInstitutionBranchCountry(
                                            "string"
                                        )
                                        .originatorCity("string")
                                        .originatorCompanyEntryDescription("string")
                                        .originatorCountry("string")
                                        .originatorIdentification("string")
                                        .originatorName("string")
                                        .originatorPostalCode("string")
                                        .originatorStreetAddress("string")
                                        .originatorStateOrProvince("string")
                                        .paymentRelatedInformation("string")
                                        .paymentRelatedInformation2("string")
                                        .receiverIdentificationNumber("string")
                                        .receiverStreetAddress("string")
                                        .receiverCity("string")
                                        .receiverStateOrProvince("string")
                                        .receiverCountry("string")
                                        .receiverPostalCode("string")
                                        .receivingCompanyOrIndividualName("string")
                                        .receivingDepositoryFinancialInstitutionName("string")
                                        .receivingDepositoryFinancialInstitutionIdQualifier(
                                            "string"
                                        )
                                        .receivingDepositoryFinancialInstitutionId("string")
                                        .receivingDepositoryFinancialInstitutionCountry("string")
                                        .traceNumber("string")
                                        .build()
                                )
                                .cardRouteDecline(
                                    AchTransferSimulation.DeclinedTransaction.Source
                                        .CardRouteDecline
                                        .builder()
                                        .amount(123L)
                                        .currency(
                                            AchTransferSimulation.DeclinedTransaction.Source
                                                .CardRouteDecline
                                                .Currency
                                                .CAD
                                        )
                                        .merchantAcceptorId("string")
                                        .merchantCity("string")
                                        .merchantCountry("string")
                                        .merchantDescriptor("string")
                                        .merchantState("string")
                                        .merchantCategoryCode("string")
                                        .build()
                                )
                                .build()
                        )
                        .type(AchTransferSimulation.DeclinedTransaction.Type.DECLINED_TRANSACTION)
                        .build()
                )
                .type(AchTransferSimulation.Type.INBOUND_ACH_TRANSFER_SIMULATION_RESULT)
                .build()
        assertThat(achTransferSimulation).isNotNull
        assertThat(achTransferSimulation.transaction())
            .isEqualTo(
                AchTransferSimulation.Transaction.builder()
                    .accountId("string")
                    .amount(123L)
                    .currency(AchTransferSimulation.Transaction.Currency.CAD)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .description("string")
                    .id("string")
                    .routeId("string")
                    .routeType(AchTransferSimulation.Transaction.RouteType.ACCOUNT_NUMBER)
                    .source(
                        AchTransferSimulation.Transaction.Source.builder()
                            .category(
                                AchTransferSimulation.Transaction.Source.Category
                                    .ACCOUNT_TRANSFER_INTENTION
                            )
                            .accountTransferIntention(
                                AchTransferSimulation.Transaction.Source.AccountTransferIntention
                                    .builder()
                                    .amount(123L)
                                    .currency(
                                        AchTransferSimulation.Transaction.Source
                                            .AccountTransferIntention
                                            .Currency
                                            .CAD
                                    )
                                    .description("string")
                                    .destinationAccountId("string")
                                    .sourceAccountId("string")
                                    .transferId("string")
                                    .build()
                            )
                            .achCheckConversionReturn(
                                AchTransferSimulation.Transaction.Source.AchCheckConversionReturn
                                    .builder()
                                    .amount(123L)
                                    .returnReasonCode("string")
                                    .build()
                            )
                            .achCheckConversion(
                                AchTransferSimulation.Transaction.Source.AchCheckConversion
                                    .builder()
                                    .amount(123L)
                                    .fileId("string")
                                    .build()
                            )
                            .achTransferIntention(
                                AchTransferSimulation.Transaction.Source.AchTransferIntention
                                    .builder()
                                    .amount(123L)
                                    .accountNumber("string")
                                    .routingNumber("string")
                                    .statementDescriptor("string")
                                    .transferId("string")
                                    .build()
                            )
                            .achTransferRejection(
                                AchTransferSimulation.Transaction.Source.AchTransferRejection
                                    .builder()
                                    .transferId("string")
                                    .build()
                            )
                            .achTransferReturn(
                                AchTransferSimulation.Transaction.Source.AchTransferReturn.builder()
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .returnReasonCode(
                                        AchTransferSimulation.Transaction.Source.AchTransferReturn
                                            .ReturnReasonCode
                                            .INSUFFICIENT_FUND
                                    )
                                    .transferId("string")
                                    .transactionId("string")
                                    .build()
                            )
                            .cardDisputeAcceptance(
                                AchTransferSimulation.Transaction.Source.CardDisputeAcceptance
                                    .builder()
                                    .acceptedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .cardDisputeId("string")
                                    .transactionId("string")
                                    .build()
                            )
                            .cardRefund(
                                AchTransferSimulation.Transaction.Source.CardRefund.builder()
                                    .id("string")
                                    .amount(123L)
                                    .currency(
                                        AchTransferSimulation.Transaction.Source.CardRefund.Currency
                                            .CAD
                                    )
                                    .cardSettlementTransactionId("string")
                                    .merchantCity("string")
                                    .merchantState("string")
                                    .merchantCountry("string")
                                    .merchantName("string")
                                    .merchantCategoryCode("string")
                                    .type(
                                        AchTransferSimulation.Transaction.Source.CardRefund.Type
                                            .CARD_REFUND
                                    )
                                    .build()
                            )
                            .cardSettlement(
                                AchTransferSimulation.Transaction.Source.CardSettlement.builder()
                                    .id("string")
                                    .cardAuthorization("string")
                                    .amount(123L)
                                    .currency(
                                        AchTransferSimulation.Transaction.Source.CardSettlement
                                            .Currency
                                            .CAD
                                    )
                                    .presentmentAmount(123L)
                                    .presentmentCurrency("string")
                                    .merchantCity("string")
                                    .merchantState("string")
                                    .merchantCountry("string")
                                    .merchantName("string")
                                    .merchantCategoryCode("string")
                                    .pendingTransactionId("string")
                                    .type(
                                        AchTransferSimulation.Transaction.Source.CardSettlement.Type
                                            .CARD_SETTLEMENT
                                    )
                                    .build()
                            )
                            .cardRevenuePayment(
                                AchTransferSimulation.Transaction.Source.CardRevenuePayment
                                    .builder()
                                    .amount(123L)
                                    .currency(
                                        AchTransferSimulation.Transaction.Source.CardRevenuePayment
                                            .Currency
                                            .CAD
                                    )
                                    .periodStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .periodEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .transactedOnAccountId("string")
                                    .build()
                            )
                            .checkDepositAcceptance(
                                AchTransferSimulation.Transaction.Source.CheckDepositAcceptance
                                    .builder()
                                    .amount(123L)
                                    .currency(
                                        AchTransferSimulation.Transaction.Source
                                            .CheckDepositAcceptance
                                            .Currency
                                            .CAD
                                    )
                                    .accountNumber("string")
                                    .routingNumber("string")
                                    .auxiliaryOnUs("string")
                                    .serialNumber("string")
                                    .checkDepositId("string")
                                    .build()
                            )
                            .checkDepositReturn(
                                AchTransferSimulation.Transaction.Source.CheckDepositReturn
                                    .builder()
                                    .amount(123L)
                                    .returnedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .currency(
                                        AchTransferSimulation.Transaction.Source.CheckDepositReturn
                                            .Currency
                                            .CAD
                                    )
                                    .checkDepositId("string")
                                    .transactionId("string")
                                    .returnReason(
                                        AchTransferSimulation.Transaction.Source.CheckDepositReturn
                                            .ReturnReason
                                            .ACH_CONVERSION_NOT_SUPPORTED
                                    )
                                    .build()
                            )
                            .checkTransferIntention(
                                AchTransferSimulation.Transaction.Source.CheckTransferIntention
                                    .builder()
                                    .addressLine1("string")
                                    .addressLine2("string")
                                    .addressCity("string")
                                    .addressState("string")
                                    .addressZip("string")
                                    .amount(123L)
                                    .currency(
                                        AchTransferSimulation.Transaction.Source
                                            .CheckTransferIntention
                                            .Currency
                                            .CAD
                                    )
                                    .recipientName("string")
                                    .transferId("string")
                                    .build()
                            )
                            .checkTransferReturn(
                                AchTransferSimulation.Transaction.Source.CheckTransferReturn
                                    .builder()
                                    .transferId("string")
                                    .returnedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .fileId("string")
                                    .reason(
                                        AchTransferSimulation.Transaction.Source.CheckTransferReturn
                                            .Reason
                                            .MAIL_DELIVERY_FAILURE
                                    )
                                    .transactionId("string")
                                    .build()
                            )
                            .checkTransferRejection(
                                AchTransferSimulation.Transaction.Source.CheckTransferRejection
                                    .builder()
                                    .transferId("string")
                                    .build()
                            )
                            .checkTransferStopPaymentRequest(
                                AchTransferSimulation.Transaction.Source
                                    .CheckTransferStopPaymentRequest
                                    .builder()
                                    .transferId("string")
                                    .transactionId("string")
                                    .requestedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .type(
                                        AchTransferSimulation.Transaction.Source
                                            .CheckTransferStopPaymentRequest
                                            .Type
                                            .CHECK_TRANSFER_STOP_PAYMENT_REQUEST
                                    )
                                    .build()
                            )
                            .disputeResolution(
                                AchTransferSimulation.Transaction.Source.DisputeResolution.builder()
                                    .amount(123L)
                                    .currency(
                                        AchTransferSimulation.Transaction.Source.DisputeResolution
                                            .Currency
                                            .CAD
                                    )
                                    .disputedTransactionId("string")
                                    .build()
                            )
                            .empyrealCashDeposit(
                                AchTransferSimulation.Transaction.Source.EmpyrealCashDeposit
                                    .builder()
                                    .amount(123L)
                                    .bagId("string")
                                    .depositDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .feePayment(
                                AchTransferSimulation.Transaction.Source.FeePayment.builder()
                                    .amount(123L)
                                    .currency(
                                        AchTransferSimulation.Transaction.Source.FeePayment.Currency
                                            .CAD
                                    )
                                    .build()
                            )
                            .inboundAchTransfer(
                                AchTransferSimulation.Transaction.Source.InboundAchTransfer
                                    .builder()
                                    .amount(123L)
                                    .originatorCompanyName("string")
                                    .originatorCompanyDescriptiveDate("string")
                                    .originatorCompanyDiscretionaryData("string")
                                    .originatorCompanyEntryDescription("string")
                                    .originatorCompanyId("string")
                                    .receiverIdNumber("string")
                                    .receiverName("string")
                                    .traceNumber("string")
                                    .build()
                            )
                            .inboundCheck(
                                AchTransferSimulation.Transaction.Source.InboundCheck.builder()
                                    .amount(123L)
                                    .currency(
                                        AchTransferSimulation.Transaction.Source.InboundCheck
                                            .Currency
                                            .CAD
                                    )
                                    .checkNumber("string")
                                    .checkFrontImageFileId("string")
                                    .checkRearImageFileId("string")
                                    .build()
                            )
                            .inboundInternationalAchTransfer(
                                AchTransferSimulation.Transaction.Source
                                    .InboundInternationalAchTransfer
                                    .builder()
                                    .amount(123L)
                                    .foreignExchangeIndicator("string")
                                    .foreignExchangeReferenceIndicator("string")
                                    .foreignExchangeReference("string")
                                    .destinationCountryCode("string")
                                    .destinationCurrencyCode("string")
                                    .foreignPaymentAmount(123L)
                                    .foreignTraceNumber("string")
                                    .internationalTransactionTypeCode("string")
                                    .originatingCurrencyCode("string")
                                    .originatingDepositoryFinancialInstitutionName("string")
                                    .originatingDepositoryFinancialInstitutionIdQualifier("string")
                                    .originatingDepositoryFinancialInstitutionId("string")
                                    .originatingDepositoryFinancialInstitutionBranchCountry(
                                        "string"
                                    )
                                    .originatorCity("string")
                                    .originatorCompanyEntryDescription("string")
                                    .originatorCountry("string")
                                    .originatorIdentification("string")
                                    .originatorName("string")
                                    .originatorPostalCode("string")
                                    .originatorStreetAddress("string")
                                    .originatorStateOrProvince("string")
                                    .paymentRelatedInformation("string")
                                    .paymentRelatedInformation2("string")
                                    .receiverIdentificationNumber("string")
                                    .receiverStreetAddress("string")
                                    .receiverCity("string")
                                    .receiverStateOrProvince("string")
                                    .receiverCountry("string")
                                    .receiverPostalCode("string")
                                    .receivingCompanyOrIndividualName("string")
                                    .receivingDepositoryFinancialInstitutionName("string")
                                    .receivingDepositoryFinancialInstitutionIdQualifier("string")
                                    .receivingDepositoryFinancialInstitutionId("string")
                                    .receivingDepositoryFinancialInstitutionCountry("string")
                                    .traceNumber("string")
                                    .build()
                            )
                            .inboundRealTimePaymentsTransferConfirmation(
                                AchTransferSimulation.Transaction.Source
                                    .InboundRealTimePaymentsTransferConfirmation
                                    .builder()
                                    .amount(123L)
                                    .currency(
                                        AchTransferSimulation.Transaction.Source
                                            .InboundRealTimePaymentsTransferConfirmation
                                            .Currency
                                            .CAD
                                    )
                                    .creditorName("string")
                                    .debtorName("string")
                                    .debtorAccountNumber("string")
                                    .debtorRoutingNumber("string")
                                    .transactionIdentification("string")
                                    .remittanceInformation("string")
                                    .build()
                            )
                            .inboundWireDrawdownPaymentReversal(
                                AchTransferSimulation.Transaction.Source
                                    .InboundWireDrawdownPaymentReversal
                                    .builder()
                                    .amount(123L)
                                    .description("string")
                                    .inputCycleDate(LocalDate.parse("2019-12-27"))
                                    .inputSequenceNumber("string")
                                    .inputSource("string")
                                    .inputMessageAccountabilityData("string")
                                    .previousMessageInputMessageAccountabilityData("string")
                                    .previousMessageInputCycleDate(LocalDate.parse("2019-12-27"))
                                    .previousMessageInputSequenceNumber("string")
                                    .previousMessageInputSource("string")
                                    .build()
                            )
                            .inboundWireDrawdownPayment(
                                AchTransferSimulation.Transaction.Source.InboundWireDrawdownPayment
                                    .builder()
                                    .amount(123L)
                                    .beneficiaryAddressLine1("string")
                                    .beneficiaryAddressLine2("string")
                                    .beneficiaryAddressLine3("string")
                                    .beneficiaryName("string")
                                    .beneficiaryReference("string")
                                    .description("string")
                                    .inputMessageAccountabilityData("string")
                                    .originatorAddressLine1("string")
                                    .originatorAddressLine2("string")
                                    .originatorAddressLine3("string")
                                    .originatorName("string")
                                    .originatorToBeneficiaryInformation("string")
                                    .build()
                            )
                            .inboundWireReversal(
                                AchTransferSimulation.Transaction.Source.InboundWireReversal
                                    .builder()
                                    .amount(123L)
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .description("string")
                                    .inputCycleDate(LocalDate.parse("2019-12-27"))
                                    .inputSequenceNumber("string")
                                    .inputSource("string")
                                    .inputMessageAccountabilityData("string")
                                    .previousMessageInputMessageAccountabilityData("string")
                                    .previousMessageInputCycleDate(LocalDate.parse("2019-12-27"))
                                    .previousMessageInputSequenceNumber("string")
                                    .previousMessageInputSource("string")
                                    .receiverFinancialInstitutionInformation("string")
                                    .financialInstitutionToFinancialInstitutionInformation("string")
                                    .transactionId("string")
                                    .build()
                            )
                            .inboundWireTransfer(
                                AchTransferSimulation.Transaction.Source.InboundWireTransfer
                                    .builder()
                                    .amount(123L)
                                    .beneficiaryAddressLine1("string")
                                    .beneficiaryAddressLine2("string")
                                    .beneficiaryAddressLine3("string")
                                    .beneficiaryName("string")
                                    .beneficiaryReference("string")
                                    .description("string")
                                    .inputMessageAccountabilityData("string")
                                    .originatorAddressLine1("string")
                                    .originatorAddressLine2("string")
                                    .originatorAddressLine3("string")
                                    .originatorName("string")
                                    .originatorToBeneficiaryInformationLine1("string")
                                    .originatorToBeneficiaryInformationLine2("string")
                                    .originatorToBeneficiaryInformationLine3("string")
                                    .originatorToBeneficiaryInformationLine4("string")
                                    .originatorToBeneficiaryInformation("string")
                                    .build()
                            )
                            .interestPayment(
                                AchTransferSimulation.Transaction.Source.InterestPayment.builder()
                                    .amount(123L)
                                    .currency(
                                        AchTransferSimulation.Transaction.Source.InterestPayment
                                            .Currency
                                            .CAD
                                    )
                                    .periodStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .periodEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .accruedOnAccountId("string")
                                    .build()
                            )
                            .internalSource(
                                AchTransferSimulation.Transaction.Source.InternalSource.builder()
                                    .amount(123L)
                                    .currency(
                                        AchTransferSimulation.Transaction.Source.InternalSource
                                            .Currency
                                            .CAD
                                    )
                                    .reason(
                                        AchTransferSimulation.Transaction.Source.InternalSource
                                            .Reason
                                            .BANK_MIGRATION
                                    )
                                    .build()
                            )
                            .cardRouteRefund(
                                AchTransferSimulation.Transaction.Source.CardRouteRefund.builder()
                                    .amount(123L)
                                    .currency(
                                        AchTransferSimulation.Transaction.Source.CardRouteRefund
                                            .Currency
                                            .CAD
                                    )
                                    .merchantAcceptorId("string")
                                    .merchantCity("string")
                                    .merchantCountry("string")
                                    .merchantDescriptor("string")
                                    .merchantState("string")
                                    .merchantCategoryCode("string")
                                    .build()
                            )
                            .cardRouteSettlement(
                                AchTransferSimulation.Transaction.Source.CardRouteSettlement
                                    .builder()
                                    .amount(123L)
                                    .currency(
                                        AchTransferSimulation.Transaction.Source.CardRouteSettlement
                                            .Currency
                                            .CAD
                                    )
                                    .merchantAcceptorId("string")
                                    .merchantCity("string")
                                    .merchantCountry("string")
                                    .merchantDescriptor("string")
                                    .merchantState("string")
                                    .merchantCategoryCode("string")
                                    .build()
                            )
                            .realTimePaymentsTransferAcknowledgement(
                                AchTransferSimulation.Transaction.Source
                                    .RealTimePaymentsTransferAcknowledgement
                                    .builder()
                                    .amount(123L)
                                    .destinationAccountNumber("string")
                                    .destinationRoutingNumber("string")
                                    .remittanceInformation("string")
                                    .transferId("string")
                                    .build()
                            )
                            .sampleFunds(
                                AchTransferSimulation.Transaction.Source.SampleFunds.builder()
                                    .originator("string")
                                    .build()
                            )
                            .wireDrawdownPaymentIntention(
                                AchTransferSimulation.Transaction.Source
                                    .WireDrawdownPaymentIntention
                                    .builder()
                                    .amount(123L)
                                    .accountNumber("string")
                                    .routingNumber("string")
                                    .messageToRecipient("string")
                                    .transferId("string")
                                    .build()
                            )
                            .wireDrawdownPaymentRejection(
                                AchTransferSimulation.Transaction.Source
                                    .WireDrawdownPaymentRejection
                                    .builder()
                                    .transferId("string")
                                    .build()
                            )
                            .wireTransferIntention(
                                AchTransferSimulation.Transaction.Source.WireTransferIntention
                                    .builder()
                                    .amount(123L)
                                    .accountNumber("string")
                                    .routingNumber("string")
                                    .messageToRecipient("string")
                                    .transferId("string")
                                    .build()
                            )
                            .wireTransferRejection(
                                AchTransferSimulation.Transaction.Source.WireTransferRejection
                                    .builder()
                                    .transferId("string")
                                    .build()
                            )
                            .build()
                    )
                    .type(AchTransferSimulation.Transaction.Type.TRANSACTION)
                    .build()
            )
        assertThat(achTransferSimulation.declinedTransaction())
            .isEqualTo(
                AchTransferSimulation.DeclinedTransaction.builder()
                    .accountId("string")
                    .amount(123L)
                    .currency(AchTransferSimulation.DeclinedTransaction.Currency.CAD)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .description("string")
                    .id("string")
                    .routeId("string")
                    .routeType(AchTransferSimulation.DeclinedTransaction.RouteType.ACCOUNT_NUMBER)
                    .source(
                        AchTransferSimulation.DeclinedTransaction.Source.builder()
                            .category(
                                AchTransferSimulation.DeclinedTransaction.Source.Category
                                    .ACH_DECLINE
                            )
                            .achDecline(
                                AchTransferSimulation.DeclinedTransaction.Source.AchDecline
                                    .builder()
                                    .amount(123L)
                                    .originatorCompanyName("string")
                                    .originatorCompanyDescriptiveDate("string")
                                    .originatorCompanyDiscretionaryData("string")
                                    .originatorCompanyId("string")
                                    .reason(
                                        AchTransferSimulation.DeclinedTransaction.Source.AchDecline
                                            .Reason
                                            .ACH_ROUTE_CANCELED
                                    )
                                    .receiverIdNumber("string")
                                    .receiverName("string")
                                    .traceNumber("string")
                                    .build()
                            )
                            .cardDecline(
                                AchTransferSimulation.DeclinedTransaction.Source.CardDecline
                                    .builder()
                                    .merchantAcceptorId("string")
                                    .merchantDescriptor("string")
                                    .merchantCategoryCode("string")
                                    .merchantCity("string")
                                    .merchantCountry("string")
                                    .network(
                                        AchTransferSimulation.DeclinedTransaction.Source.CardDecline
                                            .Network
                                            .VISA
                                    )
                                    .networkDetails(
                                        AchTransferSimulation.DeclinedTransaction.Source.CardDecline
                                            .NetworkDetails
                                            .builder()
                                            .visa(
                                                AchTransferSimulation.DeclinedTransaction.Source
                                                    .CardDecline
                                                    .NetworkDetails
                                                    .Visa
                                                    .builder()
                                                    .electronicCommerceIndicator(
                                                        AchTransferSimulation.DeclinedTransaction
                                                            .Source
                                                            .CardDecline
                                                            .NetworkDetails
                                                            .Visa
                                                            .ElectronicCommerceIndicator
                                                            .MAIL_PHONE_ORDER
                                                    )
                                                    .pointOfServiceEntryMode(
                                                        PointOfServiceEntryMode.MANUAL
                                                    )
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .amount(123L)
                                    .currency(
                                        AchTransferSimulation.DeclinedTransaction.Source.CardDecline
                                            .Currency
                                            .CAD
                                    )
                                    .reason(
                                        AchTransferSimulation.DeclinedTransaction.Source.CardDecline
                                            .Reason
                                            .CARD_NOT_ACTIVE
                                    )
                                    .merchantState("string")
                                    .realTimeDecisionId("string")
                                    .digitalWalletTokenId("string")
                                    .build()
                            )
                            .checkDecline(
                                AchTransferSimulation.DeclinedTransaction.Source.CheckDecline
                                    .builder()
                                    .amount(123L)
                                    .auxiliaryOnUs("string")
                                    .reason(
                                        AchTransferSimulation.DeclinedTransaction.Source
                                            .CheckDecline
                                            .Reason
                                            .ACH_ROUTE_CANCELED
                                    )
                                    .build()
                            )
                            .inboundRealTimePaymentsTransferDecline(
                                AchTransferSimulation.DeclinedTransaction.Source
                                    .InboundRealTimePaymentsTransferDecline
                                    .builder()
                                    .amount(123L)
                                    .currency(
                                        AchTransferSimulation.DeclinedTransaction.Source
                                            .InboundRealTimePaymentsTransferDecline
                                            .Currency
                                            .CAD
                                    )
                                    .reason(
                                        AchTransferSimulation.DeclinedTransaction.Source
                                            .InboundRealTimePaymentsTransferDecline
                                            .Reason
                                            .ACCOUNT_NUMBER_CANCELED
                                    )
                                    .creditorName("string")
                                    .debtorName("string")
                                    .debtorAccountNumber("string")
                                    .debtorRoutingNumber("string")
                                    .transactionIdentification("string")
                                    .remittanceInformation("string")
                                    .build()
                            )
                            .internationalAchDecline(
                                AchTransferSimulation.DeclinedTransaction.Source
                                    .InternationalAchDecline
                                    .builder()
                                    .amount(123L)
                                    .foreignExchangeIndicator("string")
                                    .foreignExchangeReferenceIndicator("string")
                                    .foreignExchangeReference("string")
                                    .destinationCountryCode("string")
                                    .destinationCurrencyCode("string")
                                    .foreignPaymentAmount(123L)
                                    .foreignTraceNumber("string")
                                    .internationalTransactionTypeCode("string")
                                    .originatingCurrencyCode("string")
                                    .originatingDepositoryFinancialInstitutionName("string")
                                    .originatingDepositoryFinancialInstitutionIdQualifier("string")
                                    .originatingDepositoryFinancialInstitutionId("string")
                                    .originatingDepositoryFinancialInstitutionBranchCountry(
                                        "string"
                                    )
                                    .originatorCity("string")
                                    .originatorCompanyEntryDescription("string")
                                    .originatorCountry("string")
                                    .originatorIdentification("string")
                                    .originatorName("string")
                                    .originatorPostalCode("string")
                                    .originatorStreetAddress("string")
                                    .originatorStateOrProvince("string")
                                    .paymentRelatedInformation("string")
                                    .paymentRelatedInformation2("string")
                                    .receiverIdentificationNumber("string")
                                    .receiverStreetAddress("string")
                                    .receiverCity("string")
                                    .receiverStateOrProvince("string")
                                    .receiverCountry("string")
                                    .receiverPostalCode("string")
                                    .receivingCompanyOrIndividualName("string")
                                    .receivingDepositoryFinancialInstitutionName("string")
                                    .receivingDepositoryFinancialInstitutionIdQualifier("string")
                                    .receivingDepositoryFinancialInstitutionId("string")
                                    .receivingDepositoryFinancialInstitutionCountry("string")
                                    .traceNumber("string")
                                    .build()
                            )
                            .cardRouteDecline(
                                AchTransferSimulation.DeclinedTransaction.Source.CardRouteDecline
                                    .builder()
                                    .amount(123L)
                                    .currency(
                                        AchTransferSimulation.DeclinedTransaction.Source
                                            .CardRouteDecline
                                            .Currency
                                            .CAD
                                    )
                                    .merchantAcceptorId("string")
                                    .merchantCity("string")
                                    .merchantCountry("string")
                                    .merchantDescriptor("string")
                                    .merchantState("string")
                                    .merchantCategoryCode("string")
                                    .build()
                            )
                            .build()
                    )
                    .type(AchTransferSimulation.DeclinedTransaction.Type.DECLINED_TRANSACTION)
                    .build()
            )
        assertThat(achTransferSimulation.type())
            .isEqualTo(AchTransferSimulation.Type.INBOUND_ACH_TRANSFER_SIMULATION_RESULT)
    }
}
