// File generated from our OpenAPI spec by Stainless.

package com.increase.api.models

import java.time.LocalDate
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class CardPaymentTest {

    @Test
    fun createCardPayment() {
        val cardPayment =
            CardPayment.builder()
                .id("string")
                .accountId("string")
                .cardId("string")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .elements(
                    listOf(
                        CardPayment.Element.builder()
                            .cardAuthorization(
                                CardPayment.Element.CardAuthorization.builder()
                                    .id("string")
                                    .amount(123L)
                                    .cardPaymentId("string")
                                    .cardholderAddress(
                                        CardPayment.Element.CardAuthorization.CardholderAddress
                                            .builder()
                                            .actualLine1("string")
                                            .actualPostalCode("string")
                                            .providedLine1("string")
                                            .providedPostalCode("string")
                                            .verificationResult(
                                                CardPayment.Element.CardAuthorization
                                                    .CardholderAddress
                                                    .VerificationResult
                                                    .NOT_CHECKED
                                            )
                                            .build()
                                    )
                                    .currency(CardPayment.Element.CardAuthorization.Currency.CAD)
                                    .digitalWalletTokenId("string")
                                    .direction(
                                        CardPayment.Element.CardAuthorization.Direction.SETTLEMENT
                                    )
                                    .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .merchantAcceptorId("string")
                                    .merchantCategoryCode("string")
                                    .merchantCity("string")
                                    .merchantCountry("string")
                                    .merchantDescriptor("string")
                                    .networkDetails(
                                        CardPayment.Element.CardAuthorization.NetworkDetails
                                            .builder()
                                            .category(
                                                CardPayment.Element.CardAuthorization.NetworkDetails
                                                    .Category
                                                    .VISA
                                            )
                                            .visa(
                                                CardPayment.Element.CardAuthorization.NetworkDetails
                                                    .Visa
                                                    .builder()
                                                    .electronicCommerceIndicator(
                                                        CardPayment.Element.CardAuthorization
                                                            .NetworkDetails
                                                            .Visa
                                                            .ElectronicCommerceIndicator
                                                            .MAIL_PHONE_ORDER
                                                    )
                                                    .pointOfServiceEntryMode(
                                                        CardPayment.Element.CardAuthorization
                                                            .NetworkDetails
                                                            .Visa
                                                            .PointOfServiceEntryMode
                                                            .UNKNOWN
                                                    )
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .pendingTransactionId("string")
                                    .physicalCardId("string")
                                    .realTimeDecisionId("string")
                                    .type(
                                        CardPayment.Element.CardAuthorization.Type
                                            .CARD_AUTHORIZATION
                                    )
                                    .build()
                            )
                            .cardAuthorizationExpiration(
                                CardPayment.Element.CardAuthorizationExpiration.builder()
                                    .id("string")
                                    .cardAuthorizationId("string")
                                    .currency(
                                        CardPayment.Element.CardAuthorizationExpiration.Currency.CAD
                                    )
                                    .expiredAmount(123L)
                                    .network(
                                        CardPayment.Element.CardAuthorizationExpiration.Network.VISA
                                    )
                                    .type(
                                        CardPayment.Element.CardAuthorizationExpiration.Type
                                            .CARD_AUTHORIZATION_EXPIRATION
                                    )
                                    .build()
                            )
                            .cardDecline(
                                CardPayment.Element.CardDecline.builder()
                                    .id("string")
                                    .amount(123L)
                                    .cardPaymentId("string")
                                    .cardholderAddress(
                                        CardPayment.Element.CardDecline.CardholderAddress.builder()
                                            .actualLine1("string")
                                            .actualPostalCode("string")
                                            .providedLine1("string")
                                            .providedPostalCode("string")
                                            .verificationResult(
                                                CardPayment.Element.CardDecline.CardholderAddress
                                                    .VerificationResult
                                                    .NOT_CHECKED
                                            )
                                            .build()
                                    )
                                    .currency(CardPayment.Element.CardDecline.Currency.CAD)
                                    .digitalWalletTokenId("string")
                                    .merchantAcceptorId("string")
                                    .merchantCategoryCode("string")
                                    .merchantCity("string")
                                    .merchantCountry("string")
                                    .merchantDescriptor("string")
                                    .merchantState("string")
                                    .networkDetails(
                                        CardPayment.Element.CardDecline.NetworkDetails.builder()
                                            .category(
                                                CardPayment.Element.CardDecline.NetworkDetails
                                                    .Category
                                                    .VISA
                                            )
                                            .visa(
                                                CardPayment.Element.CardDecline.NetworkDetails.Visa
                                                    .builder()
                                                    .electronicCommerceIndicator(
                                                        CardPayment.Element.CardDecline
                                                            .NetworkDetails
                                                            .Visa
                                                            .ElectronicCommerceIndicator
                                                            .MAIL_PHONE_ORDER
                                                    )
                                                    .pointOfServiceEntryMode(
                                                        CardPayment.Element.CardDecline
                                                            .NetworkDetails
                                                            .Visa
                                                            .PointOfServiceEntryMode
                                                            .UNKNOWN
                                                    )
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .physicalCardId("string")
                                    .realTimeDecisionId("string")
                                    .reason(CardPayment.Element.CardDecline.Reason.CARD_NOT_ACTIVE)
                                    .build()
                            )
                            .cardIncrement(
                                CardPayment.Element.CardIncrement.builder()
                                    .id("string")
                                    .amount(123L)
                                    .cardAuthorizationId("string")
                                    .currency(CardPayment.Element.CardIncrement.Currency.CAD)
                                    .network(CardPayment.Element.CardIncrement.Network.VISA)
                                    .realTimeDecisionId("string")
                                    .type(CardPayment.Element.CardIncrement.Type.CARD_INCREMENT)
                                    .updatedAuthorizationAmount(123L)
                                    .build()
                            )
                            .cardRefund(
                                CardPayment.Element.CardRefund.builder()
                                    .id("string")
                                    .amount(123L)
                                    .cardPaymentId("string")
                                    .currency(CardPayment.Element.CardRefund.Currency.CAD)
                                    .merchantAcceptorId("string")
                                    .merchantCategoryCode("string")
                                    .merchantCity("string")
                                    .merchantCountry("string")
                                    .merchantName("string")
                                    .merchantState("string")
                                    .purchaseDetails(
                                        CardPayment.Element.CardRefund.PurchaseDetails.builder()
                                            .carRental(
                                                CardPayment.Element.CardRefund.PurchaseDetails
                                                    .CarRental
                                                    .builder()
                                                    .carClassCode("string")
                                                    .checkoutDate(LocalDate.parse("2019-12-27"))
                                                    .dailyRentalRateAmount(123L)
                                                    .dailyRentalRateCurrency("string")
                                                    .daysRented(123L)
                                                    .extraCharges(
                                                        CardPayment.Element.CardRefund
                                                            .PurchaseDetails
                                                            .CarRental
                                                            .ExtraCharges
                                                            .NO_EXTRA_CHARGE
                                                    )
                                                    .fuelChargesAmount(123L)
                                                    .fuelChargesCurrency("string")
                                                    .insuranceChargesAmount(123L)
                                                    .insuranceChargesCurrency("string")
                                                    .noShowIndicator(
                                                        CardPayment.Element.CardRefund
                                                            .PurchaseDetails
                                                            .CarRental
                                                            .NoShowIndicator
                                                            .NOT_APPLICABLE
                                                    )
                                                    .oneWayDropOffChargesAmount(123L)
                                                    .oneWayDropOffChargesCurrency("string")
                                                    .renterName("string")
                                                    .weeklyRentalRateAmount(123L)
                                                    .weeklyRentalRateCurrency("string")
                                                    .build()
                                            )
                                            .customerReferenceIdentifier("string")
                                            .localTaxAmount(123L)
                                            .localTaxCurrency("string")
                                            .lodging(
                                                CardPayment.Element.CardRefund.PurchaseDetails
                                                    .Lodging
                                                    .builder()
                                                    .checkInDate(LocalDate.parse("2019-12-27"))
                                                    .dailyRoomRateAmount(123L)
                                                    .dailyRoomRateCurrency("string")
                                                    .extraCharges(
                                                        CardPayment.Element.CardRefund
                                                            .PurchaseDetails
                                                            .Lodging
                                                            .ExtraCharges
                                                            .NO_EXTRA_CHARGE
                                                    )
                                                    .folioCashAdvancesAmount(123L)
                                                    .folioCashAdvancesCurrency("string")
                                                    .foodBeverageChargesAmount(123L)
                                                    .foodBeverageChargesCurrency("string")
                                                    .noShowIndicator(
                                                        CardPayment.Element.CardRefund
                                                            .PurchaseDetails
                                                            .Lodging
                                                            .NoShowIndicator
                                                            .NOT_APPLICABLE
                                                    )
                                                    .prepaidExpensesAmount(123L)
                                                    .prepaidExpensesCurrency("string")
                                                    .roomNights(123L)
                                                    .totalRoomTaxAmount(123L)
                                                    .totalRoomTaxCurrency("string")
                                                    .totalTaxAmount(123L)
                                                    .totalTaxCurrency("string")
                                                    .build()
                                            )
                                            .nationalTaxAmount(123L)
                                            .nationalTaxCurrency("string")
                                            .purchaseIdentifier("string")
                                            .purchaseIdentifierFormat(
                                                CardPayment.Element.CardRefund.PurchaseDetails
                                                    .PurchaseIdentifierFormat
                                                    .FREE_TEXT
                                            )
                                            .travel(
                                                CardPayment.Element.CardRefund.PurchaseDetails
                                                    .Travel
                                                    .builder()
                                                    .ancillary(
                                                        CardPayment.Element.CardRefund
                                                            .PurchaseDetails
                                                            .Travel
                                                            .Ancillary
                                                            .builder()
                                                            .connectedTicketDocumentNumber("string")
                                                            .creditReasonIndicator(
                                                                CardPayment.Element.CardRefund
                                                                    .PurchaseDetails
                                                                    .Travel
                                                                    .Ancillary
                                                                    .CreditReasonIndicator
                                                                    .NO_CREDIT
                                                            )
                                                            .passengerNameOrDescription("string")
                                                            .services(
                                                                listOf(
                                                                    CardPayment.Element.CardRefund
                                                                        .PurchaseDetails
                                                                        .Travel
                                                                        .Ancillary
                                                                        .Service
                                                                        .builder()
                                                                        .category(
                                                                            CardPayment.Element
                                                                                .CardRefund
                                                                                .PurchaseDetails
                                                                                .Travel
                                                                                .Ancillary
                                                                                .Service
                                                                                .Category
                                                                                .NONE
                                                                        )
                                                                        .subCategory("string")
                                                                        .build()
                                                                )
                                                            )
                                                            .ticketDocumentNumber("string")
                                                            .build()
                                                    )
                                                    .computerizedReservationSystem("string")
                                                    .creditReasonIndicator(
                                                        CardPayment.Element.CardRefund
                                                            .PurchaseDetails
                                                            .Travel
                                                            .CreditReasonIndicator
                                                            .NO_CREDIT
                                                    )
                                                    .departureDate(LocalDate.parse("2019-12-27"))
                                                    .originationCityAirportCode("string")
                                                    .passengerName("string")
                                                    .restrictedTicketIndicator(
                                                        CardPayment.Element.CardRefund
                                                            .PurchaseDetails
                                                            .Travel
                                                            .RestrictedTicketIndicator
                                                            .NO_RESTRICTIONS
                                                    )
                                                    .ticketChangeIndicator(
                                                        CardPayment.Element.CardRefund
                                                            .PurchaseDetails
                                                            .Travel
                                                            .TicketChangeIndicator
                                                            .NONE
                                                    )
                                                    .ticketNumber("string")
                                                    .travelAgencyCode("string")
                                                    .travelAgencyName("string")
                                                    .tripLegs(
                                                        listOf(
                                                            CardPayment.Element.CardRefund
                                                                .PurchaseDetails
                                                                .Travel
                                                                .TripLeg
                                                                .builder()
                                                                .carrierCode("string")
                                                                .destinationCityAirportCode(
                                                                    "string"
                                                                )
                                                                .fareBasisCode("string")
                                                                .flightNumber("string")
                                                                .serviceClass("string")
                                                                .stopOverCode(
                                                                    CardPayment.Element.CardRefund
                                                                        .PurchaseDetails
                                                                        .Travel
                                                                        .TripLeg
                                                                        .StopOverCode
                                                                        .NONE
                                                                )
                                                                .build()
                                                        )
                                                    )
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .transactionId("string")
                                    .type(CardPayment.Element.CardRefund.Type.CARD_REFUND)
                                    .build()
                            )
                            .cardReversal(
                                CardPayment.Element.CardReversal.builder()
                                    .id("string")
                                    .cardAuthorizationId("string")
                                    .currency(CardPayment.Element.CardReversal.Currency.CAD)
                                    .network(CardPayment.Element.CardReversal.Network.VISA)
                                    .reversalAmount(123L)
                                    .type(CardPayment.Element.CardReversal.Type.CARD_REVERSAL)
                                    .updatedAuthorizationAmount(123L)
                                    .build()
                            )
                            .cardSettlement(
                                CardPayment.Element.CardSettlement.builder()
                                    .id("string")
                                    .amount(123L)
                                    .cardAuthorization("string")
                                    .cardPaymentId("string")
                                    .currency(CardPayment.Element.CardSettlement.Currency.CAD)
                                    .merchantAcceptorId("string")
                                    .merchantCategoryCode("string")
                                    .merchantCity("string")
                                    .merchantCountry("string")
                                    .merchantName("string")
                                    .merchantState("string")
                                    .pendingTransactionId("string")
                                    .presentmentAmount(123L)
                                    .presentmentCurrency("string")
                                    .purchaseDetails(
                                        CardPayment.Element.CardSettlement.PurchaseDetails.builder()
                                            .carRental(
                                                CardPayment.Element.CardSettlement.PurchaseDetails
                                                    .CarRental
                                                    .builder()
                                                    .carClassCode("string")
                                                    .checkoutDate(LocalDate.parse("2019-12-27"))
                                                    .dailyRentalRateAmount(123L)
                                                    .dailyRentalRateCurrency("string")
                                                    .daysRented(123L)
                                                    .extraCharges(
                                                        CardPayment.Element.CardSettlement
                                                            .PurchaseDetails
                                                            .CarRental
                                                            .ExtraCharges
                                                            .NO_EXTRA_CHARGE
                                                    )
                                                    .fuelChargesAmount(123L)
                                                    .fuelChargesCurrency("string")
                                                    .insuranceChargesAmount(123L)
                                                    .insuranceChargesCurrency("string")
                                                    .noShowIndicator(
                                                        CardPayment.Element.CardSettlement
                                                            .PurchaseDetails
                                                            .CarRental
                                                            .NoShowIndicator
                                                            .NOT_APPLICABLE
                                                    )
                                                    .oneWayDropOffChargesAmount(123L)
                                                    .oneWayDropOffChargesCurrency("string")
                                                    .renterName("string")
                                                    .weeklyRentalRateAmount(123L)
                                                    .weeklyRentalRateCurrency("string")
                                                    .build()
                                            )
                                            .customerReferenceIdentifier("string")
                                            .localTaxAmount(123L)
                                            .localTaxCurrency("string")
                                            .lodging(
                                                CardPayment.Element.CardSettlement.PurchaseDetails
                                                    .Lodging
                                                    .builder()
                                                    .checkInDate(LocalDate.parse("2019-12-27"))
                                                    .dailyRoomRateAmount(123L)
                                                    .dailyRoomRateCurrency("string")
                                                    .extraCharges(
                                                        CardPayment.Element.CardSettlement
                                                            .PurchaseDetails
                                                            .Lodging
                                                            .ExtraCharges
                                                            .NO_EXTRA_CHARGE
                                                    )
                                                    .folioCashAdvancesAmount(123L)
                                                    .folioCashAdvancesCurrency("string")
                                                    .foodBeverageChargesAmount(123L)
                                                    .foodBeverageChargesCurrency("string")
                                                    .noShowIndicator(
                                                        CardPayment.Element.CardSettlement
                                                            .PurchaseDetails
                                                            .Lodging
                                                            .NoShowIndicator
                                                            .NOT_APPLICABLE
                                                    )
                                                    .prepaidExpensesAmount(123L)
                                                    .prepaidExpensesCurrency("string")
                                                    .roomNights(123L)
                                                    .totalRoomTaxAmount(123L)
                                                    .totalRoomTaxCurrency("string")
                                                    .totalTaxAmount(123L)
                                                    .totalTaxCurrency("string")
                                                    .build()
                                            )
                                            .nationalTaxAmount(123L)
                                            .nationalTaxCurrency("string")
                                            .purchaseIdentifier("string")
                                            .purchaseIdentifierFormat(
                                                CardPayment.Element.CardSettlement.PurchaseDetails
                                                    .PurchaseIdentifierFormat
                                                    .FREE_TEXT
                                            )
                                            .travel(
                                                CardPayment.Element.CardSettlement.PurchaseDetails
                                                    .Travel
                                                    .builder()
                                                    .ancillary(
                                                        CardPayment.Element.CardSettlement
                                                            .PurchaseDetails
                                                            .Travel
                                                            .Ancillary
                                                            .builder()
                                                            .connectedTicketDocumentNumber("string")
                                                            .creditReasonIndicator(
                                                                CardPayment.Element.CardSettlement
                                                                    .PurchaseDetails
                                                                    .Travel
                                                                    .Ancillary
                                                                    .CreditReasonIndicator
                                                                    .NO_CREDIT
                                                            )
                                                            .passengerNameOrDescription("string")
                                                            .services(
                                                                listOf(
                                                                    CardPayment.Element
                                                                        .CardSettlement
                                                                        .PurchaseDetails
                                                                        .Travel
                                                                        .Ancillary
                                                                        .Service
                                                                        .builder()
                                                                        .category(
                                                                            CardPayment.Element
                                                                                .CardSettlement
                                                                                .PurchaseDetails
                                                                                .Travel
                                                                                .Ancillary
                                                                                .Service
                                                                                .Category
                                                                                .NONE
                                                                        )
                                                                        .subCategory("string")
                                                                        .build()
                                                                )
                                                            )
                                                            .ticketDocumentNumber("string")
                                                            .build()
                                                    )
                                                    .computerizedReservationSystem("string")
                                                    .creditReasonIndicator(
                                                        CardPayment.Element.CardSettlement
                                                            .PurchaseDetails
                                                            .Travel
                                                            .CreditReasonIndicator
                                                            .NO_CREDIT
                                                    )
                                                    .departureDate(LocalDate.parse("2019-12-27"))
                                                    .originationCityAirportCode("string")
                                                    .passengerName("string")
                                                    .restrictedTicketIndicator(
                                                        CardPayment.Element.CardSettlement
                                                            .PurchaseDetails
                                                            .Travel
                                                            .RestrictedTicketIndicator
                                                            .NO_RESTRICTIONS
                                                    )
                                                    .ticketChangeIndicator(
                                                        CardPayment.Element.CardSettlement
                                                            .PurchaseDetails
                                                            .Travel
                                                            .TicketChangeIndicator
                                                            .NONE
                                                    )
                                                    .ticketNumber("string")
                                                    .travelAgencyCode("string")
                                                    .travelAgencyName("string")
                                                    .tripLegs(
                                                        listOf(
                                                            CardPayment.Element.CardSettlement
                                                                .PurchaseDetails
                                                                .Travel
                                                                .TripLeg
                                                                .builder()
                                                                .carrierCode("string")
                                                                .destinationCityAirportCode(
                                                                    "string"
                                                                )
                                                                .fareBasisCode("string")
                                                                .flightNumber("string")
                                                                .serviceClass("string")
                                                                .stopOverCode(
                                                                    CardPayment.Element
                                                                        .CardSettlement
                                                                        .PurchaseDetails
                                                                        .Travel
                                                                        .TripLeg
                                                                        .StopOverCode
                                                                        .NONE
                                                                )
                                                                .build()
                                                        )
                                                    )
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .transactionId("string")
                                    .type(CardPayment.Element.CardSettlement.Type.CARD_SETTLEMENT)
                                    .build()
                            )
                            .cardValidation(
                                CardPayment.Element.CardValidation.builder()
                                    .id("string")
                                    .cardPaymentId("string")
                                    .cardholderAddress(
                                        CardPayment.Element.CardValidation.CardholderAddress
                                            .builder()
                                            .actualLine1("string")
                                            .actualPostalCode("string")
                                            .providedLine1("string")
                                            .providedPostalCode("string")
                                            .verificationResult(
                                                CardPayment.Element.CardValidation.CardholderAddress
                                                    .VerificationResult
                                                    .NOT_CHECKED
                                            )
                                            .build()
                                    )
                                    .currency(CardPayment.Element.CardValidation.Currency.CAD)
                                    .digitalWalletTokenId("string")
                                    .merchantAcceptorId("string")
                                    .merchantCategoryCode("string")
                                    .merchantCity("string")
                                    .merchantCountry("string")
                                    .merchantDescriptor("string")
                                    .networkDetails(
                                        CardPayment.Element.CardValidation.NetworkDetails.builder()
                                            .category(
                                                CardPayment.Element.CardValidation.NetworkDetails
                                                    .Category
                                                    .VISA
                                            )
                                            .visa(
                                                CardPayment.Element.CardValidation.NetworkDetails
                                                    .Visa
                                                    .builder()
                                                    .electronicCommerceIndicator(
                                                        CardPayment.Element.CardValidation
                                                            .NetworkDetails
                                                            .Visa
                                                            .ElectronicCommerceIndicator
                                                            .MAIL_PHONE_ORDER
                                                    )
                                                    .pointOfServiceEntryMode(
                                                        CardPayment.Element.CardValidation
                                                            .NetworkDetails
                                                            .Visa
                                                            .PointOfServiceEntryMode
                                                            .UNKNOWN
                                                    )
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .physicalCardId("string")
                                    .realTimeDecisionId("string")
                                    .type(CardPayment.Element.CardValidation.Type.CARD_VALIDATION)
                                    .build()
                            )
                            .category(CardPayment.Element.Category.CARD_AUTHORIZATION)
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                )
                .state(
                    CardPayment.State.builder()
                        .authorizedAmount(123L)
                        .incrementedAmount(123L)
                        .reversedAmount(123L)
                        .settledAmount(123L)
                        .build()
                )
                .type(CardPayment.Type.CARD_PAYMENT)
                .build()
        assertThat(cardPayment).isNotNull
        assertThat(cardPayment.id()).isEqualTo("string")
        assertThat(cardPayment.accountId()).isEqualTo("string")
        assertThat(cardPayment.cardId()).isEqualTo("string")
        assertThat(cardPayment.createdAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(cardPayment.elements())
            .containsExactly(
                CardPayment.Element.builder()
                    .cardAuthorization(
                        CardPayment.Element.CardAuthorization.builder()
                            .id("string")
                            .amount(123L)
                            .cardPaymentId("string")
                            .cardholderAddress(
                                CardPayment.Element.CardAuthorization.CardholderAddress.builder()
                                    .actualLine1("string")
                                    .actualPostalCode("string")
                                    .providedLine1("string")
                                    .providedPostalCode("string")
                                    .verificationResult(
                                        CardPayment.Element.CardAuthorization.CardholderAddress
                                            .VerificationResult
                                            .NOT_CHECKED
                                    )
                                    .build()
                            )
                            .currency(CardPayment.Element.CardAuthorization.Currency.CAD)
                            .digitalWalletTokenId("string")
                            .direction(CardPayment.Element.CardAuthorization.Direction.SETTLEMENT)
                            .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .merchantAcceptorId("string")
                            .merchantCategoryCode("string")
                            .merchantCity("string")
                            .merchantCountry("string")
                            .merchantDescriptor("string")
                            .networkDetails(
                                CardPayment.Element.CardAuthorization.NetworkDetails.builder()
                                    .category(
                                        CardPayment.Element.CardAuthorization.NetworkDetails
                                            .Category
                                            .VISA
                                    )
                                    .visa(
                                        CardPayment.Element.CardAuthorization.NetworkDetails.Visa
                                            .builder()
                                            .electronicCommerceIndicator(
                                                CardPayment.Element.CardAuthorization.NetworkDetails
                                                    .Visa
                                                    .ElectronicCommerceIndicator
                                                    .MAIL_PHONE_ORDER
                                            )
                                            .pointOfServiceEntryMode(
                                                CardPayment.Element.CardAuthorization.NetworkDetails
                                                    .Visa
                                                    .PointOfServiceEntryMode
                                                    .UNKNOWN
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .pendingTransactionId("string")
                            .physicalCardId("string")
                            .realTimeDecisionId("string")
                            .type(CardPayment.Element.CardAuthorization.Type.CARD_AUTHORIZATION)
                            .build()
                    )
                    .cardAuthorizationExpiration(
                        CardPayment.Element.CardAuthorizationExpiration.builder()
                            .id("string")
                            .cardAuthorizationId("string")
                            .currency(CardPayment.Element.CardAuthorizationExpiration.Currency.CAD)
                            .expiredAmount(123L)
                            .network(CardPayment.Element.CardAuthorizationExpiration.Network.VISA)
                            .type(
                                CardPayment.Element.CardAuthorizationExpiration.Type
                                    .CARD_AUTHORIZATION_EXPIRATION
                            )
                            .build()
                    )
                    .cardDecline(
                        CardPayment.Element.CardDecline.builder()
                            .id("string")
                            .amount(123L)
                            .cardPaymentId("string")
                            .cardholderAddress(
                                CardPayment.Element.CardDecline.CardholderAddress.builder()
                                    .actualLine1("string")
                                    .actualPostalCode("string")
                                    .providedLine1("string")
                                    .providedPostalCode("string")
                                    .verificationResult(
                                        CardPayment.Element.CardDecline.CardholderAddress
                                            .VerificationResult
                                            .NOT_CHECKED
                                    )
                                    .build()
                            )
                            .currency(CardPayment.Element.CardDecline.Currency.CAD)
                            .digitalWalletTokenId("string")
                            .merchantAcceptorId("string")
                            .merchantCategoryCode("string")
                            .merchantCity("string")
                            .merchantCountry("string")
                            .merchantDescriptor("string")
                            .merchantState("string")
                            .networkDetails(
                                CardPayment.Element.CardDecline.NetworkDetails.builder()
                                    .category(
                                        CardPayment.Element.CardDecline.NetworkDetails.Category.VISA
                                    )
                                    .visa(
                                        CardPayment.Element.CardDecline.NetworkDetails.Visa
                                            .builder()
                                            .electronicCommerceIndicator(
                                                CardPayment.Element.CardDecline.NetworkDetails.Visa
                                                    .ElectronicCommerceIndicator
                                                    .MAIL_PHONE_ORDER
                                            )
                                            .pointOfServiceEntryMode(
                                                CardPayment.Element.CardDecline.NetworkDetails.Visa
                                                    .PointOfServiceEntryMode
                                                    .UNKNOWN
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .physicalCardId("string")
                            .realTimeDecisionId("string")
                            .reason(CardPayment.Element.CardDecline.Reason.CARD_NOT_ACTIVE)
                            .build()
                    )
                    .cardIncrement(
                        CardPayment.Element.CardIncrement.builder()
                            .id("string")
                            .amount(123L)
                            .cardAuthorizationId("string")
                            .currency(CardPayment.Element.CardIncrement.Currency.CAD)
                            .network(CardPayment.Element.CardIncrement.Network.VISA)
                            .realTimeDecisionId("string")
                            .type(CardPayment.Element.CardIncrement.Type.CARD_INCREMENT)
                            .updatedAuthorizationAmount(123L)
                            .build()
                    )
                    .cardRefund(
                        CardPayment.Element.CardRefund.builder()
                            .id("string")
                            .amount(123L)
                            .cardPaymentId("string")
                            .currency(CardPayment.Element.CardRefund.Currency.CAD)
                            .merchantAcceptorId("string")
                            .merchantCategoryCode("string")
                            .merchantCity("string")
                            .merchantCountry("string")
                            .merchantName("string")
                            .merchantState("string")
                            .purchaseDetails(
                                CardPayment.Element.CardRefund.PurchaseDetails.builder()
                                    .carRental(
                                        CardPayment.Element.CardRefund.PurchaseDetails.CarRental
                                            .builder()
                                            .carClassCode("string")
                                            .checkoutDate(LocalDate.parse("2019-12-27"))
                                            .dailyRentalRateAmount(123L)
                                            .dailyRentalRateCurrency("string")
                                            .daysRented(123L)
                                            .extraCharges(
                                                CardPayment.Element.CardRefund.PurchaseDetails
                                                    .CarRental
                                                    .ExtraCharges
                                                    .NO_EXTRA_CHARGE
                                            )
                                            .fuelChargesAmount(123L)
                                            .fuelChargesCurrency("string")
                                            .insuranceChargesAmount(123L)
                                            .insuranceChargesCurrency("string")
                                            .noShowIndicator(
                                                CardPayment.Element.CardRefund.PurchaseDetails
                                                    .CarRental
                                                    .NoShowIndicator
                                                    .NOT_APPLICABLE
                                            )
                                            .oneWayDropOffChargesAmount(123L)
                                            .oneWayDropOffChargesCurrency("string")
                                            .renterName("string")
                                            .weeklyRentalRateAmount(123L)
                                            .weeklyRentalRateCurrency("string")
                                            .build()
                                    )
                                    .customerReferenceIdentifier("string")
                                    .localTaxAmount(123L)
                                    .localTaxCurrency("string")
                                    .lodging(
                                        CardPayment.Element.CardRefund.PurchaseDetails.Lodging
                                            .builder()
                                            .checkInDate(LocalDate.parse("2019-12-27"))
                                            .dailyRoomRateAmount(123L)
                                            .dailyRoomRateCurrency("string")
                                            .extraCharges(
                                                CardPayment.Element.CardRefund.PurchaseDetails
                                                    .Lodging
                                                    .ExtraCharges
                                                    .NO_EXTRA_CHARGE
                                            )
                                            .folioCashAdvancesAmount(123L)
                                            .folioCashAdvancesCurrency("string")
                                            .foodBeverageChargesAmount(123L)
                                            .foodBeverageChargesCurrency("string")
                                            .noShowIndicator(
                                                CardPayment.Element.CardRefund.PurchaseDetails
                                                    .Lodging
                                                    .NoShowIndicator
                                                    .NOT_APPLICABLE
                                            )
                                            .prepaidExpensesAmount(123L)
                                            .prepaidExpensesCurrency("string")
                                            .roomNights(123L)
                                            .totalRoomTaxAmount(123L)
                                            .totalRoomTaxCurrency("string")
                                            .totalTaxAmount(123L)
                                            .totalTaxCurrency("string")
                                            .build()
                                    )
                                    .nationalTaxAmount(123L)
                                    .nationalTaxCurrency("string")
                                    .purchaseIdentifier("string")
                                    .purchaseIdentifierFormat(
                                        CardPayment.Element.CardRefund.PurchaseDetails
                                            .PurchaseIdentifierFormat
                                            .FREE_TEXT
                                    )
                                    .travel(
                                        CardPayment.Element.CardRefund.PurchaseDetails.Travel
                                            .builder()
                                            .ancillary(
                                                CardPayment.Element.CardRefund.PurchaseDetails
                                                    .Travel
                                                    .Ancillary
                                                    .builder()
                                                    .connectedTicketDocumentNumber("string")
                                                    .creditReasonIndicator(
                                                        CardPayment.Element.CardRefund
                                                            .PurchaseDetails
                                                            .Travel
                                                            .Ancillary
                                                            .CreditReasonIndicator
                                                            .NO_CREDIT
                                                    )
                                                    .passengerNameOrDescription("string")
                                                    .services(
                                                        listOf(
                                                            CardPayment.Element.CardRefund
                                                                .PurchaseDetails
                                                                .Travel
                                                                .Ancillary
                                                                .Service
                                                                .builder()
                                                                .category(
                                                                    CardPayment.Element.CardRefund
                                                                        .PurchaseDetails
                                                                        .Travel
                                                                        .Ancillary
                                                                        .Service
                                                                        .Category
                                                                        .NONE
                                                                )
                                                                .subCategory("string")
                                                                .build()
                                                        )
                                                    )
                                                    .ticketDocumentNumber("string")
                                                    .build()
                                            )
                                            .computerizedReservationSystem("string")
                                            .creditReasonIndicator(
                                                CardPayment.Element.CardRefund.PurchaseDetails
                                                    .Travel
                                                    .CreditReasonIndicator
                                                    .NO_CREDIT
                                            )
                                            .departureDate(LocalDate.parse("2019-12-27"))
                                            .originationCityAirportCode("string")
                                            .passengerName("string")
                                            .restrictedTicketIndicator(
                                                CardPayment.Element.CardRefund.PurchaseDetails
                                                    .Travel
                                                    .RestrictedTicketIndicator
                                                    .NO_RESTRICTIONS
                                            )
                                            .ticketChangeIndicator(
                                                CardPayment.Element.CardRefund.PurchaseDetails
                                                    .Travel
                                                    .TicketChangeIndicator
                                                    .NONE
                                            )
                                            .ticketNumber("string")
                                            .travelAgencyCode("string")
                                            .travelAgencyName("string")
                                            .tripLegs(
                                                listOf(
                                                    CardPayment.Element.CardRefund.PurchaseDetails
                                                        .Travel
                                                        .TripLeg
                                                        .builder()
                                                        .carrierCode("string")
                                                        .destinationCityAirportCode("string")
                                                        .fareBasisCode("string")
                                                        .flightNumber("string")
                                                        .serviceClass("string")
                                                        .stopOverCode(
                                                            CardPayment.Element.CardRefund
                                                                .PurchaseDetails
                                                                .Travel
                                                                .TripLeg
                                                                .StopOverCode
                                                                .NONE
                                                        )
                                                        .build()
                                                )
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .transactionId("string")
                            .type(CardPayment.Element.CardRefund.Type.CARD_REFUND)
                            .build()
                    )
                    .cardReversal(
                        CardPayment.Element.CardReversal.builder()
                            .id("string")
                            .cardAuthorizationId("string")
                            .currency(CardPayment.Element.CardReversal.Currency.CAD)
                            .network(CardPayment.Element.CardReversal.Network.VISA)
                            .reversalAmount(123L)
                            .type(CardPayment.Element.CardReversal.Type.CARD_REVERSAL)
                            .updatedAuthorizationAmount(123L)
                            .build()
                    )
                    .cardSettlement(
                        CardPayment.Element.CardSettlement.builder()
                            .id("string")
                            .amount(123L)
                            .cardAuthorization("string")
                            .cardPaymentId("string")
                            .currency(CardPayment.Element.CardSettlement.Currency.CAD)
                            .merchantAcceptorId("string")
                            .merchantCategoryCode("string")
                            .merchantCity("string")
                            .merchantCountry("string")
                            .merchantName("string")
                            .merchantState("string")
                            .pendingTransactionId("string")
                            .presentmentAmount(123L)
                            .presentmentCurrency("string")
                            .purchaseDetails(
                                CardPayment.Element.CardSettlement.PurchaseDetails.builder()
                                    .carRental(
                                        CardPayment.Element.CardSettlement.PurchaseDetails.CarRental
                                            .builder()
                                            .carClassCode("string")
                                            .checkoutDate(LocalDate.parse("2019-12-27"))
                                            .dailyRentalRateAmount(123L)
                                            .dailyRentalRateCurrency("string")
                                            .daysRented(123L)
                                            .extraCharges(
                                                CardPayment.Element.CardSettlement.PurchaseDetails
                                                    .CarRental
                                                    .ExtraCharges
                                                    .NO_EXTRA_CHARGE
                                            )
                                            .fuelChargesAmount(123L)
                                            .fuelChargesCurrency("string")
                                            .insuranceChargesAmount(123L)
                                            .insuranceChargesCurrency("string")
                                            .noShowIndicator(
                                                CardPayment.Element.CardSettlement.PurchaseDetails
                                                    .CarRental
                                                    .NoShowIndicator
                                                    .NOT_APPLICABLE
                                            )
                                            .oneWayDropOffChargesAmount(123L)
                                            .oneWayDropOffChargesCurrency("string")
                                            .renterName("string")
                                            .weeklyRentalRateAmount(123L)
                                            .weeklyRentalRateCurrency("string")
                                            .build()
                                    )
                                    .customerReferenceIdentifier("string")
                                    .localTaxAmount(123L)
                                    .localTaxCurrency("string")
                                    .lodging(
                                        CardPayment.Element.CardSettlement.PurchaseDetails.Lodging
                                            .builder()
                                            .checkInDate(LocalDate.parse("2019-12-27"))
                                            .dailyRoomRateAmount(123L)
                                            .dailyRoomRateCurrency("string")
                                            .extraCharges(
                                                CardPayment.Element.CardSettlement.PurchaseDetails
                                                    .Lodging
                                                    .ExtraCharges
                                                    .NO_EXTRA_CHARGE
                                            )
                                            .folioCashAdvancesAmount(123L)
                                            .folioCashAdvancesCurrency("string")
                                            .foodBeverageChargesAmount(123L)
                                            .foodBeverageChargesCurrency("string")
                                            .noShowIndicator(
                                                CardPayment.Element.CardSettlement.PurchaseDetails
                                                    .Lodging
                                                    .NoShowIndicator
                                                    .NOT_APPLICABLE
                                            )
                                            .prepaidExpensesAmount(123L)
                                            .prepaidExpensesCurrency("string")
                                            .roomNights(123L)
                                            .totalRoomTaxAmount(123L)
                                            .totalRoomTaxCurrency("string")
                                            .totalTaxAmount(123L)
                                            .totalTaxCurrency("string")
                                            .build()
                                    )
                                    .nationalTaxAmount(123L)
                                    .nationalTaxCurrency("string")
                                    .purchaseIdentifier("string")
                                    .purchaseIdentifierFormat(
                                        CardPayment.Element.CardSettlement.PurchaseDetails
                                            .PurchaseIdentifierFormat
                                            .FREE_TEXT
                                    )
                                    .travel(
                                        CardPayment.Element.CardSettlement.PurchaseDetails.Travel
                                            .builder()
                                            .ancillary(
                                                CardPayment.Element.CardSettlement.PurchaseDetails
                                                    .Travel
                                                    .Ancillary
                                                    .builder()
                                                    .connectedTicketDocumentNumber("string")
                                                    .creditReasonIndicator(
                                                        CardPayment.Element.CardSettlement
                                                            .PurchaseDetails
                                                            .Travel
                                                            .Ancillary
                                                            .CreditReasonIndicator
                                                            .NO_CREDIT
                                                    )
                                                    .passengerNameOrDescription("string")
                                                    .services(
                                                        listOf(
                                                            CardPayment.Element.CardSettlement
                                                                .PurchaseDetails
                                                                .Travel
                                                                .Ancillary
                                                                .Service
                                                                .builder()
                                                                .category(
                                                                    CardPayment.Element
                                                                        .CardSettlement
                                                                        .PurchaseDetails
                                                                        .Travel
                                                                        .Ancillary
                                                                        .Service
                                                                        .Category
                                                                        .NONE
                                                                )
                                                                .subCategory("string")
                                                                .build()
                                                        )
                                                    )
                                                    .ticketDocumentNumber("string")
                                                    .build()
                                            )
                                            .computerizedReservationSystem("string")
                                            .creditReasonIndicator(
                                                CardPayment.Element.CardSettlement.PurchaseDetails
                                                    .Travel
                                                    .CreditReasonIndicator
                                                    .NO_CREDIT
                                            )
                                            .departureDate(LocalDate.parse("2019-12-27"))
                                            .originationCityAirportCode("string")
                                            .passengerName("string")
                                            .restrictedTicketIndicator(
                                                CardPayment.Element.CardSettlement.PurchaseDetails
                                                    .Travel
                                                    .RestrictedTicketIndicator
                                                    .NO_RESTRICTIONS
                                            )
                                            .ticketChangeIndicator(
                                                CardPayment.Element.CardSettlement.PurchaseDetails
                                                    .Travel
                                                    .TicketChangeIndicator
                                                    .NONE
                                            )
                                            .ticketNumber("string")
                                            .travelAgencyCode("string")
                                            .travelAgencyName("string")
                                            .tripLegs(
                                                listOf(
                                                    CardPayment.Element.CardSettlement
                                                        .PurchaseDetails
                                                        .Travel
                                                        .TripLeg
                                                        .builder()
                                                        .carrierCode("string")
                                                        .destinationCityAirportCode("string")
                                                        .fareBasisCode("string")
                                                        .flightNumber("string")
                                                        .serviceClass("string")
                                                        .stopOverCode(
                                                            CardPayment.Element.CardSettlement
                                                                .PurchaseDetails
                                                                .Travel
                                                                .TripLeg
                                                                .StopOverCode
                                                                .NONE
                                                        )
                                                        .build()
                                                )
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .transactionId("string")
                            .type(CardPayment.Element.CardSettlement.Type.CARD_SETTLEMENT)
                            .build()
                    )
                    .cardValidation(
                        CardPayment.Element.CardValidation.builder()
                            .id("string")
                            .cardPaymentId("string")
                            .cardholderAddress(
                                CardPayment.Element.CardValidation.CardholderAddress.builder()
                                    .actualLine1("string")
                                    .actualPostalCode("string")
                                    .providedLine1("string")
                                    .providedPostalCode("string")
                                    .verificationResult(
                                        CardPayment.Element.CardValidation.CardholderAddress
                                            .VerificationResult
                                            .NOT_CHECKED
                                    )
                                    .build()
                            )
                            .currency(CardPayment.Element.CardValidation.Currency.CAD)
                            .digitalWalletTokenId("string")
                            .merchantAcceptorId("string")
                            .merchantCategoryCode("string")
                            .merchantCity("string")
                            .merchantCountry("string")
                            .merchantDescriptor("string")
                            .networkDetails(
                                CardPayment.Element.CardValidation.NetworkDetails.builder()
                                    .category(
                                        CardPayment.Element.CardValidation.NetworkDetails.Category
                                            .VISA
                                    )
                                    .visa(
                                        CardPayment.Element.CardValidation.NetworkDetails.Visa
                                            .builder()
                                            .electronicCommerceIndicator(
                                                CardPayment.Element.CardValidation.NetworkDetails
                                                    .Visa
                                                    .ElectronicCommerceIndicator
                                                    .MAIL_PHONE_ORDER
                                            )
                                            .pointOfServiceEntryMode(
                                                CardPayment.Element.CardValidation.NetworkDetails
                                                    .Visa
                                                    .PointOfServiceEntryMode
                                                    .UNKNOWN
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .physicalCardId("string")
                            .realTimeDecisionId("string")
                            .type(CardPayment.Element.CardValidation.Type.CARD_VALIDATION)
                            .build()
                    )
                    .category(CardPayment.Element.Category.CARD_AUTHORIZATION)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        assertThat(cardPayment.state())
            .isEqualTo(
                CardPayment.State.builder()
                    .authorizedAmount(123L)
                    .incrementedAmount(123L)
                    .reversedAmount(123L)
                    .settledAmount(123L)
                    .build()
            )
        assertThat(cardPayment.type()).isEqualTo(CardPayment.Type.CARD_PAYMENT)
    }
}
