// File generated from our OpenAPI spec by Stainless.

package com.increase.api.models

import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class CardAuthorizationSimulationTest {

    @Test
    fun createCardAuthorizationSimulation() {
        val cardAuthorizationSimulation =
            CardAuthorizationSimulation.builder()
                .declinedTransaction(
                    CardAuthorizationSimulation.DeclinedTransaction.builder()
                        .id("id")
                        .accountId("account_id")
                        .amount(123L)
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .currency(CardAuthorizationSimulation.DeclinedTransaction.Currency.CAD)
                        .description("description")
                        .routeId("route_id")
                        .routeType(
                            CardAuthorizationSimulation.DeclinedTransaction.RouteType.ACCOUNT_NUMBER
                        )
                        .source(
                            CardAuthorizationSimulation.DeclinedTransaction.Source.builder()
                                .achDecline(
                                    CardAuthorizationSimulation.DeclinedTransaction.Source
                                        .AchDecline
                                        .builder()
                                        .id("id")
                                        .amount(123L)
                                        .inboundAchTransferId("inbound_ach_transfer_id")
                                        .originatorCompanyDescriptiveDate(
                                            "originator_company_descriptive_date"
                                        )
                                        .originatorCompanyDiscretionaryData(
                                            "originator_company_discretionary_data"
                                        )
                                        .originatorCompanyId("originator_company_id")
                                        .originatorCompanyName("originator_company_name")
                                        .reason(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .AchDecline
                                                .Reason
                                                .ACH_ROUTE_CANCELED
                                        )
                                        .receiverIdNumber("receiver_id_number")
                                        .receiverName("receiver_name")
                                        .traceNumber("trace_number")
                                        .type(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .AchDecline
                                                .Type
                                                .ACH_DECLINE
                                        )
                                        .build()
                                )
                                .cardDecline(
                                    CardAuthorizationSimulation.DeclinedTransaction.Source
                                        .CardDecline
                                        .builder()
                                        .id("id")
                                        .actioner(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .CardDecline
                                                .Actioner
                                                .USER
                                        )
                                        .amount(123L)
                                        .cardPaymentId("card_payment_id")
                                        .currency(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .CardDecline
                                                .Currency
                                                .CAD
                                        )
                                        .declinedTransactionId("declined_transaction_id")
                                        .digitalWalletTokenId("digital_wallet_token_id")
                                        .merchantAcceptorId("merchant_acceptor_id")
                                        .merchantCategoryCode("merchant_category_code")
                                        .merchantCity("merchant_city")
                                        .merchantCountry("merchant_country")
                                        .merchantDescriptor("merchant_descriptor")
                                        .merchantState("merchant_state")
                                        .networkDetails(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .CardDecline
                                                .NetworkDetails
                                                .builder()
                                                .category(
                                                    CardAuthorizationSimulation.DeclinedTransaction
                                                        .Source
                                                        .CardDecline
                                                        .NetworkDetails
                                                        .Category
                                                        .VISA
                                                )
                                                .visa(
                                                    CardAuthorizationSimulation.DeclinedTransaction
                                                        .Source
                                                        .CardDecline
                                                        .NetworkDetails
                                                        .Visa
                                                        .builder()
                                                        .electronicCommerceIndicator(
                                                            CardAuthorizationSimulation
                                                                .DeclinedTransaction
                                                                .Source
                                                                .CardDecline
                                                                .NetworkDetails
                                                                .Visa
                                                                .ElectronicCommerceIndicator
                                                                .MAIL_PHONE_ORDER
                                                        )
                                                        .pointOfServiceEntryMode(
                                                            CardAuthorizationSimulation
                                                                .DeclinedTransaction
                                                                .Source
                                                                .CardDecline
                                                                .NetworkDetails
                                                                .Visa
                                                                .PointOfServiceEntryMode
                                                                .UNKNOWN
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .networkIdentifiers(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .CardDecline
                                                .NetworkIdentifiers
                                                .builder()
                                                .retrievalReferenceNumber(
                                                    "retrieval_reference_number"
                                                )
                                                .traceNumber("trace_number")
                                                .transactionId("transaction_id")
                                                .build()
                                        )
                                        .networkRiskScore(123L)
                                        .physicalCardId("physical_card_id")
                                        .presentmentAmount(123L)
                                        .presentmentCurrency("presentment_currency")
                                        .processingCategory(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .CardDecline
                                                .ProcessingCategory
                                                .ACCOUNT_FUNDING
                                        )
                                        .realTimeDecisionId("real_time_decision_id")
                                        .reason(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .CardDecline
                                                .Reason
                                                .CARD_NOT_ACTIVE
                                        )
                                        .verification(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .CardDecline
                                                .Verification
                                                .builder()
                                                .cardVerificationCode(
                                                    CardAuthorizationSimulation.DeclinedTransaction
                                                        .Source
                                                        .CardDecline
                                                        .Verification
                                                        .CardVerificationCode
                                                        .builder()
                                                        .result(
                                                            CardAuthorizationSimulation
                                                                .DeclinedTransaction
                                                                .Source
                                                                .CardDecline
                                                                .Verification
                                                                .CardVerificationCode
                                                                .Result
                                                                .NOT_CHECKED
                                                        )
                                                        .build()
                                                )
                                                .cardholderAddress(
                                                    CardAuthorizationSimulation.DeclinedTransaction
                                                        .Source
                                                        .CardDecline
                                                        .Verification
                                                        .CardholderAddress
                                                        .builder()
                                                        .actualLine1("actual_line1")
                                                        .actualPostalCode("actual_postal_code")
                                                        .providedLine1("provided_line1")
                                                        .providedPostalCode("provided_postal_code")
                                                        .result(
                                                            CardAuthorizationSimulation
                                                                .DeclinedTransaction
                                                                .Source
                                                                .CardDecline
                                                                .Verification
                                                                .CardholderAddress
                                                                .Result
                                                                .NOT_CHECKED
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .category(
                                    CardAuthorizationSimulation.DeclinedTransaction.Source.Category
                                        .ACH_DECLINE
                                )
                                .checkDecline(
                                    CardAuthorizationSimulation.DeclinedTransaction.Source
                                        .CheckDecline
                                        .builder()
                                        .amount(123L)
                                        .auxiliaryOnUs("auxiliary_on_us")
                                        .backImageFileId("back_image_file_id")
                                        .checkTransferId("check_transfer_id")
                                        .frontImageFileId("front_image_file_id")
                                        .inboundCheckDepositId("inbound_check_deposit_id")
                                        .reason(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .CheckDecline
                                                .Reason
                                                .ACH_ROUTE_DISABLED
                                        )
                                        .build()
                                )
                                .checkDepositRejection(
                                    CardAuthorizationSimulation.DeclinedTransaction.Source
                                        .CheckDepositRejection
                                        .builder()
                                        .amount(123L)
                                        .checkDepositId("check_deposit_id")
                                        .currency(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .CheckDepositRejection
                                                .Currency
                                                .CAD
                                        )
                                        .reason(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .CheckDepositRejection
                                                .Reason
                                                .INCOMPLETE_IMAGE
                                        )
                                        .rejectedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .build()
                                )
                                .inboundRealTimePaymentsTransferDecline(
                                    CardAuthorizationSimulation.DeclinedTransaction.Source
                                        .InboundRealTimePaymentsTransferDecline
                                        .builder()
                                        .amount(123L)
                                        .creditorName("creditor_name")
                                        .currency(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .InboundRealTimePaymentsTransferDecline
                                                .Currency
                                                .CAD
                                        )
                                        .debtorAccountNumber("debtor_account_number")
                                        .debtorName("debtor_name")
                                        .debtorRoutingNumber("debtor_routing_number")
                                        .reason(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .InboundRealTimePaymentsTransferDecline
                                                .Reason
                                                .ACCOUNT_NUMBER_CANCELED
                                        )
                                        .remittanceInformation("remittance_information")
                                        .transactionIdentification("transaction_identification")
                                        .build()
                                )
                                .internationalAchDecline(
                                    CardAuthorizationSimulation.DeclinedTransaction.Source
                                        .InternationalAchDecline
                                        .builder()
                                        .amount(123L)
                                        .destinationCountryCode("destination_country_code")
                                        .destinationCurrencyCode("destination_currency_code")
                                        .foreignExchangeIndicator(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .InternationalAchDecline
                                                .ForeignExchangeIndicator
                                                .FIXED_TO_VARIABLE
                                        )
                                        .foreignExchangeReference("foreign_exchange_reference")
                                        .foreignExchangeReferenceIndicator(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .InternationalAchDecline
                                                .ForeignExchangeReferenceIndicator
                                                .FOREIGN_EXCHANGE_RATE
                                        )
                                        .foreignPaymentAmount(123L)
                                        .foreignTraceNumber("foreign_trace_number")
                                        .internationalTransactionTypeCode(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .InternationalAchDecline
                                                .InternationalTransactionTypeCode
                                                .ANNUITY
                                        )
                                        .originatingCurrencyCode("originating_currency_code")
                                        .originatingDepositoryFinancialInstitutionBranchCountry(
                                            "originating_depository_financial_institution_branch_country"
                                        )
                                        .originatingDepositoryFinancialInstitutionId(
                                            "originating_depository_financial_institution_id"
                                        )
                                        .originatingDepositoryFinancialInstitutionIdQualifier(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .InternationalAchDecline
                                                .OriginatingDepositoryFinancialInstitutionIdQualifier
                                                .NATIONAL_CLEARING_SYSTEM_NUMBER
                                        )
                                        .originatingDepositoryFinancialInstitutionName(
                                            "originating_depository_financial_institution_name"
                                        )
                                        .originatorCity("originator_city")
                                        .originatorCompanyEntryDescription(
                                            "originator_company_entry_description"
                                        )
                                        .originatorCountry("originator_country")
                                        .originatorIdentification("originator_identification")
                                        .originatorName("originator_name")
                                        .originatorPostalCode("originator_postal_code")
                                        .originatorStateOrProvince("originator_state_or_province")
                                        .originatorStreetAddress("originator_street_address")
                                        .paymentRelatedInformation("payment_related_information")
                                        .paymentRelatedInformation2("payment_related_information2")
                                        .receiverCity("receiver_city")
                                        .receiverCountry("receiver_country")
                                        .receiverIdentificationNumber(
                                            "receiver_identification_number"
                                        )
                                        .receiverPostalCode("receiver_postal_code")
                                        .receiverStateOrProvince("receiver_state_or_province")
                                        .receiverStreetAddress("receiver_street_address")
                                        .receivingCompanyOrIndividualName(
                                            "receiving_company_or_individual_name"
                                        )
                                        .receivingDepositoryFinancialInstitutionCountry(
                                            "receiving_depository_financial_institution_country"
                                        )
                                        .receivingDepositoryFinancialInstitutionId(
                                            "receiving_depository_financial_institution_id"
                                        )
                                        .receivingDepositoryFinancialInstitutionIdQualifier(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .InternationalAchDecline
                                                .ReceivingDepositoryFinancialInstitutionIdQualifier
                                                .NATIONAL_CLEARING_SYSTEM_NUMBER
                                        )
                                        .receivingDepositoryFinancialInstitutionName(
                                            "receiving_depository_financial_institution_name"
                                        )
                                        .traceNumber("trace_number")
                                        .build()
                                )
                                .wireDecline(
                                    CardAuthorizationSimulation.DeclinedTransaction.Source
                                        .WireDecline
                                        .builder()
                                        .inboundWireTransferId("inbound_wire_transfer_id")
                                        .reason(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .WireDecline
                                                .Reason
                                                .ACCOUNT_NUMBER_CANCELED
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .type(
                            CardAuthorizationSimulation.DeclinedTransaction.Type
                                .DECLINED_TRANSACTION
                        )
                        .build()
                )
                .pendingTransaction(
                    CardAuthorizationSimulation.PendingTransaction.builder()
                        .id("id")
                        .accountId("account_id")
                        .amount(123L)
                        .completedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .currency(CardAuthorizationSimulation.PendingTransaction.Currency.CAD)
                        .description("description")
                        .routeId("route_id")
                        .routeType(
                            CardAuthorizationSimulation.PendingTransaction.RouteType.ACCOUNT_NUMBER
                        )
                        .source(
                            CardAuthorizationSimulation.PendingTransaction.Source.builder()
                                .accountTransferInstruction(
                                    CardAuthorizationSimulation.PendingTransaction.Source
                                        .AccountTransferInstruction
                                        .builder()
                                        .amount(123L)
                                        .currency(
                                            CardAuthorizationSimulation.PendingTransaction.Source
                                                .AccountTransferInstruction
                                                .Currency
                                                .CAD
                                        )
                                        .transferId("transfer_id")
                                        .build()
                                )
                                .achTransferInstruction(
                                    CardAuthorizationSimulation.PendingTransaction.Source
                                        .AchTransferInstruction
                                        .builder()
                                        .amount(123L)
                                        .transferId("transfer_id")
                                        .build()
                                )
                                .cardAuthorization(
                                    CardAuthorizationSimulation.PendingTransaction.Source
                                        .CardAuthorization
                                        .builder()
                                        .id("id")
                                        .actioner(
                                            CardAuthorizationSimulation.PendingTransaction.Source
                                                .CardAuthorization
                                                .Actioner
                                                .USER
                                        )
                                        .amount(123L)
                                        .cardPaymentId("card_payment_id")
                                        .currency(
                                            CardAuthorizationSimulation.PendingTransaction.Source
                                                .CardAuthorization
                                                .Currency
                                                .CAD
                                        )
                                        .digitalWalletTokenId("digital_wallet_token_id")
                                        .direction(
                                            CardAuthorizationSimulation.PendingTransaction.Source
                                                .CardAuthorization
                                                .Direction
                                                .SETTLEMENT
                                        )
                                        .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .merchantAcceptorId("merchant_acceptor_id")
                                        .merchantCategoryCode("merchant_category_code")
                                        .merchantCity("merchant_city")
                                        .merchantCountry("merchant_country")
                                        .merchantDescriptor("merchant_descriptor")
                                        .networkDetails(
                                            CardAuthorizationSimulation.PendingTransaction.Source
                                                .CardAuthorization
                                                .NetworkDetails
                                                .builder()
                                                .category(
                                                    CardAuthorizationSimulation.PendingTransaction
                                                        .Source
                                                        .CardAuthorization
                                                        .NetworkDetails
                                                        .Category
                                                        .VISA
                                                )
                                                .visa(
                                                    CardAuthorizationSimulation.PendingTransaction
                                                        .Source
                                                        .CardAuthorization
                                                        .NetworkDetails
                                                        .Visa
                                                        .builder()
                                                        .electronicCommerceIndicator(
                                                            CardAuthorizationSimulation
                                                                .PendingTransaction
                                                                .Source
                                                                .CardAuthorization
                                                                .NetworkDetails
                                                                .Visa
                                                                .ElectronicCommerceIndicator
                                                                .MAIL_PHONE_ORDER
                                                        )
                                                        .pointOfServiceEntryMode(
                                                            CardAuthorizationSimulation
                                                                .PendingTransaction
                                                                .Source
                                                                .CardAuthorization
                                                                .NetworkDetails
                                                                .Visa
                                                                .PointOfServiceEntryMode
                                                                .UNKNOWN
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .networkIdentifiers(
                                            CardAuthorizationSimulation.PendingTransaction.Source
                                                .CardAuthorization
                                                .NetworkIdentifiers
                                                .builder()
                                                .retrievalReferenceNumber(
                                                    "retrieval_reference_number"
                                                )
                                                .traceNumber("trace_number")
                                                .transactionId("transaction_id")
                                                .build()
                                        )
                                        .networkRiskScore(123L)
                                        .pendingTransactionId("pending_transaction_id")
                                        .physicalCardId("physical_card_id")
                                        .presentmentAmount(123L)
                                        .presentmentCurrency("presentment_currency")
                                        .processingCategory(
                                            CardAuthorizationSimulation.PendingTransaction.Source
                                                .CardAuthorization
                                                .ProcessingCategory
                                                .ACCOUNT_FUNDING
                                        )
                                        .realTimeDecisionId("real_time_decision_id")
                                        .type(
                                            CardAuthorizationSimulation.PendingTransaction.Source
                                                .CardAuthorization
                                                .Type
                                                .CARD_AUTHORIZATION
                                        )
                                        .verification(
                                            CardAuthorizationSimulation.PendingTransaction.Source
                                                .CardAuthorization
                                                .Verification
                                                .builder()
                                                .cardVerificationCode(
                                                    CardAuthorizationSimulation.PendingTransaction
                                                        .Source
                                                        .CardAuthorization
                                                        .Verification
                                                        .CardVerificationCode
                                                        .builder()
                                                        .result(
                                                            CardAuthorizationSimulation
                                                                .PendingTransaction
                                                                .Source
                                                                .CardAuthorization
                                                                .Verification
                                                                .CardVerificationCode
                                                                .Result
                                                                .NOT_CHECKED
                                                        )
                                                        .build()
                                                )
                                                .cardholderAddress(
                                                    CardAuthorizationSimulation.PendingTransaction
                                                        .Source
                                                        .CardAuthorization
                                                        .Verification
                                                        .CardholderAddress
                                                        .builder()
                                                        .actualLine1("actual_line1")
                                                        .actualPostalCode("actual_postal_code")
                                                        .providedLine1("provided_line1")
                                                        .providedPostalCode("provided_postal_code")
                                                        .result(
                                                            CardAuthorizationSimulation
                                                                .PendingTransaction
                                                                .Source
                                                                .CardAuthorization
                                                                .Verification
                                                                .CardholderAddress
                                                                .Result
                                                                .NOT_CHECKED
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .category(
                                    CardAuthorizationSimulation.PendingTransaction.Source.Category
                                        .ACCOUNT_TRANSFER_INSTRUCTION
                                )
                                .checkDepositInstruction(
                                    CardAuthorizationSimulation.PendingTransaction.Source
                                        .CheckDepositInstruction
                                        .builder()
                                        .amount(123L)
                                        .backImageFileId("back_image_file_id")
                                        .checkDepositId("check_deposit_id")
                                        .currency(
                                            CardAuthorizationSimulation.PendingTransaction.Source
                                                .CheckDepositInstruction
                                                .Currency
                                                .CAD
                                        )
                                        .frontImageFileId("front_image_file_id")
                                        .build()
                                )
                                .checkTransferInstruction(
                                    CardAuthorizationSimulation.PendingTransaction.Source
                                        .CheckTransferInstruction
                                        .builder()
                                        .amount(123L)
                                        .currency(
                                            CardAuthorizationSimulation.PendingTransaction.Source
                                                .CheckTransferInstruction
                                                .Currency
                                                .CAD
                                        )
                                        .transferId("transfer_id")
                                        .build()
                                )
                                .inboundFundsHold(
                                    CardAuthorizationSimulation.PendingTransaction.Source
                                        .InboundFundsHold
                                        .builder()
                                        .id("id")
                                        .amount(123L)
                                        .automaticallyReleasesAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .currency(
                                            CardAuthorizationSimulation.PendingTransaction.Source
                                                .InboundFundsHold
                                                .Currency
                                                .CAD
                                        )
                                        .heldTransactionId("held_transaction_id")
                                        .pendingTransactionId("pending_transaction_id")
                                        .releasedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .status(
                                            CardAuthorizationSimulation.PendingTransaction.Source
                                                .InboundFundsHold
                                                .Status
                                                .HELD
                                        )
                                        .type(
                                            CardAuthorizationSimulation.PendingTransaction.Source
                                                .InboundFundsHold
                                                .Type
                                                .INBOUND_FUNDS_HOLD
                                        )
                                        .build()
                                )
                                .realTimePaymentsTransferInstruction(
                                    CardAuthorizationSimulation.PendingTransaction.Source
                                        .RealTimePaymentsTransferInstruction
                                        .builder()
                                        .amount(123L)
                                        .transferId("transfer_id")
                                        .build()
                                )
                                .wireTransferInstruction(
                                    CardAuthorizationSimulation.PendingTransaction.Source
                                        .WireTransferInstruction
                                        .builder()
                                        .accountNumber("account_number")
                                        .amount(123L)
                                        .messageToRecipient("message_to_recipient")
                                        .routingNumber("routing_number")
                                        .transferId("transfer_id")
                                        .build()
                                )
                                .build()
                        )
                        .status(CardAuthorizationSimulation.PendingTransaction.Status.PENDING)
                        .type(
                            CardAuthorizationSimulation.PendingTransaction.Type.PENDING_TRANSACTION
                        )
                        .build()
                )
                .type(CardAuthorizationSimulation.Type.INBOUND_CARD_AUTHORIZATION_SIMULATION_RESULT)
                .build()
        assertThat(cardAuthorizationSimulation).isNotNull
        assertThat(cardAuthorizationSimulation.declinedTransaction())
            .isEqualTo(
                CardAuthorizationSimulation.DeclinedTransaction.builder()
                    .id("id")
                    .accountId("account_id")
                    .amount(123L)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .currency(CardAuthorizationSimulation.DeclinedTransaction.Currency.CAD)
                    .description("description")
                    .routeId("route_id")
                    .routeType(
                        CardAuthorizationSimulation.DeclinedTransaction.RouteType.ACCOUNT_NUMBER
                    )
                    .source(
                        CardAuthorizationSimulation.DeclinedTransaction.Source.builder()
                            .achDecline(
                                CardAuthorizationSimulation.DeclinedTransaction.Source.AchDecline
                                    .builder()
                                    .id("id")
                                    .amount(123L)
                                    .inboundAchTransferId("inbound_ach_transfer_id")
                                    .originatorCompanyDescriptiveDate(
                                        "originator_company_descriptive_date"
                                    )
                                    .originatorCompanyDiscretionaryData(
                                        "originator_company_discretionary_data"
                                    )
                                    .originatorCompanyId("originator_company_id")
                                    .originatorCompanyName("originator_company_name")
                                    .reason(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .AchDecline
                                            .Reason
                                            .ACH_ROUTE_CANCELED
                                    )
                                    .receiverIdNumber("receiver_id_number")
                                    .receiverName("receiver_name")
                                    .traceNumber("trace_number")
                                    .type(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .AchDecline
                                            .Type
                                            .ACH_DECLINE
                                    )
                                    .build()
                            )
                            .cardDecline(
                                CardAuthorizationSimulation.DeclinedTransaction.Source.CardDecline
                                    .builder()
                                    .id("id")
                                    .actioner(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .CardDecline
                                            .Actioner
                                            .USER
                                    )
                                    .amount(123L)
                                    .cardPaymentId("card_payment_id")
                                    .currency(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .CardDecline
                                            .Currency
                                            .CAD
                                    )
                                    .declinedTransactionId("declined_transaction_id")
                                    .digitalWalletTokenId("digital_wallet_token_id")
                                    .merchantAcceptorId("merchant_acceptor_id")
                                    .merchantCategoryCode("merchant_category_code")
                                    .merchantCity("merchant_city")
                                    .merchantCountry("merchant_country")
                                    .merchantDescriptor("merchant_descriptor")
                                    .merchantState("merchant_state")
                                    .networkDetails(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .CardDecline
                                            .NetworkDetails
                                            .builder()
                                            .category(
                                                CardAuthorizationSimulation.DeclinedTransaction
                                                    .Source
                                                    .CardDecline
                                                    .NetworkDetails
                                                    .Category
                                                    .VISA
                                            )
                                            .visa(
                                                CardAuthorizationSimulation.DeclinedTransaction
                                                    .Source
                                                    .CardDecline
                                                    .NetworkDetails
                                                    .Visa
                                                    .builder()
                                                    .electronicCommerceIndicator(
                                                        CardAuthorizationSimulation
                                                            .DeclinedTransaction
                                                            .Source
                                                            .CardDecline
                                                            .NetworkDetails
                                                            .Visa
                                                            .ElectronicCommerceIndicator
                                                            .MAIL_PHONE_ORDER
                                                    )
                                                    .pointOfServiceEntryMode(
                                                        CardAuthorizationSimulation
                                                            .DeclinedTransaction
                                                            .Source
                                                            .CardDecline
                                                            .NetworkDetails
                                                            .Visa
                                                            .PointOfServiceEntryMode
                                                            .UNKNOWN
                                                    )
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .networkIdentifiers(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .CardDecline
                                            .NetworkIdentifiers
                                            .builder()
                                            .retrievalReferenceNumber("retrieval_reference_number")
                                            .traceNumber("trace_number")
                                            .transactionId("transaction_id")
                                            .build()
                                    )
                                    .networkRiskScore(123L)
                                    .physicalCardId("physical_card_id")
                                    .presentmentAmount(123L)
                                    .presentmentCurrency("presentment_currency")
                                    .processingCategory(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .CardDecline
                                            .ProcessingCategory
                                            .ACCOUNT_FUNDING
                                    )
                                    .realTimeDecisionId("real_time_decision_id")
                                    .reason(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .CardDecline
                                            .Reason
                                            .CARD_NOT_ACTIVE
                                    )
                                    .verification(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .CardDecline
                                            .Verification
                                            .builder()
                                            .cardVerificationCode(
                                                CardAuthorizationSimulation.DeclinedTransaction
                                                    .Source
                                                    .CardDecline
                                                    .Verification
                                                    .CardVerificationCode
                                                    .builder()
                                                    .result(
                                                        CardAuthorizationSimulation
                                                            .DeclinedTransaction
                                                            .Source
                                                            .CardDecline
                                                            .Verification
                                                            .CardVerificationCode
                                                            .Result
                                                            .NOT_CHECKED
                                                    )
                                                    .build()
                                            )
                                            .cardholderAddress(
                                                CardAuthorizationSimulation.DeclinedTransaction
                                                    .Source
                                                    .CardDecline
                                                    .Verification
                                                    .CardholderAddress
                                                    .builder()
                                                    .actualLine1("actual_line1")
                                                    .actualPostalCode("actual_postal_code")
                                                    .providedLine1("provided_line1")
                                                    .providedPostalCode("provided_postal_code")
                                                    .result(
                                                        CardAuthorizationSimulation
                                                            .DeclinedTransaction
                                                            .Source
                                                            .CardDecline
                                                            .Verification
                                                            .CardholderAddress
                                                            .Result
                                                            .NOT_CHECKED
                                                    )
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .category(
                                CardAuthorizationSimulation.DeclinedTransaction.Source.Category
                                    .ACH_DECLINE
                            )
                            .checkDecline(
                                CardAuthorizationSimulation.DeclinedTransaction.Source.CheckDecline
                                    .builder()
                                    .amount(123L)
                                    .auxiliaryOnUs("auxiliary_on_us")
                                    .backImageFileId("back_image_file_id")
                                    .checkTransferId("check_transfer_id")
                                    .frontImageFileId("front_image_file_id")
                                    .inboundCheckDepositId("inbound_check_deposit_id")
                                    .reason(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .CheckDecline
                                            .Reason
                                            .ACH_ROUTE_DISABLED
                                    )
                                    .build()
                            )
                            .checkDepositRejection(
                                CardAuthorizationSimulation.DeclinedTransaction.Source
                                    .CheckDepositRejection
                                    .builder()
                                    .amount(123L)
                                    .checkDepositId("check_deposit_id")
                                    .currency(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .CheckDepositRejection
                                            .Currency
                                            .CAD
                                    )
                                    .reason(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .CheckDepositRejection
                                            .Reason
                                            .INCOMPLETE_IMAGE
                                    )
                                    .rejectedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .inboundRealTimePaymentsTransferDecline(
                                CardAuthorizationSimulation.DeclinedTransaction.Source
                                    .InboundRealTimePaymentsTransferDecline
                                    .builder()
                                    .amount(123L)
                                    .creditorName("creditor_name")
                                    .currency(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .InboundRealTimePaymentsTransferDecline
                                            .Currency
                                            .CAD
                                    )
                                    .debtorAccountNumber("debtor_account_number")
                                    .debtorName("debtor_name")
                                    .debtorRoutingNumber("debtor_routing_number")
                                    .reason(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .InboundRealTimePaymentsTransferDecline
                                            .Reason
                                            .ACCOUNT_NUMBER_CANCELED
                                    )
                                    .remittanceInformation("remittance_information")
                                    .transactionIdentification("transaction_identification")
                                    .build()
                            )
                            .internationalAchDecline(
                                CardAuthorizationSimulation.DeclinedTransaction.Source
                                    .InternationalAchDecline
                                    .builder()
                                    .amount(123L)
                                    .destinationCountryCode("destination_country_code")
                                    .destinationCurrencyCode("destination_currency_code")
                                    .foreignExchangeIndicator(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .InternationalAchDecline
                                            .ForeignExchangeIndicator
                                            .FIXED_TO_VARIABLE
                                    )
                                    .foreignExchangeReference("foreign_exchange_reference")
                                    .foreignExchangeReferenceIndicator(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .InternationalAchDecline
                                            .ForeignExchangeReferenceIndicator
                                            .FOREIGN_EXCHANGE_RATE
                                    )
                                    .foreignPaymentAmount(123L)
                                    .foreignTraceNumber("foreign_trace_number")
                                    .internationalTransactionTypeCode(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .InternationalAchDecline
                                            .InternationalTransactionTypeCode
                                            .ANNUITY
                                    )
                                    .originatingCurrencyCode("originating_currency_code")
                                    .originatingDepositoryFinancialInstitutionBranchCountry(
                                        "originating_depository_financial_institution_branch_country"
                                    )
                                    .originatingDepositoryFinancialInstitutionId(
                                        "originating_depository_financial_institution_id"
                                    )
                                    .originatingDepositoryFinancialInstitutionIdQualifier(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .InternationalAchDecline
                                            .OriginatingDepositoryFinancialInstitutionIdQualifier
                                            .NATIONAL_CLEARING_SYSTEM_NUMBER
                                    )
                                    .originatingDepositoryFinancialInstitutionName(
                                        "originating_depository_financial_institution_name"
                                    )
                                    .originatorCity("originator_city")
                                    .originatorCompanyEntryDescription(
                                        "originator_company_entry_description"
                                    )
                                    .originatorCountry("originator_country")
                                    .originatorIdentification("originator_identification")
                                    .originatorName("originator_name")
                                    .originatorPostalCode("originator_postal_code")
                                    .originatorStateOrProvince("originator_state_or_province")
                                    .originatorStreetAddress("originator_street_address")
                                    .paymentRelatedInformation("payment_related_information")
                                    .paymentRelatedInformation2("payment_related_information2")
                                    .receiverCity("receiver_city")
                                    .receiverCountry("receiver_country")
                                    .receiverIdentificationNumber("receiver_identification_number")
                                    .receiverPostalCode("receiver_postal_code")
                                    .receiverStateOrProvince("receiver_state_or_province")
                                    .receiverStreetAddress("receiver_street_address")
                                    .receivingCompanyOrIndividualName(
                                        "receiving_company_or_individual_name"
                                    )
                                    .receivingDepositoryFinancialInstitutionCountry(
                                        "receiving_depository_financial_institution_country"
                                    )
                                    .receivingDepositoryFinancialInstitutionId(
                                        "receiving_depository_financial_institution_id"
                                    )
                                    .receivingDepositoryFinancialInstitutionIdQualifier(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .InternationalAchDecline
                                            .ReceivingDepositoryFinancialInstitutionIdQualifier
                                            .NATIONAL_CLEARING_SYSTEM_NUMBER
                                    )
                                    .receivingDepositoryFinancialInstitutionName(
                                        "receiving_depository_financial_institution_name"
                                    )
                                    .traceNumber("trace_number")
                                    .build()
                            )
                            .wireDecline(
                                CardAuthorizationSimulation.DeclinedTransaction.Source.WireDecline
                                    .builder()
                                    .inboundWireTransferId("inbound_wire_transfer_id")
                                    .reason(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .WireDecline
                                            .Reason
                                            .ACCOUNT_NUMBER_CANCELED
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .type(CardAuthorizationSimulation.DeclinedTransaction.Type.DECLINED_TRANSACTION)
                    .build()
            )
        assertThat(cardAuthorizationSimulation.pendingTransaction())
            .isEqualTo(
                CardAuthorizationSimulation.PendingTransaction.builder()
                    .id("id")
                    .accountId("account_id")
                    .amount(123L)
                    .completedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .currency(CardAuthorizationSimulation.PendingTransaction.Currency.CAD)
                    .description("description")
                    .routeId("route_id")
                    .routeType(
                        CardAuthorizationSimulation.PendingTransaction.RouteType.ACCOUNT_NUMBER
                    )
                    .source(
                        CardAuthorizationSimulation.PendingTransaction.Source.builder()
                            .accountTransferInstruction(
                                CardAuthorizationSimulation.PendingTransaction.Source
                                    .AccountTransferInstruction
                                    .builder()
                                    .amount(123L)
                                    .currency(
                                        CardAuthorizationSimulation.PendingTransaction.Source
                                            .AccountTransferInstruction
                                            .Currency
                                            .CAD
                                    )
                                    .transferId("transfer_id")
                                    .build()
                            )
                            .achTransferInstruction(
                                CardAuthorizationSimulation.PendingTransaction.Source
                                    .AchTransferInstruction
                                    .builder()
                                    .amount(123L)
                                    .transferId("transfer_id")
                                    .build()
                            )
                            .cardAuthorization(
                                CardAuthorizationSimulation.PendingTransaction.Source
                                    .CardAuthorization
                                    .builder()
                                    .id("id")
                                    .actioner(
                                        CardAuthorizationSimulation.PendingTransaction.Source
                                            .CardAuthorization
                                            .Actioner
                                            .USER
                                    )
                                    .amount(123L)
                                    .cardPaymentId("card_payment_id")
                                    .currency(
                                        CardAuthorizationSimulation.PendingTransaction.Source
                                            .CardAuthorization
                                            .Currency
                                            .CAD
                                    )
                                    .digitalWalletTokenId("digital_wallet_token_id")
                                    .direction(
                                        CardAuthorizationSimulation.PendingTransaction.Source
                                            .CardAuthorization
                                            .Direction
                                            .SETTLEMENT
                                    )
                                    .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .merchantAcceptorId("merchant_acceptor_id")
                                    .merchantCategoryCode("merchant_category_code")
                                    .merchantCity("merchant_city")
                                    .merchantCountry("merchant_country")
                                    .merchantDescriptor("merchant_descriptor")
                                    .networkDetails(
                                        CardAuthorizationSimulation.PendingTransaction.Source
                                            .CardAuthorization
                                            .NetworkDetails
                                            .builder()
                                            .category(
                                                CardAuthorizationSimulation.PendingTransaction
                                                    .Source
                                                    .CardAuthorization
                                                    .NetworkDetails
                                                    .Category
                                                    .VISA
                                            )
                                            .visa(
                                                CardAuthorizationSimulation.PendingTransaction
                                                    .Source
                                                    .CardAuthorization
                                                    .NetworkDetails
                                                    .Visa
                                                    .builder()
                                                    .electronicCommerceIndicator(
                                                        CardAuthorizationSimulation
                                                            .PendingTransaction
                                                            .Source
                                                            .CardAuthorization
                                                            .NetworkDetails
                                                            .Visa
                                                            .ElectronicCommerceIndicator
                                                            .MAIL_PHONE_ORDER
                                                    )
                                                    .pointOfServiceEntryMode(
                                                        CardAuthorizationSimulation
                                                            .PendingTransaction
                                                            .Source
                                                            .CardAuthorization
                                                            .NetworkDetails
                                                            .Visa
                                                            .PointOfServiceEntryMode
                                                            .UNKNOWN
                                                    )
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .networkIdentifiers(
                                        CardAuthorizationSimulation.PendingTransaction.Source
                                            .CardAuthorization
                                            .NetworkIdentifiers
                                            .builder()
                                            .retrievalReferenceNumber("retrieval_reference_number")
                                            .traceNumber("trace_number")
                                            .transactionId("transaction_id")
                                            .build()
                                    )
                                    .networkRiskScore(123L)
                                    .pendingTransactionId("pending_transaction_id")
                                    .physicalCardId("physical_card_id")
                                    .presentmentAmount(123L)
                                    .presentmentCurrency("presentment_currency")
                                    .processingCategory(
                                        CardAuthorizationSimulation.PendingTransaction.Source
                                            .CardAuthorization
                                            .ProcessingCategory
                                            .ACCOUNT_FUNDING
                                    )
                                    .realTimeDecisionId("real_time_decision_id")
                                    .type(
                                        CardAuthorizationSimulation.PendingTransaction.Source
                                            .CardAuthorization
                                            .Type
                                            .CARD_AUTHORIZATION
                                    )
                                    .verification(
                                        CardAuthorizationSimulation.PendingTransaction.Source
                                            .CardAuthorization
                                            .Verification
                                            .builder()
                                            .cardVerificationCode(
                                                CardAuthorizationSimulation.PendingTransaction
                                                    .Source
                                                    .CardAuthorization
                                                    .Verification
                                                    .CardVerificationCode
                                                    .builder()
                                                    .result(
                                                        CardAuthorizationSimulation
                                                            .PendingTransaction
                                                            .Source
                                                            .CardAuthorization
                                                            .Verification
                                                            .CardVerificationCode
                                                            .Result
                                                            .NOT_CHECKED
                                                    )
                                                    .build()
                                            )
                                            .cardholderAddress(
                                                CardAuthorizationSimulation.PendingTransaction
                                                    .Source
                                                    .CardAuthorization
                                                    .Verification
                                                    .CardholderAddress
                                                    .builder()
                                                    .actualLine1("actual_line1")
                                                    .actualPostalCode("actual_postal_code")
                                                    .providedLine1("provided_line1")
                                                    .providedPostalCode("provided_postal_code")
                                                    .result(
                                                        CardAuthorizationSimulation
                                                            .PendingTransaction
                                                            .Source
                                                            .CardAuthorization
                                                            .Verification
                                                            .CardholderAddress
                                                            .Result
                                                            .NOT_CHECKED
                                                    )
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .category(
                                CardAuthorizationSimulation.PendingTransaction.Source.Category
                                    .ACCOUNT_TRANSFER_INSTRUCTION
                            )
                            .checkDepositInstruction(
                                CardAuthorizationSimulation.PendingTransaction.Source
                                    .CheckDepositInstruction
                                    .builder()
                                    .amount(123L)
                                    .backImageFileId("back_image_file_id")
                                    .checkDepositId("check_deposit_id")
                                    .currency(
                                        CardAuthorizationSimulation.PendingTransaction.Source
                                            .CheckDepositInstruction
                                            .Currency
                                            .CAD
                                    )
                                    .frontImageFileId("front_image_file_id")
                                    .build()
                            )
                            .checkTransferInstruction(
                                CardAuthorizationSimulation.PendingTransaction.Source
                                    .CheckTransferInstruction
                                    .builder()
                                    .amount(123L)
                                    .currency(
                                        CardAuthorizationSimulation.PendingTransaction.Source
                                            .CheckTransferInstruction
                                            .Currency
                                            .CAD
                                    )
                                    .transferId("transfer_id")
                                    .build()
                            )
                            .inboundFundsHold(
                                CardAuthorizationSimulation.PendingTransaction.Source
                                    .InboundFundsHold
                                    .builder()
                                    .id("id")
                                    .amount(123L)
                                    .automaticallyReleasesAt(
                                        OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                    )
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .currency(
                                        CardAuthorizationSimulation.PendingTransaction.Source
                                            .InboundFundsHold
                                            .Currency
                                            .CAD
                                    )
                                    .heldTransactionId("held_transaction_id")
                                    .pendingTransactionId("pending_transaction_id")
                                    .releasedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .status(
                                        CardAuthorizationSimulation.PendingTransaction.Source
                                            .InboundFundsHold
                                            .Status
                                            .HELD
                                    )
                                    .type(
                                        CardAuthorizationSimulation.PendingTransaction.Source
                                            .InboundFundsHold
                                            .Type
                                            .INBOUND_FUNDS_HOLD
                                    )
                                    .build()
                            )
                            .realTimePaymentsTransferInstruction(
                                CardAuthorizationSimulation.PendingTransaction.Source
                                    .RealTimePaymentsTransferInstruction
                                    .builder()
                                    .amount(123L)
                                    .transferId("transfer_id")
                                    .build()
                            )
                            .wireTransferInstruction(
                                CardAuthorizationSimulation.PendingTransaction.Source
                                    .WireTransferInstruction
                                    .builder()
                                    .accountNumber("account_number")
                                    .amount(123L)
                                    .messageToRecipient("message_to_recipient")
                                    .routingNumber("routing_number")
                                    .transferId("transfer_id")
                                    .build()
                            )
                            .build()
                    )
                    .status(CardAuthorizationSimulation.PendingTransaction.Status.PENDING)
                    .type(CardAuthorizationSimulation.PendingTransaction.Type.PENDING_TRANSACTION)
                    .build()
            )
        assertThat(cardAuthorizationSimulation.type())
            .isEqualTo(
                CardAuthorizationSimulation.Type.INBOUND_CARD_AUTHORIZATION_SIMULATION_RESULT
            )
    }
}
