package com.increase.api.models

import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class CardAuthorizationSimulationTest {

    @Test
    fun createCardAuthorizationSimulation() {
        val cardAuthorizationSimulation =
            CardAuthorizationSimulation.builder()
                .declinedTransaction(
                    CardAuthorizationSimulation.DeclinedTransaction.builder()
                        .id("string")
                        .accountId("string")
                        .amount(123L)
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .currency(CardAuthorizationSimulation.DeclinedTransaction.Currency.CAD)
                        .description("string")
                        .routeId("string")
                        .routeType(
                            CardAuthorizationSimulation.DeclinedTransaction.RouteType.ACCOUNT_NUMBER
                        )
                        .source(
                            CardAuthorizationSimulation.DeclinedTransaction.Source.builder()
                                .achDecline(
                                    CardAuthorizationSimulation.DeclinedTransaction.Source
                                        .AchDecline
                                        .builder()
                                        .amount(123L)
                                        .originatorCompanyDescriptiveDate("string")
                                        .originatorCompanyDiscretionaryData("string")
                                        .originatorCompanyId("string")
                                        .originatorCompanyName("string")
                                        .reason(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .AchDecline
                                                .Reason
                                                .ACH_ROUTE_CANCELED
                                        )
                                        .receiverIdNumber("string")
                                        .receiverName("string")
                                        .traceNumber("string")
                                        .build()
                                )
                                .cardDecline(
                                    CardAuthorizationSimulation.DeclinedTransaction.Source
                                        .CardDecline
                                        .builder()
                                        .amount(123L)
                                        .currency(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .CardDecline
                                                .Currency
                                                .CAD
                                        )
                                        .digitalWalletTokenId("string")
                                        .merchantAcceptorId("string")
                                        .merchantCategoryCode("string")
                                        .merchantCity("string")
                                        .merchantCountry("string")
                                        .merchantDescriptor("string")
                                        .merchantState("string")
                                        .network(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .CardDecline
                                                .Network
                                                .VISA
                                        )
                                        .networkDetails(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .CardDecline
                                                .NetworkDetails
                                                .builder()
                                                .visa(
                                                    CardAuthorizationSimulation.DeclinedTransaction
                                                        .Source
                                                        .CardDecline
                                                        .NetworkDetails
                                                        .Visa
                                                        .builder()
                                                        .electronicCommerceIndicator(
                                                            CardAuthorizationSimulation
                                                                .DeclinedTransaction
                                                                .Source
                                                                .CardDecline
                                                                .NetworkDetails
                                                                .Visa
                                                                .ElectronicCommerceIndicator
                                                                .MAIL_PHONE_ORDER
                                                        )
                                                        .pointOfServiceEntryMode(
                                                            PointOfServiceEntryMode.MANUAL
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .physicalCardId("string")
                                        .realTimeDecisionId("string")
                                        .reason(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .CardDecline
                                                .Reason
                                                .CARD_NOT_ACTIVE
                                        )
                                        .build()
                                )
                                .category(
                                    CardAuthorizationSimulation.DeclinedTransaction.Source.Category
                                        .ACH_DECLINE
                                )
                                .checkDecline(
                                    CardAuthorizationSimulation.DeclinedTransaction.Source
                                        .CheckDecline
                                        .builder()
                                        .amount(123L)
                                        .auxiliaryOnUs("string")
                                        .reason(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .CheckDecline
                                                .Reason
                                                .ACH_ROUTE_CANCELED
                                        )
                                        .build()
                                )
                                .inboundRealTimePaymentsTransferDecline(
                                    CardAuthorizationSimulation.DeclinedTransaction.Source
                                        .InboundRealTimePaymentsTransferDecline
                                        .builder()
                                        .amount(123L)
                                        .creditorName("string")
                                        .currency(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .InboundRealTimePaymentsTransferDecline
                                                .Currency
                                                .CAD
                                        )
                                        .debtorAccountNumber("string")
                                        .debtorName("string")
                                        .debtorRoutingNumber("string")
                                        .reason(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .InboundRealTimePaymentsTransferDecline
                                                .Reason
                                                .ACCOUNT_NUMBER_CANCELED
                                        )
                                        .remittanceInformation("string")
                                        .transactionIdentification("string")
                                        .build()
                                )
                                .internationalAchDecline(
                                    CardAuthorizationSimulation.DeclinedTransaction.Source
                                        .InternationalAchDecline
                                        .builder()
                                        .amount(123L)
                                        .destinationCountryCode("string")
                                        .destinationCurrencyCode("string")
                                        .foreignExchangeIndicator("string")
                                        .foreignExchangeReference("string")
                                        .foreignExchangeReferenceIndicator("string")
                                        .foreignPaymentAmount(123L)
                                        .foreignTraceNumber("string")
                                        .internationalTransactionTypeCode("string")
                                        .originatingCurrencyCode("string")
                                        .originatingDepositoryFinancialInstitutionBranchCountry(
                                            "string"
                                        )
                                        .originatingDepositoryFinancialInstitutionId("string")
                                        .originatingDepositoryFinancialInstitutionIdQualifier(
                                            "string"
                                        )
                                        .originatingDepositoryFinancialInstitutionName("string")
                                        .originatorCity("string")
                                        .originatorCompanyEntryDescription("string")
                                        .originatorCountry("string")
                                        .originatorIdentification("string")
                                        .originatorName("string")
                                        .originatorPostalCode("string")
                                        .originatorStateOrProvince("string")
                                        .originatorStreetAddress("string")
                                        .paymentRelatedInformation("string")
                                        .paymentRelatedInformation2("string")
                                        .receiverCity("string")
                                        .receiverCountry("string")
                                        .receiverIdentificationNumber("string")
                                        .receiverPostalCode("string")
                                        .receiverStateOrProvince("string")
                                        .receiverStreetAddress("string")
                                        .receivingCompanyOrIndividualName("string")
                                        .receivingDepositoryFinancialInstitutionCountry("string")
                                        .receivingDepositoryFinancialInstitutionId("string")
                                        .receivingDepositoryFinancialInstitutionIdQualifier(
                                            "string"
                                        )
                                        .receivingDepositoryFinancialInstitutionName("string")
                                        .traceNumber("string")
                                        .build()
                                )
                                .wireDecline(
                                    CardAuthorizationSimulation.DeclinedTransaction.Source
                                        .WireDecline
                                        .builder()
                                        .amount(123L)
                                        .beneficiaryAddressLine1("string")
                                        .beneficiaryAddressLine2("string")
                                        .beneficiaryAddressLine3("string")
                                        .beneficiaryName("string")
                                        .beneficiaryReference("string")
                                        .description("string")
                                        .inputMessageAccountabilityData("string")
                                        .originatorAddressLine1("string")
                                        .originatorAddressLine2("string")
                                        .originatorAddressLine3("string")
                                        .originatorName("string")
                                        .originatorToBeneficiaryInformationLine1("string")
                                        .originatorToBeneficiaryInformationLine2("string")
                                        .originatorToBeneficiaryInformationLine3("string")
                                        .originatorToBeneficiaryInformationLine4("string")
                                        .reason(
                                            CardAuthorizationSimulation.DeclinedTransaction.Source
                                                .WireDecline
                                                .Reason
                                                .ACCOUNT_NUMBER_CANCELED
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .type(
                            CardAuthorizationSimulation.DeclinedTransaction.Type
                                .DECLINED_TRANSACTION
                        )
                        .build()
                )
                .pendingTransaction(
                    CardAuthorizationSimulation.PendingTransaction.builder()
                        .id("string")
                        .accountId("string")
                        .amount(123L)
                        .completedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .currency(CardAuthorizationSimulation.PendingTransaction.Currency.CAD)
                        .description("string")
                        .routeId("string")
                        .routeType(
                            CardAuthorizationSimulation.PendingTransaction.RouteType.ACCOUNT_NUMBER
                        )
                        .source(
                            CardAuthorizationSimulation.PendingTransaction.Source.builder()
                                .accountTransferInstruction(
                                    CardAuthorizationSimulation.PendingTransaction.Source
                                        .AccountTransferInstruction
                                        .builder()
                                        .amount(123L)
                                        .currency(
                                            CardAuthorizationSimulation.PendingTransaction.Source
                                                .AccountTransferInstruction
                                                .Currency
                                                .CAD
                                        )
                                        .transferId("string")
                                        .build()
                                )
                                .achTransferInstruction(
                                    CardAuthorizationSimulation.PendingTransaction.Source
                                        .AchTransferInstruction
                                        .builder()
                                        .amount(123L)
                                        .transferId("string")
                                        .build()
                                )
                                .cardAuthorization(
                                    CardAuthorizationSimulation.PendingTransaction.Source
                                        .CardAuthorization
                                        .builder()
                                        .id("string")
                                        .amount(123L)
                                        .currency(
                                            CardAuthorizationSimulation.PendingTransaction.Source
                                                .CardAuthorization
                                                .Currency
                                                .CAD
                                        )
                                        .digitalWalletTokenId("string")
                                        .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .merchantAcceptorId("string")
                                        .merchantCategoryCode("string")
                                        .merchantCity("string")
                                        .merchantCountry("string")
                                        .merchantDescriptor("string")
                                        .network(
                                            CardAuthorizationSimulation.PendingTransaction.Source
                                                .CardAuthorization
                                                .Network
                                                .VISA
                                        )
                                        .networkDetails(
                                            CardAuthorizationSimulation.PendingTransaction.Source
                                                .CardAuthorization
                                                .NetworkDetails
                                                .builder()
                                                .visa(
                                                    CardAuthorizationSimulation.PendingTransaction
                                                        .Source
                                                        .CardAuthorization
                                                        .NetworkDetails
                                                        .Visa
                                                        .builder()
                                                        .electronicCommerceIndicator(
                                                            CardAuthorizationSimulation
                                                                .PendingTransaction
                                                                .Source
                                                                .CardAuthorization
                                                                .NetworkDetails
                                                                .Visa
                                                                .ElectronicCommerceIndicator
                                                                .MAIL_PHONE_ORDER
                                                        )
                                                        .pointOfServiceEntryMode(
                                                            PointOfServiceEntryMode.MANUAL
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .pendingTransactionId("string")
                                        .physicalCardId("string")
                                        .realTimeDecisionId("string")
                                        .type(
                                            CardAuthorizationSimulation.PendingTransaction.Source
                                                .CardAuthorization
                                                .Type
                                                .CARD_AUTHORIZATION
                                        )
                                        .build()
                                )
                                .category(
                                    CardAuthorizationSimulation.PendingTransaction.Source.Category
                                        .ACCOUNT_TRANSFER_INSTRUCTION
                                )
                                .checkDepositInstruction(
                                    CardAuthorizationSimulation.PendingTransaction.Source
                                        .CheckDepositInstruction
                                        .builder()
                                        .amount(123L)
                                        .backImageFileId("string")
                                        .checkDepositId("string")
                                        .currency(
                                            CardAuthorizationSimulation.PendingTransaction.Source
                                                .CheckDepositInstruction
                                                .Currency
                                                .CAD
                                        )
                                        .frontImageFileId("string")
                                        .build()
                                )
                                .checkTransferInstruction(
                                    CardAuthorizationSimulation.PendingTransaction.Source
                                        .CheckTransferInstruction
                                        .builder()
                                        .amount(123L)
                                        .currency(
                                            CardAuthorizationSimulation.PendingTransaction.Source
                                                .CheckTransferInstruction
                                                .Currency
                                                .CAD
                                        )
                                        .transferId("string")
                                        .build()
                                )
                                .inboundFundsHold(
                                    CardAuthorizationSimulation.PendingTransaction.Source
                                        .InboundFundsHold
                                        .builder()
                                        .amount(123L)
                                        .automaticallyReleasesAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .currency(
                                            CardAuthorizationSimulation.PendingTransaction.Source
                                                .InboundFundsHold
                                                .Currency
                                                .CAD
                                        )
                                        .heldTransactionId("string")
                                        .pendingTransactionId("string")
                                        .releasedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .status(
                                            CardAuthorizationSimulation.PendingTransaction.Source
                                                .InboundFundsHold
                                                .Status
                                                .HELD
                                        )
                                        .type(
                                            CardAuthorizationSimulation.PendingTransaction.Source
                                                .InboundFundsHold
                                                .Type
                                                .INBOUND_FUNDS_HOLD
                                        )
                                        .build()
                                )
                                .realTimePaymentsTransferInstruction(
                                    CardAuthorizationSimulation.PendingTransaction.Source
                                        .RealTimePaymentsTransferInstruction
                                        .builder()
                                        .amount(123L)
                                        .transferId("string")
                                        .build()
                                )
                                .wireTransferInstruction(
                                    CardAuthorizationSimulation.PendingTransaction.Source
                                        .WireTransferInstruction
                                        .builder()
                                        .accountNumber("string")
                                        .amount(123L)
                                        .messageToRecipient("string")
                                        .routingNumber("string")
                                        .transferId("string")
                                        .build()
                                )
                                .build()
                        )
                        .status(CardAuthorizationSimulation.PendingTransaction.Status.PENDING)
                        .type(
                            CardAuthorizationSimulation.PendingTransaction.Type.PENDING_TRANSACTION
                        )
                        .build()
                )
                .type(CardAuthorizationSimulation.Type.INBOUND_CARD_AUTHORIZATION_SIMULATION_RESULT)
                .build()
        assertThat(cardAuthorizationSimulation).isNotNull
        assertThat(cardAuthorizationSimulation.declinedTransaction())
            .isEqualTo(
                CardAuthorizationSimulation.DeclinedTransaction.builder()
                    .id("string")
                    .accountId("string")
                    .amount(123L)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .currency(CardAuthorizationSimulation.DeclinedTransaction.Currency.CAD)
                    .description("string")
                    .routeId("string")
                    .routeType(
                        CardAuthorizationSimulation.DeclinedTransaction.RouteType.ACCOUNT_NUMBER
                    )
                    .source(
                        CardAuthorizationSimulation.DeclinedTransaction.Source.builder()
                            .achDecline(
                                CardAuthorizationSimulation.DeclinedTransaction.Source.AchDecline
                                    .builder()
                                    .amount(123L)
                                    .originatorCompanyDescriptiveDate("string")
                                    .originatorCompanyDiscretionaryData("string")
                                    .originatorCompanyId("string")
                                    .originatorCompanyName("string")
                                    .reason(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .AchDecline
                                            .Reason
                                            .ACH_ROUTE_CANCELED
                                    )
                                    .receiverIdNumber("string")
                                    .receiverName("string")
                                    .traceNumber("string")
                                    .build()
                            )
                            .cardDecline(
                                CardAuthorizationSimulation.DeclinedTransaction.Source.CardDecline
                                    .builder()
                                    .amount(123L)
                                    .currency(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .CardDecline
                                            .Currency
                                            .CAD
                                    )
                                    .digitalWalletTokenId("string")
                                    .merchantAcceptorId("string")
                                    .merchantCategoryCode("string")
                                    .merchantCity("string")
                                    .merchantCountry("string")
                                    .merchantDescriptor("string")
                                    .merchantState("string")
                                    .network(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .CardDecline
                                            .Network
                                            .VISA
                                    )
                                    .networkDetails(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .CardDecline
                                            .NetworkDetails
                                            .builder()
                                            .visa(
                                                CardAuthorizationSimulation.DeclinedTransaction
                                                    .Source
                                                    .CardDecline
                                                    .NetworkDetails
                                                    .Visa
                                                    .builder()
                                                    .electronicCommerceIndicator(
                                                        CardAuthorizationSimulation
                                                            .DeclinedTransaction
                                                            .Source
                                                            .CardDecline
                                                            .NetworkDetails
                                                            .Visa
                                                            .ElectronicCommerceIndicator
                                                            .MAIL_PHONE_ORDER
                                                    )
                                                    .pointOfServiceEntryMode(
                                                        PointOfServiceEntryMode.MANUAL
                                                    )
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .physicalCardId("string")
                                    .realTimeDecisionId("string")
                                    .reason(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .CardDecline
                                            .Reason
                                            .CARD_NOT_ACTIVE
                                    )
                                    .build()
                            )
                            .category(
                                CardAuthorizationSimulation.DeclinedTransaction.Source.Category
                                    .ACH_DECLINE
                            )
                            .checkDecline(
                                CardAuthorizationSimulation.DeclinedTransaction.Source.CheckDecline
                                    .builder()
                                    .amount(123L)
                                    .auxiliaryOnUs("string")
                                    .reason(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .CheckDecline
                                            .Reason
                                            .ACH_ROUTE_CANCELED
                                    )
                                    .build()
                            )
                            .inboundRealTimePaymentsTransferDecline(
                                CardAuthorizationSimulation.DeclinedTransaction.Source
                                    .InboundRealTimePaymentsTransferDecline
                                    .builder()
                                    .amount(123L)
                                    .creditorName("string")
                                    .currency(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .InboundRealTimePaymentsTransferDecline
                                            .Currency
                                            .CAD
                                    )
                                    .debtorAccountNumber("string")
                                    .debtorName("string")
                                    .debtorRoutingNumber("string")
                                    .reason(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .InboundRealTimePaymentsTransferDecline
                                            .Reason
                                            .ACCOUNT_NUMBER_CANCELED
                                    )
                                    .remittanceInformation("string")
                                    .transactionIdentification("string")
                                    .build()
                            )
                            .internationalAchDecline(
                                CardAuthorizationSimulation.DeclinedTransaction.Source
                                    .InternationalAchDecline
                                    .builder()
                                    .amount(123L)
                                    .destinationCountryCode("string")
                                    .destinationCurrencyCode("string")
                                    .foreignExchangeIndicator("string")
                                    .foreignExchangeReference("string")
                                    .foreignExchangeReferenceIndicator("string")
                                    .foreignPaymentAmount(123L)
                                    .foreignTraceNumber("string")
                                    .internationalTransactionTypeCode("string")
                                    .originatingCurrencyCode("string")
                                    .originatingDepositoryFinancialInstitutionBranchCountry(
                                        "string"
                                    )
                                    .originatingDepositoryFinancialInstitutionId("string")
                                    .originatingDepositoryFinancialInstitutionIdQualifier("string")
                                    .originatingDepositoryFinancialInstitutionName("string")
                                    .originatorCity("string")
                                    .originatorCompanyEntryDescription("string")
                                    .originatorCountry("string")
                                    .originatorIdentification("string")
                                    .originatorName("string")
                                    .originatorPostalCode("string")
                                    .originatorStateOrProvince("string")
                                    .originatorStreetAddress("string")
                                    .paymentRelatedInformation("string")
                                    .paymentRelatedInformation2("string")
                                    .receiverCity("string")
                                    .receiverCountry("string")
                                    .receiverIdentificationNumber("string")
                                    .receiverPostalCode("string")
                                    .receiverStateOrProvince("string")
                                    .receiverStreetAddress("string")
                                    .receivingCompanyOrIndividualName("string")
                                    .receivingDepositoryFinancialInstitutionCountry("string")
                                    .receivingDepositoryFinancialInstitutionId("string")
                                    .receivingDepositoryFinancialInstitutionIdQualifier("string")
                                    .receivingDepositoryFinancialInstitutionName("string")
                                    .traceNumber("string")
                                    .build()
                            )
                            .wireDecline(
                                CardAuthorizationSimulation.DeclinedTransaction.Source.WireDecline
                                    .builder()
                                    .amount(123L)
                                    .beneficiaryAddressLine1("string")
                                    .beneficiaryAddressLine2("string")
                                    .beneficiaryAddressLine3("string")
                                    .beneficiaryName("string")
                                    .beneficiaryReference("string")
                                    .description("string")
                                    .inputMessageAccountabilityData("string")
                                    .originatorAddressLine1("string")
                                    .originatorAddressLine2("string")
                                    .originatorAddressLine3("string")
                                    .originatorName("string")
                                    .originatorToBeneficiaryInformationLine1("string")
                                    .originatorToBeneficiaryInformationLine2("string")
                                    .originatorToBeneficiaryInformationLine3("string")
                                    .originatorToBeneficiaryInformationLine4("string")
                                    .reason(
                                        CardAuthorizationSimulation.DeclinedTransaction.Source
                                            .WireDecline
                                            .Reason
                                            .ACCOUNT_NUMBER_CANCELED
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .type(CardAuthorizationSimulation.DeclinedTransaction.Type.DECLINED_TRANSACTION)
                    .build()
            )
        assertThat(cardAuthorizationSimulation.pendingTransaction())
            .isEqualTo(
                CardAuthorizationSimulation.PendingTransaction.builder()
                    .id("string")
                    .accountId("string")
                    .amount(123L)
                    .completedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .currency(CardAuthorizationSimulation.PendingTransaction.Currency.CAD)
                    .description("string")
                    .routeId("string")
                    .routeType(
                        CardAuthorizationSimulation.PendingTransaction.RouteType.ACCOUNT_NUMBER
                    )
                    .source(
                        CardAuthorizationSimulation.PendingTransaction.Source.builder()
                            .accountTransferInstruction(
                                CardAuthorizationSimulation.PendingTransaction.Source
                                    .AccountTransferInstruction
                                    .builder()
                                    .amount(123L)
                                    .currency(
                                        CardAuthorizationSimulation.PendingTransaction.Source
                                            .AccountTransferInstruction
                                            .Currency
                                            .CAD
                                    )
                                    .transferId("string")
                                    .build()
                            )
                            .achTransferInstruction(
                                CardAuthorizationSimulation.PendingTransaction.Source
                                    .AchTransferInstruction
                                    .builder()
                                    .amount(123L)
                                    .transferId("string")
                                    .build()
                            )
                            .cardAuthorization(
                                CardAuthorizationSimulation.PendingTransaction.Source
                                    .CardAuthorization
                                    .builder()
                                    .id("string")
                                    .amount(123L)
                                    .currency(
                                        CardAuthorizationSimulation.PendingTransaction.Source
                                            .CardAuthorization
                                            .Currency
                                            .CAD
                                    )
                                    .digitalWalletTokenId("string")
                                    .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .merchantAcceptorId("string")
                                    .merchantCategoryCode("string")
                                    .merchantCity("string")
                                    .merchantCountry("string")
                                    .merchantDescriptor("string")
                                    .network(
                                        CardAuthorizationSimulation.PendingTransaction.Source
                                            .CardAuthorization
                                            .Network
                                            .VISA
                                    )
                                    .networkDetails(
                                        CardAuthorizationSimulation.PendingTransaction.Source
                                            .CardAuthorization
                                            .NetworkDetails
                                            .builder()
                                            .visa(
                                                CardAuthorizationSimulation.PendingTransaction
                                                    .Source
                                                    .CardAuthorization
                                                    .NetworkDetails
                                                    .Visa
                                                    .builder()
                                                    .electronicCommerceIndicator(
                                                        CardAuthorizationSimulation
                                                            .PendingTransaction
                                                            .Source
                                                            .CardAuthorization
                                                            .NetworkDetails
                                                            .Visa
                                                            .ElectronicCommerceIndicator
                                                            .MAIL_PHONE_ORDER
                                                    )
                                                    .pointOfServiceEntryMode(
                                                        PointOfServiceEntryMode.MANUAL
                                                    )
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .pendingTransactionId("string")
                                    .physicalCardId("string")
                                    .realTimeDecisionId("string")
                                    .type(
                                        CardAuthorizationSimulation.PendingTransaction.Source
                                            .CardAuthorization
                                            .Type
                                            .CARD_AUTHORIZATION
                                    )
                                    .build()
                            )
                            .category(
                                CardAuthorizationSimulation.PendingTransaction.Source.Category
                                    .ACCOUNT_TRANSFER_INSTRUCTION
                            )
                            .checkDepositInstruction(
                                CardAuthorizationSimulation.PendingTransaction.Source
                                    .CheckDepositInstruction
                                    .builder()
                                    .amount(123L)
                                    .backImageFileId("string")
                                    .checkDepositId("string")
                                    .currency(
                                        CardAuthorizationSimulation.PendingTransaction.Source
                                            .CheckDepositInstruction
                                            .Currency
                                            .CAD
                                    )
                                    .frontImageFileId("string")
                                    .build()
                            )
                            .checkTransferInstruction(
                                CardAuthorizationSimulation.PendingTransaction.Source
                                    .CheckTransferInstruction
                                    .builder()
                                    .amount(123L)
                                    .currency(
                                        CardAuthorizationSimulation.PendingTransaction.Source
                                            .CheckTransferInstruction
                                            .Currency
                                            .CAD
                                    )
                                    .transferId("string")
                                    .build()
                            )
                            .inboundFundsHold(
                                CardAuthorizationSimulation.PendingTransaction.Source
                                    .InboundFundsHold
                                    .builder()
                                    .amount(123L)
                                    .automaticallyReleasesAt(
                                        OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                    )
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .currency(
                                        CardAuthorizationSimulation.PendingTransaction.Source
                                            .InboundFundsHold
                                            .Currency
                                            .CAD
                                    )
                                    .heldTransactionId("string")
                                    .pendingTransactionId("string")
                                    .releasedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .status(
                                        CardAuthorizationSimulation.PendingTransaction.Source
                                            .InboundFundsHold
                                            .Status
                                            .HELD
                                    )
                                    .type(
                                        CardAuthorizationSimulation.PendingTransaction.Source
                                            .InboundFundsHold
                                            .Type
                                            .INBOUND_FUNDS_HOLD
                                    )
                                    .build()
                            )
                            .realTimePaymentsTransferInstruction(
                                CardAuthorizationSimulation.PendingTransaction.Source
                                    .RealTimePaymentsTransferInstruction
                                    .builder()
                                    .amount(123L)
                                    .transferId("string")
                                    .build()
                            )
                            .wireTransferInstruction(
                                CardAuthorizationSimulation.PendingTransaction.Source
                                    .WireTransferInstruction
                                    .builder()
                                    .accountNumber("string")
                                    .amount(123L)
                                    .messageToRecipient("string")
                                    .routingNumber("string")
                                    .transferId("string")
                                    .build()
                            )
                            .build()
                    )
                    .status(CardAuthorizationSimulation.PendingTransaction.Status.PENDING)
                    .type(CardAuthorizationSimulation.PendingTransaction.Type.PENDING_TRANSACTION)
                    .build()
            )
        assertThat(cardAuthorizationSimulation.type())
            .isEqualTo(
                CardAuthorizationSimulation.Type.INBOUND_CARD_AUTHORIZATION_SIMULATION_RESULT
            )
    }
}
