// File generated from our OpenAPI spec by Stainless.

package com.increase.api.models

import com.increase.api.core.JsonValue
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class DeclinedTransactionTest {

    @Test
    fun createDeclinedTransaction() {
        val declinedTransaction =
            DeclinedTransaction.builder()
                .id("declined_transaction_17jbn0yyhvkt4v4ooym8")
                .accountId("account_in71c4amph0vgo2qllky")
                .amount(1750L)
                .createdAt(OffsetDateTime.parse("2020-01-31T23:59:59Z"))
                .currency(DeclinedTransaction.Currency.CAD)
                .description("INVOICE 2468")
                .routeId("account_number_v18nkfqm6afpsrvy82b2")
                .routeType(DeclinedTransaction.RouteType.ACCOUNT_NUMBER)
                .source(
                    DeclinedTransaction.Source.builder()
                        .achDecline(
                            DeclinedTransaction.Source.AchDecline.builder()
                                .id("ach_decline_72v1mcwxudctq56efipa")
                                .amount(1750L)
                                .inboundAchTransferId("inbound_ach_transfer_tdrwqr3fq9gnnq49odev")
                                .originatorCompanyDescriptiveDate(null)
                                .originatorCompanyDiscretionaryData(null)
                                .originatorCompanyId("0987654321")
                                .originatorCompanyName("BIG BANK")
                                .reason(
                                    DeclinedTransaction.Source.AchDecline.Reason.ACH_ROUTE_CANCELED
                                )
                                .receiverIdNumber("12345678900")
                                .receiverName("IAN CREASE")
                                .traceNumber("021000038461022")
                                .type(DeclinedTransaction.Source.AchDecline.Type.ACH_DECLINE)
                                .build()
                        )
                        .cardDecline(
                            DeclinedTransaction.Source.CardDecline.builder()
                                .id("card_decline_bx3o8zd7glq8yvtwg25v")
                                .actioner(DeclinedTransaction.Source.CardDecline.Actioner.USER)
                                .amount(-1000L)
                                .cardPaymentId("card_payment_nd3k2kacrqjli8482ave")
                                .currency(DeclinedTransaction.Source.CardDecline.Currency.CAD)
                                .declinedTransactionId("declined_transaction_17jbn0yyhvkt4v4ooym8")
                                .digitalWalletTokenId(null)
                                .direction(
                                    DeclinedTransaction.Source.CardDecline.Direction.SETTLEMENT
                                )
                                .merchantAcceptorId("5665270011000168")
                                .merchantCategoryCode("5734")
                                .merchantCity("New York")
                                .merchantCountry("US")
                                .merchantDescriptor("AMAZON.COM")
                                .merchantPostalCode("10045")
                                .merchantState(null)
                                .networkDetails(
                                    DeclinedTransaction.Source.CardDecline.NetworkDetails.builder()
                                        .category(
                                            DeclinedTransaction.Source.CardDecline.NetworkDetails
                                                .Category
                                                .VISA
                                        )
                                        .visa(
                                            DeclinedTransaction.Source.CardDecline.NetworkDetails
                                                .Visa
                                                .builder()
                                                .electronicCommerceIndicator(
                                                    DeclinedTransaction.Source.CardDecline
                                                        .NetworkDetails
                                                        .Visa
                                                        .ElectronicCommerceIndicator
                                                        .MAIL_PHONE_ORDER
                                                )
                                                .pointOfServiceEntryMode(
                                                    DeclinedTransaction.Source.CardDecline
                                                        .NetworkDetails
                                                        .Visa
                                                        .PointOfServiceEntryMode
                                                        .UNKNOWN
                                                )
                                                .standInProcessingReason(
                                                    DeclinedTransaction.Source.CardDecline
                                                        .NetworkDetails
                                                        .Visa
                                                        .StandInProcessingReason
                                                        .ISSUER_ERROR
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .networkIdentifiers(
                                    DeclinedTransaction.Source.CardDecline.NetworkIdentifiers
                                        .builder()
                                        .retrievalReferenceNumber("785867080153")
                                        .traceNumber("487941")
                                        .transactionId("627199945183184")
                                        .build()
                                )
                                .networkRiskScore(10L)
                                .physicalCardId(null)
                                .presentmentAmount(-1000L)
                                .presentmentCurrency("USD")
                                .processingCategory(
                                    DeclinedTransaction.Source.CardDecline.ProcessingCategory
                                        .ACCOUNT_FUNDING
                                )
                                .realTimeDecisionId(null)
                                .realTimeDecisionReason(
                                    DeclinedTransaction.Source.CardDecline.RealTimeDecisionReason
                                        .INSUFFICIENT_FUNDS
                                )
                                .reason(
                                    DeclinedTransaction.Source.CardDecline.Reason.ACCOUNT_CLOSED
                                )
                                .terminalId("RCN5VNXS")
                                .verification(
                                    DeclinedTransaction.Source.CardDecline.Verification.builder()
                                        .cardVerificationCode(
                                            DeclinedTransaction.Source.CardDecline.Verification
                                                .CardVerificationCode
                                                .builder()
                                                .result(
                                                    DeclinedTransaction.Source.CardDecline
                                                        .Verification
                                                        .CardVerificationCode
                                                        .Result
                                                        .NOT_CHECKED
                                                )
                                                .build()
                                        )
                                        .cardholderAddress(
                                            DeclinedTransaction.Source.CardDecline.Verification
                                                .CardholderAddress
                                                .builder()
                                                .actualLine1("33 Liberty Street")
                                                .actualPostalCode("94131")
                                                .providedLine1("33 Liberty Street")
                                                .providedPostalCode("94132")
                                                .result(
                                                    DeclinedTransaction.Source.CardDecline
                                                        .Verification
                                                        .CardholderAddress
                                                        .Result
                                                        .NOT_CHECKED
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .category(DeclinedTransaction.Source.Category.ACH_DECLINE)
                        .checkDecline(
                            DeclinedTransaction.Source.CheckDecline.builder()
                                .amount(-1000L)
                                .auxiliaryOnUs("99999")
                                .backImageFileId(null)
                                .checkTransferId("check_transfer_30b43acfu9vw8fyc4f5")
                                .frontImageFileId(null)
                                .inboundCheckDepositId("inbound_check_deposit_zoshvqybq0cjjm31mra")
                                .reason(
                                    DeclinedTransaction.Source.CheckDecline.Reason
                                        .ACH_ROUTE_DISABLED
                                )
                                .build()
                        )
                        .checkDepositRejection(
                            DeclinedTransaction.Source.CheckDepositRejection.builder()
                                .amount(1750L)
                                .checkDepositId("check_deposit_f06n9gpg7sxn8t19lfc1")
                                .currency(
                                    DeclinedTransaction.Source.CheckDepositRejection.Currency.CAD
                                )
                                .declinedTransactionId("declined_transaction_17jbn0yyhvkt4v4ooym8")
                                .reason(
                                    DeclinedTransaction.Source.CheckDepositRejection.Reason
                                        .INCOMPLETE_IMAGE
                                )
                                .rejectedAt(OffsetDateTime.parse("2020-01-31T23:59:59Z"))
                                .build()
                        )
                        .inboundRealTimePaymentsTransferDecline(
                            DeclinedTransaction.Source.InboundRealTimePaymentsTransferDecline
                                .builder()
                                .amount(100L)
                                .creditorName("Ian Crease")
                                .currency(
                                    DeclinedTransaction.Source
                                        .InboundRealTimePaymentsTransferDecline
                                        .Currency
                                        .CAD
                                )
                                .debtorAccountNumber("987654321")
                                .debtorName("National Phonograph Company")
                                .debtorRoutingNumber("101050001")
                                .reason(
                                    DeclinedTransaction.Source
                                        .InboundRealTimePaymentsTransferDecline
                                        .Reason
                                        .ACCOUNT_NUMBER_CANCELED
                                )
                                .remittanceInformation("Invoice 29582")
                                .transactionIdentification("20220501234567891T1BSLZO01745013025")
                                .transferId(
                                    "inbound_real_time_payments_transfer_63hlz498vcxg644hcrzr"
                                )
                                .build()
                        )
                        .other(JsonValue.from(mapOf<String, Any>()))
                        .wireDecline(
                            DeclinedTransaction.Source.WireDecline.builder()
                                .inboundWireTransferId("inbound_wire_transfer_f228m6bmhtcxjco9pwp0")
                                .reason(
                                    DeclinedTransaction.Source.WireDecline.Reason
                                        .ACCOUNT_NUMBER_CANCELED
                                )
                                .build()
                        )
                        .build()
                )
                .type(DeclinedTransaction.Type.DECLINED_TRANSACTION)
                .build()
        assertThat(declinedTransaction).isNotNull
        assertThat(declinedTransaction.id()).isEqualTo("declined_transaction_17jbn0yyhvkt4v4ooym8")
        assertThat(declinedTransaction.accountId()).isEqualTo("account_in71c4amph0vgo2qllky")
        assertThat(declinedTransaction.amount()).isEqualTo(1750L)
        assertThat(declinedTransaction.createdAt())
            .isEqualTo(OffsetDateTime.parse("2020-01-31T23:59:59Z"))
        assertThat(declinedTransaction.currency()).isEqualTo(DeclinedTransaction.Currency.CAD)
        assertThat(declinedTransaction.description()).isEqualTo("INVOICE 2468")
        assertThat(declinedTransaction.routeId()).isEqualTo("account_number_v18nkfqm6afpsrvy82b2")
        assertThat(declinedTransaction.routeType())
            .isEqualTo(DeclinedTransaction.RouteType.ACCOUNT_NUMBER)
        assertThat(declinedTransaction.source())
            .isEqualTo(
                DeclinedTransaction.Source.builder()
                    .achDecline(
                        DeclinedTransaction.Source.AchDecline.builder()
                            .id("ach_decline_72v1mcwxudctq56efipa")
                            .amount(1750L)
                            .inboundAchTransferId("inbound_ach_transfer_tdrwqr3fq9gnnq49odev")
                            .originatorCompanyDescriptiveDate(null)
                            .originatorCompanyDiscretionaryData(null)
                            .originatorCompanyId("0987654321")
                            .originatorCompanyName("BIG BANK")
                            .reason(DeclinedTransaction.Source.AchDecline.Reason.ACH_ROUTE_CANCELED)
                            .receiverIdNumber("12345678900")
                            .receiverName("IAN CREASE")
                            .traceNumber("021000038461022")
                            .type(DeclinedTransaction.Source.AchDecline.Type.ACH_DECLINE)
                            .build()
                    )
                    .cardDecline(
                        DeclinedTransaction.Source.CardDecline.builder()
                            .id("card_decline_bx3o8zd7glq8yvtwg25v")
                            .actioner(DeclinedTransaction.Source.CardDecline.Actioner.USER)
                            .amount(-1000L)
                            .cardPaymentId("card_payment_nd3k2kacrqjli8482ave")
                            .currency(DeclinedTransaction.Source.CardDecline.Currency.CAD)
                            .declinedTransactionId("declined_transaction_17jbn0yyhvkt4v4ooym8")
                            .digitalWalletTokenId(null)
                            .direction(DeclinedTransaction.Source.CardDecline.Direction.SETTLEMENT)
                            .merchantAcceptorId("5665270011000168")
                            .merchantCategoryCode("5734")
                            .merchantCity("New York")
                            .merchantCountry("US")
                            .merchantDescriptor("AMAZON.COM")
                            .merchantPostalCode("10045")
                            .merchantState(null)
                            .networkDetails(
                                DeclinedTransaction.Source.CardDecline.NetworkDetails.builder()
                                    .category(
                                        DeclinedTransaction.Source.CardDecline.NetworkDetails
                                            .Category
                                            .VISA
                                    )
                                    .visa(
                                        DeclinedTransaction.Source.CardDecline.NetworkDetails.Visa
                                            .builder()
                                            .electronicCommerceIndicator(
                                                DeclinedTransaction.Source.CardDecline
                                                    .NetworkDetails
                                                    .Visa
                                                    .ElectronicCommerceIndicator
                                                    .MAIL_PHONE_ORDER
                                            )
                                            .pointOfServiceEntryMode(
                                                DeclinedTransaction.Source.CardDecline
                                                    .NetworkDetails
                                                    .Visa
                                                    .PointOfServiceEntryMode
                                                    .UNKNOWN
                                            )
                                            .standInProcessingReason(
                                                DeclinedTransaction.Source.CardDecline
                                                    .NetworkDetails
                                                    .Visa
                                                    .StandInProcessingReason
                                                    .ISSUER_ERROR
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .networkIdentifiers(
                                DeclinedTransaction.Source.CardDecline.NetworkIdentifiers.builder()
                                    .retrievalReferenceNumber("785867080153")
                                    .traceNumber("487941")
                                    .transactionId("627199945183184")
                                    .build()
                            )
                            .networkRiskScore(10L)
                            .physicalCardId(null)
                            .presentmentAmount(-1000L)
                            .presentmentCurrency("USD")
                            .processingCategory(
                                DeclinedTransaction.Source.CardDecline.ProcessingCategory
                                    .ACCOUNT_FUNDING
                            )
                            .realTimeDecisionId(null)
                            .realTimeDecisionReason(
                                DeclinedTransaction.Source.CardDecline.RealTimeDecisionReason
                                    .INSUFFICIENT_FUNDS
                            )
                            .reason(DeclinedTransaction.Source.CardDecline.Reason.ACCOUNT_CLOSED)
                            .terminalId("RCN5VNXS")
                            .verification(
                                DeclinedTransaction.Source.CardDecline.Verification.builder()
                                    .cardVerificationCode(
                                        DeclinedTransaction.Source.CardDecline.Verification
                                            .CardVerificationCode
                                            .builder()
                                            .result(
                                                DeclinedTransaction.Source.CardDecline.Verification
                                                    .CardVerificationCode
                                                    .Result
                                                    .NOT_CHECKED
                                            )
                                            .build()
                                    )
                                    .cardholderAddress(
                                        DeclinedTransaction.Source.CardDecline.Verification
                                            .CardholderAddress
                                            .builder()
                                            .actualLine1("33 Liberty Street")
                                            .actualPostalCode("94131")
                                            .providedLine1("33 Liberty Street")
                                            .providedPostalCode("94132")
                                            .result(
                                                DeclinedTransaction.Source.CardDecline.Verification
                                                    .CardholderAddress
                                                    .Result
                                                    .NOT_CHECKED
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .category(DeclinedTransaction.Source.Category.ACH_DECLINE)
                    .checkDecline(
                        DeclinedTransaction.Source.CheckDecline.builder()
                            .amount(-1000L)
                            .auxiliaryOnUs("99999")
                            .backImageFileId(null)
                            .checkTransferId("check_transfer_30b43acfu9vw8fyc4f5")
                            .frontImageFileId(null)
                            .inboundCheckDepositId("inbound_check_deposit_zoshvqybq0cjjm31mra")
                            .reason(
                                DeclinedTransaction.Source.CheckDecline.Reason.ACH_ROUTE_DISABLED
                            )
                            .build()
                    )
                    .checkDepositRejection(
                        DeclinedTransaction.Source.CheckDepositRejection.builder()
                            .amount(1750L)
                            .checkDepositId("check_deposit_f06n9gpg7sxn8t19lfc1")
                            .currency(DeclinedTransaction.Source.CheckDepositRejection.Currency.CAD)
                            .declinedTransactionId("declined_transaction_17jbn0yyhvkt4v4ooym8")
                            .reason(
                                DeclinedTransaction.Source.CheckDepositRejection.Reason
                                    .INCOMPLETE_IMAGE
                            )
                            .rejectedAt(OffsetDateTime.parse("2020-01-31T23:59:59Z"))
                            .build()
                    )
                    .inboundRealTimePaymentsTransferDecline(
                        DeclinedTransaction.Source.InboundRealTimePaymentsTransferDecline.builder()
                            .amount(100L)
                            .creditorName("Ian Crease")
                            .currency(
                                DeclinedTransaction.Source.InboundRealTimePaymentsTransferDecline
                                    .Currency
                                    .CAD
                            )
                            .debtorAccountNumber("987654321")
                            .debtorName("National Phonograph Company")
                            .debtorRoutingNumber("101050001")
                            .reason(
                                DeclinedTransaction.Source.InboundRealTimePaymentsTransferDecline
                                    .Reason
                                    .ACCOUNT_NUMBER_CANCELED
                            )
                            .remittanceInformation("Invoice 29582")
                            .transactionIdentification("20220501234567891T1BSLZO01745013025")
                            .transferId("inbound_real_time_payments_transfer_63hlz498vcxg644hcrzr")
                            .build()
                    )
                    .other(JsonValue.from(mapOf<String, Any>()))
                    .wireDecline(
                        DeclinedTransaction.Source.WireDecline.builder()
                            .inboundWireTransferId("inbound_wire_transfer_f228m6bmhtcxjco9pwp0")
                            .reason(
                                DeclinedTransaction.Source.WireDecline.Reason
                                    .ACCOUNT_NUMBER_CANCELED
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(declinedTransaction.type())
            .isEqualTo(DeclinedTransaction.Type.DECLINED_TRANSACTION)
    }
}
