package com.increase.api.models

import java.time.LocalDate
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class EntityTest {

    @Test
    fun createEntity() {
        val entity =
            Entity.builder()
                .id("string")
                .structure(Entity.Structure.CORPORATION)
                .corporation(
                    Entity.Corporation.builder()
                        .name("string")
                        .website("string")
                        .taxIdentifier("string")
                        .incorporationState("string")
                        .address(
                            Entity.Corporation.Address.builder()
                                .line1("string")
                                .line2("string")
                                .city("string")
                                .state("string")
                                .zip("string")
                                .build()
                        )
                        .beneficialOwners(
                            listOf(
                                Entity.Corporation.BeneficialOwner.builder()
                                    .individual(
                                        Entity.Corporation.BeneficialOwner.Individual.builder()
                                            .name("string")
                                            .dateOfBirth(LocalDate.parse("2019-12-27"))
                                            .address(
                                                Entity.Corporation.BeneficialOwner.Individual
                                                    .Address
                                                    .builder()
                                                    .line1("string")
                                                    .line2("string")
                                                    .city("string")
                                                    .state("string")
                                                    .zip("string")
                                                    .build()
                                            )
                                            .identification(
                                                Entity.Corporation.BeneficialOwner.Individual
                                                    .Identification
                                                    .builder()
                                                    .method(
                                                        Entity.Corporation.BeneficialOwner
                                                            .Individual
                                                            .Identification
                                                            .Method
                                                            .SOCIAL_SECURITY_NUMBER
                                                    )
                                                    .numberLast4("string")
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .companyTitle("string")
                                    .prong(Entity.Corporation.BeneficialOwner.Prong.OWNERSHIP)
                                    .build()
                            )
                        )
                        .build()
                )
                .naturalPerson(
                    Entity.NaturalPerson.builder()
                        .name("string")
                        .dateOfBirth(LocalDate.parse("2019-12-27"))
                        .address(
                            Entity.NaturalPerson.Address.builder()
                                .line1("string")
                                .line2("string")
                                .city("string")
                                .state("string")
                                .zip("string")
                                .build()
                        )
                        .identification(
                            Entity.NaturalPerson.Identification.builder()
                                .method(
                                    Entity.NaturalPerson.Identification.Method
                                        .SOCIAL_SECURITY_NUMBER
                                )
                                .numberLast4("string")
                                .build()
                        )
                        .build()
                )
                .joint(
                    Entity.Joint.builder()
                        .name("string")
                        .individuals(
                            listOf(
                                Entity.Joint.Individual.builder()
                                    .name("string")
                                    .dateOfBirth(LocalDate.parse("2019-12-27"))
                                    .address(
                                        Entity.Joint.Individual.Address.builder()
                                            .line1("string")
                                            .line2("string")
                                            .city("string")
                                            .state("string")
                                            .zip("string")
                                            .build()
                                    )
                                    .identification(
                                        Entity.Joint.Individual.Identification.builder()
                                            .method(
                                                Entity.Joint.Individual.Identification.Method
                                                    .SOCIAL_SECURITY_NUMBER
                                            )
                                            .numberLast4("string")
                                            .build()
                                    )
                                    .build()
                            )
                        )
                        .build()
                )
                .trust(
                    Entity.Trust.builder()
                        .name("string")
                        .category(Entity.Trust.Category.REVOCABLE)
                        .address(
                            Entity.Trust.Address.builder()
                                .line1("string")
                                .line2("string")
                                .city("string")
                                .state("string")
                                .zip("string")
                                .build()
                        )
                        .formationState("string")
                        .taxIdentifier("string")
                        .trustees(
                            listOf(
                                Entity.Trust.Trustee.builder()
                                    .structure(Entity.Trust.Trustee.Structure.INDIVIDUAL)
                                    .individual(
                                        Entity.Trust.Trustee.Individual.builder()
                                            .name("string")
                                            .dateOfBirth(LocalDate.parse("2019-12-27"))
                                            .address(
                                                Entity.Trust.Trustee.Individual.Address.builder()
                                                    .line1("string")
                                                    .line2("string")
                                                    .city("string")
                                                    .state("string")
                                                    .zip("string")
                                                    .build()
                                            )
                                            .identification(
                                                Entity.Trust.Trustee.Individual.Identification
                                                    .builder()
                                                    .method(
                                                        Entity.Trust.Trustee.Individual
                                                            .Identification
                                                            .Method
                                                            .SOCIAL_SECURITY_NUMBER
                                                    )
                                                    .numberLast4("string")
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                        )
                        .grantor(
                            Entity.Trust.Grantor.builder()
                                .name("string")
                                .dateOfBirth(LocalDate.parse("2019-12-27"))
                                .address(
                                    Entity.Trust.Grantor.Address.builder()
                                        .line1("string")
                                        .line2("string")
                                        .city("string")
                                        .state("string")
                                        .zip("string")
                                        .build()
                                )
                                .identification(
                                    Entity.Trust.Grantor.Identification.builder()
                                        .method(
                                            Entity.Trust.Grantor.Identification.Method
                                                .SOCIAL_SECURITY_NUMBER
                                        )
                                        .numberLast4("string")
                                        .build()
                                )
                                .build()
                        )
                        .formationDocumentFileId("string")
                        .build()
                )
                .type(Entity.Type.ENTITY)
                .description("string")
                .relationship(Entity.Relationship.AFFILIATED)
                .supplementalDocuments(
                    listOf(
                        Entity.SupplementalDocument.builder()
                            .fileId("string")
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .type(Entity.SupplementalDocument.Type.ENTITY_SUPPLEMENTAL_DOCUMENT)
                            .build()
                    )
                )
                .build()
        assertThat(entity).isNotNull
        assertThat(entity.id()).isEqualTo("string")
        assertThat(entity.structure()).isEqualTo(Entity.Structure.CORPORATION)
        assertThat(entity.corporation())
            .isEqualTo(
                Entity.Corporation.builder()
                    .name("string")
                    .website("string")
                    .taxIdentifier("string")
                    .incorporationState("string")
                    .address(
                        Entity.Corporation.Address.builder()
                            .line1("string")
                            .line2("string")
                            .city("string")
                            .state("string")
                            .zip("string")
                            .build()
                    )
                    .beneficialOwners(
                        listOf(
                            Entity.Corporation.BeneficialOwner.builder()
                                .individual(
                                    Entity.Corporation.BeneficialOwner.Individual.builder()
                                        .name("string")
                                        .dateOfBirth(LocalDate.parse("2019-12-27"))
                                        .address(
                                            Entity.Corporation.BeneficialOwner.Individual.Address
                                                .builder()
                                                .line1("string")
                                                .line2("string")
                                                .city("string")
                                                .state("string")
                                                .zip("string")
                                                .build()
                                        )
                                        .identification(
                                            Entity.Corporation.BeneficialOwner.Individual
                                                .Identification
                                                .builder()
                                                .method(
                                                    Entity.Corporation.BeneficialOwner.Individual
                                                        .Identification
                                                        .Method
                                                        .SOCIAL_SECURITY_NUMBER
                                                )
                                                .numberLast4("string")
                                                .build()
                                        )
                                        .build()
                                )
                                .companyTitle("string")
                                .prong(Entity.Corporation.BeneficialOwner.Prong.OWNERSHIP)
                                .build()
                        )
                    )
                    .build()
            )
        assertThat(entity.naturalPerson())
            .isEqualTo(
                Entity.NaturalPerson.builder()
                    .name("string")
                    .dateOfBirth(LocalDate.parse("2019-12-27"))
                    .address(
                        Entity.NaturalPerson.Address.builder()
                            .line1("string")
                            .line2("string")
                            .city("string")
                            .state("string")
                            .zip("string")
                            .build()
                    )
                    .identification(
                        Entity.NaturalPerson.Identification.builder()
                            .method(
                                Entity.NaturalPerson.Identification.Method.SOCIAL_SECURITY_NUMBER
                            )
                            .numberLast4("string")
                            .build()
                    )
                    .build()
            )
        assertThat(entity.joint())
            .isEqualTo(
                Entity.Joint.builder()
                    .name("string")
                    .individuals(
                        listOf(
                            Entity.Joint.Individual.builder()
                                .name("string")
                                .dateOfBirth(LocalDate.parse("2019-12-27"))
                                .address(
                                    Entity.Joint.Individual.Address.builder()
                                        .line1("string")
                                        .line2("string")
                                        .city("string")
                                        .state("string")
                                        .zip("string")
                                        .build()
                                )
                                .identification(
                                    Entity.Joint.Individual.Identification.builder()
                                        .method(
                                            Entity.Joint.Individual.Identification.Method
                                                .SOCIAL_SECURITY_NUMBER
                                        )
                                        .numberLast4("string")
                                        .build()
                                )
                                .build()
                        )
                    )
                    .build()
            )
        assertThat(entity.trust())
            .isEqualTo(
                Entity.Trust.builder()
                    .name("string")
                    .category(Entity.Trust.Category.REVOCABLE)
                    .address(
                        Entity.Trust.Address.builder()
                            .line1("string")
                            .line2("string")
                            .city("string")
                            .state("string")
                            .zip("string")
                            .build()
                    )
                    .formationState("string")
                    .taxIdentifier("string")
                    .trustees(
                        listOf(
                            Entity.Trust.Trustee.builder()
                                .structure(Entity.Trust.Trustee.Structure.INDIVIDUAL)
                                .individual(
                                    Entity.Trust.Trustee.Individual.builder()
                                        .name("string")
                                        .dateOfBirth(LocalDate.parse("2019-12-27"))
                                        .address(
                                            Entity.Trust.Trustee.Individual.Address.builder()
                                                .line1("string")
                                                .line2("string")
                                                .city("string")
                                                .state("string")
                                                .zip("string")
                                                .build()
                                        )
                                        .identification(
                                            Entity.Trust.Trustee.Individual.Identification.builder()
                                                .method(
                                                    Entity.Trust.Trustee.Individual.Identification
                                                        .Method
                                                        .SOCIAL_SECURITY_NUMBER
                                                )
                                                .numberLast4("string")
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                    )
                    .grantor(
                        Entity.Trust.Grantor.builder()
                            .name("string")
                            .dateOfBirth(LocalDate.parse("2019-12-27"))
                            .address(
                                Entity.Trust.Grantor.Address.builder()
                                    .line1("string")
                                    .line2("string")
                                    .city("string")
                                    .state("string")
                                    .zip("string")
                                    .build()
                            )
                            .identification(
                                Entity.Trust.Grantor.Identification.builder()
                                    .method(
                                        Entity.Trust.Grantor.Identification.Method
                                            .SOCIAL_SECURITY_NUMBER
                                    )
                                    .numberLast4("string")
                                    .build()
                            )
                            .build()
                    )
                    .formationDocumentFileId("string")
                    .build()
            )
        assertThat(entity.type()).isEqualTo(Entity.Type.ENTITY)
        assertThat(entity.description()).isEqualTo("string")
        assertThat(entity.relationship()).isEqualTo(Entity.Relationship.AFFILIATED)
        assertThat(entity.supplementalDocuments())
            .containsExactly(
                Entity.SupplementalDocument.builder()
                    .fileId("string")
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .type(Entity.SupplementalDocument.Type.ENTITY_SUPPLEMENTAL_DOCUMENT)
                    .build()
            )
    }
}
