// File generated from our OpenAPI spec by Stainless.

package com.increase.api.models

import com.increase.api.models.*
import java.time.LocalDate
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class EntityCreateParamsTest {

    @Test
    fun createEntityCreateParams() {
        EntityCreateParams.builder()
            .structure(EntityCreateParams.Structure.CORPORATION)
            .corporation(
                EntityCreateParams.Corporation.builder()
                    .address(
                        EntityCreateParams.Corporation.Address.builder()
                            .city("x")
                            .line1("x")
                            .state("x")
                            .zip("x")
                            .line2("x")
                            .build()
                    )
                    .beneficialOwners(
                        listOf(
                            EntityCreateParams.Corporation.BeneficialOwner.builder()
                                .individual(
                                    EntityCreateParams.Corporation.BeneficialOwner.Individual
                                        .builder()
                                        .address(
                                            EntityCreateParams.Corporation.BeneficialOwner
                                                .Individual
                                                .Address
                                                .builder()
                                                .city("x")
                                                .line1("x")
                                                .state("x")
                                                .zip("x")
                                                .line2("x")
                                                .build()
                                        )
                                        .dateOfBirth(LocalDate.parse("2019-12-27"))
                                        .identification(
                                            EntityCreateParams.Corporation.BeneficialOwner
                                                .Individual
                                                .Identification
                                                .builder()
                                                .method(
                                                    EntityCreateParams.Corporation.BeneficialOwner
                                                        .Individual
                                                        .Identification
                                                        .Method
                                                        .SOCIAL_SECURITY_NUMBER
                                                )
                                                .number("xxxx")
                                                .driversLicense(
                                                    EntityCreateParams.Corporation.BeneficialOwner
                                                        .Individual
                                                        .Identification
                                                        .DriversLicense
                                                        .builder()
                                                        .expirationDate(
                                                            LocalDate.parse("2019-12-27")
                                                        )
                                                        .fileId("string")
                                                        .state("x")
                                                        .backFileId("string")
                                                        .build()
                                                )
                                                .other(
                                                    EntityCreateParams.Corporation.BeneficialOwner
                                                        .Individual
                                                        .Identification
                                                        .Other
                                                        .builder()
                                                        .country("x")
                                                        .description("x")
                                                        .fileId("string")
                                                        .backFileId("string")
                                                        .expirationDate(
                                                            LocalDate.parse("2019-12-27")
                                                        )
                                                        .build()
                                                )
                                                .passport(
                                                    EntityCreateParams.Corporation.BeneficialOwner
                                                        .Individual
                                                        .Identification
                                                        .Passport
                                                        .builder()
                                                        .country("x")
                                                        .expirationDate(
                                                            LocalDate.parse("2019-12-27")
                                                        )
                                                        .fileId("string")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .name("x")
                                        .confirmedNoUsTaxId(true)
                                        .build()
                                )
                                .prongs(
                                    listOf(
                                        EntityCreateParams.Corporation.BeneficialOwner.Prong
                                            .OWNERSHIP
                                    )
                                )
                                .companyTitle("x")
                                .build()
                        )
                    )
                    .name("x")
                    .taxIdentifier("x")
                    .incorporationState("x")
                    .industryCode("x")
                    .website("string")
                    .build()
            )
            .description("x")
            .joint(
                EntityCreateParams.Joint.builder()
                    .individuals(
                        listOf(
                            EntityCreateParams.Joint.Individual.builder()
                                .address(
                                    EntityCreateParams.Joint.Individual.Address.builder()
                                        .city("x")
                                        .line1("x")
                                        .state("x")
                                        .zip("x")
                                        .line2("x")
                                        .build()
                                )
                                .dateOfBirth(LocalDate.parse("2019-12-27"))
                                .identification(
                                    EntityCreateParams.Joint.Individual.Identification.builder()
                                        .method(
                                            EntityCreateParams.Joint.Individual.Identification
                                                .Method
                                                .SOCIAL_SECURITY_NUMBER
                                        )
                                        .number("xxxx")
                                        .driversLicense(
                                            EntityCreateParams.Joint.Individual.Identification
                                                .DriversLicense
                                                .builder()
                                                .expirationDate(LocalDate.parse("2019-12-27"))
                                                .fileId("string")
                                                .state("x")
                                                .backFileId("string")
                                                .build()
                                        )
                                        .other(
                                            EntityCreateParams.Joint.Individual.Identification.Other
                                                .builder()
                                                .country("x")
                                                .description("x")
                                                .fileId("string")
                                                .backFileId("string")
                                                .expirationDate(LocalDate.parse("2019-12-27"))
                                                .build()
                                        )
                                        .passport(
                                            EntityCreateParams.Joint.Individual.Identification
                                                .Passport
                                                .builder()
                                                .country("x")
                                                .expirationDate(LocalDate.parse("2019-12-27"))
                                                .fileId("string")
                                                .build()
                                        )
                                        .build()
                                )
                                .name("x")
                                .confirmedNoUsTaxId(true)
                                .build()
                        )
                    )
                    .name("x")
                    .build()
            )
            .naturalPerson(
                EntityCreateParams.NaturalPerson.builder()
                    .address(
                        EntityCreateParams.NaturalPerson.Address.builder()
                            .city("x")
                            .line1("x")
                            .state("x")
                            .zip("x")
                            .line2("x")
                            .build()
                    )
                    .dateOfBirth(LocalDate.parse("2019-12-27"))
                    .identification(
                        EntityCreateParams.NaturalPerson.Identification.builder()
                            .method(
                                EntityCreateParams.NaturalPerson.Identification.Method
                                    .SOCIAL_SECURITY_NUMBER
                            )
                            .number("xxxx")
                            .driversLicense(
                                EntityCreateParams.NaturalPerson.Identification.DriversLicense
                                    .builder()
                                    .expirationDate(LocalDate.parse("2019-12-27"))
                                    .fileId("string")
                                    .state("x")
                                    .backFileId("string")
                                    .build()
                            )
                            .other(
                                EntityCreateParams.NaturalPerson.Identification.Other.builder()
                                    .country("x")
                                    .description("x")
                                    .fileId("string")
                                    .backFileId("string")
                                    .expirationDate(LocalDate.parse("2019-12-27"))
                                    .build()
                            )
                            .passport(
                                EntityCreateParams.NaturalPerson.Identification.Passport.builder()
                                    .country("x")
                                    .expirationDate(LocalDate.parse("2019-12-27"))
                                    .fileId("string")
                                    .build()
                            )
                            .build()
                    )
                    .name("x")
                    .confirmedNoUsTaxId(true)
                    .build()
            )
            .supplementalDocuments(
                listOf(EntityCreateParams.SupplementalDocument.builder().fileId("string").build())
            )
            .trust(
                EntityCreateParams.Trust.builder()
                    .address(
                        EntityCreateParams.Trust.Address.builder()
                            .city("x")
                            .line1("x")
                            .state("x")
                            .zip("x")
                            .line2("x")
                            .build()
                    )
                    .category(EntityCreateParams.Trust.Category.REVOCABLE)
                    .name("x")
                    .trustees(
                        listOf(
                            EntityCreateParams.Trust.Trustee.builder()
                                .structure(EntityCreateParams.Trust.Trustee.Structure.INDIVIDUAL)
                                .individual(
                                    EntityCreateParams.Trust.Trustee.Individual.builder()
                                        .address(
                                            EntityCreateParams.Trust.Trustee.Individual.Address
                                                .builder()
                                                .city("x")
                                                .line1("x")
                                                .state("x")
                                                .zip("x")
                                                .line2("x")
                                                .build()
                                        )
                                        .dateOfBirth(LocalDate.parse("2019-12-27"))
                                        .identification(
                                            EntityCreateParams.Trust.Trustee.Individual
                                                .Identification
                                                .builder()
                                                .method(
                                                    EntityCreateParams.Trust.Trustee.Individual
                                                        .Identification
                                                        .Method
                                                        .SOCIAL_SECURITY_NUMBER
                                                )
                                                .number("xxxx")
                                                .driversLicense(
                                                    EntityCreateParams.Trust.Trustee.Individual
                                                        .Identification
                                                        .DriversLicense
                                                        .builder()
                                                        .expirationDate(
                                                            LocalDate.parse("2019-12-27")
                                                        )
                                                        .fileId("string")
                                                        .state("x")
                                                        .backFileId("string")
                                                        .build()
                                                )
                                                .other(
                                                    EntityCreateParams.Trust.Trustee.Individual
                                                        .Identification
                                                        .Other
                                                        .builder()
                                                        .country("x")
                                                        .description("x")
                                                        .fileId("string")
                                                        .backFileId("string")
                                                        .expirationDate(
                                                            LocalDate.parse("2019-12-27")
                                                        )
                                                        .build()
                                                )
                                                .passport(
                                                    EntityCreateParams.Trust.Trustee.Individual
                                                        .Identification
                                                        .Passport
                                                        .builder()
                                                        .country("x")
                                                        .expirationDate(
                                                            LocalDate.parse("2019-12-27")
                                                        )
                                                        .fileId("string")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .name("x")
                                        .confirmedNoUsTaxId(true)
                                        .build()
                                )
                                .build()
                        )
                    )
                    .formationDocumentFileId("string")
                    .formationState("x")
                    .grantor(
                        EntityCreateParams.Trust.Grantor.builder()
                            .address(
                                EntityCreateParams.Trust.Grantor.Address.builder()
                                    .city("x")
                                    .line1("x")
                                    .state("x")
                                    .zip("x")
                                    .line2("x")
                                    .build()
                            )
                            .dateOfBirth(LocalDate.parse("2019-12-27"))
                            .identification(
                                EntityCreateParams.Trust.Grantor.Identification.builder()
                                    .method(
                                        EntityCreateParams.Trust.Grantor.Identification.Method
                                            .SOCIAL_SECURITY_NUMBER
                                    )
                                    .number("xxxx")
                                    .driversLicense(
                                        EntityCreateParams.Trust.Grantor.Identification
                                            .DriversLicense
                                            .builder()
                                            .expirationDate(LocalDate.parse("2019-12-27"))
                                            .fileId("string")
                                            .state("x")
                                            .backFileId("string")
                                            .build()
                                    )
                                    .other(
                                        EntityCreateParams.Trust.Grantor.Identification.Other
                                            .builder()
                                            .country("x")
                                            .description("x")
                                            .fileId("string")
                                            .backFileId("string")
                                            .expirationDate(LocalDate.parse("2019-12-27"))
                                            .build()
                                    )
                                    .passport(
                                        EntityCreateParams.Trust.Grantor.Identification.Passport
                                            .builder()
                                            .country("x")
                                            .expirationDate(LocalDate.parse("2019-12-27"))
                                            .fileId("string")
                                            .build()
                                    )
                                    .build()
                            )
                            .name("x")
                            .confirmedNoUsTaxId(true)
                            .build()
                    )
                    .taxIdentifier("x")
                    .build()
            )
            .build()
    }

    @Test
    fun getBody() {
        val params =
            EntityCreateParams.builder()
                .structure(EntityCreateParams.Structure.CORPORATION)
                .corporation(
                    EntityCreateParams.Corporation.builder()
                        .address(
                            EntityCreateParams.Corporation.Address.builder()
                                .city("x")
                                .line1("x")
                                .state("x")
                                .zip("x")
                                .line2("x")
                                .build()
                        )
                        .beneficialOwners(
                            listOf(
                                EntityCreateParams.Corporation.BeneficialOwner.builder()
                                    .individual(
                                        EntityCreateParams.Corporation.BeneficialOwner.Individual
                                            .builder()
                                            .address(
                                                EntityCreateParams.Corporation.BeneficialOwner
                                                    .Individual
                                                    .Address
                                                    .builder()
                                                    .city("x")
                                                    .line1("x")
                                                    .state("x")
                                                    .zip("x")
                                                    .line2("x")
                                                    .build()
                                            )
                                            .dateOfBirth(LocalDate.parse("2019-12-27"))
                                            .identification(
                                                EntityCreateParams.Corporation.BeneficialOwner
                                                    .Individual
                                                    .Identification
                                                    .builder()
                                                    .method(
                                                        EntityCreateParams.Corporation
                                                            .BeneficialOwner
                                                            .Individual
                                                            .Identification
                                                            .Method
                                                            .SOCIAL_SECURITY_NUMBER
                                                    )
                                                    .number("xxxx")
                                                    .driversLicense(
                                                        EntityCreateParams.Corporation
                                                            .BeneficialOwner
                                                            .Individual
                                                            .Identification
                                                            .DriversLicense
                                                            .builder()
                                                            .expirationDate(
                                                                LocalDate.parse("2019-12-27")
                                                            )
                                                            .fileId("string")
                                                            .state("x")
                                                            .backFileId("string")
                                                            .build()
                                                    )
                                                    .other(
                                                        EntityCreateParams.Corporation
                                                            .BeneficialOwner
                                                            .Individual
                                                            .Identification
                                                            .Other
                                                            .builder()
                                                            .country("x")
                                                            .description("x")
                                                            .fileId("string")
                                                            .backFileId("string")
                                                            .expirationDate(
                                                                LocalDate.parse("2019-12-27")
                                                            )
                                                            .build()
                                                    )
                                                    .passport(
                                                        EntityCreateParams.Corporation
                                                            .BeneficialOwner
                                                            .Individual
                                                            .Identification
                                                            .Passport
                                                            .builder()
                                                            .country("x")
                                                            .expirationDate(
                                                                LocalDate.parse("2019-12-27")
                                                            )
                                                            .fileId("string")
                                                            .build()
                                                    )
                                                    .build()
                                            )
                                            .name("x")
                                            .confirmedNoUsTaxId(true)
                                            .build()
                                    )
                                    .prongs(
                                        listOf(
                                            EntityCreateParams.Corporation.BeneficialOwner.Prong
                                                .OWNERSHIP
                                        )
                                    )
                                    .companyTitle("x")
                                    .build()
                            )
                        )
                        .name("x")
                        .taxIdentifier("x")
                        .incorporationState("x")
                        .industryCode("x")
                        .website("string")
                        .build()
                )
                .description("x")
                .joint(
                    EntityCreateParams.Joint.builder()
                        .individuals(
                            listOf(
                                EntityCreateParams.Joint.Individual.builder()
                                    .address(
                                        EntityCreateParams.Joint.Individual.Address.builder()
                                            .city("x")
                                            .line1("x")
                                            .state("x")
                                            .zip("x")
                                            .line2("x")
                                            .build()
                                    )
                                    .dateOfBirth(LocalDate.parse("2019-12-27"))
                                    .identification(
                                        EntityCreateParams.Joint.Individual.Identification.builder()
                                            .method(
                                                EntityCreateParams.Joint.Individual.Identification
                                                    .Method
                                                    .SOCIAL_SECURITY_NUMBER
                                            )
                                            .number("xxxx")
                                            .driversLicense(
                                                EntityCreateParams.Joint.Individual.Identification
                                                    .DriversLicense
                                                    .builder()
                                                    .expirationDate(LocalDate.parse("2019-12-27"))
                                                    .fileId("string")
                                                    .state("x")
                                                    .backFileId("string")
                                                    .build()
                                            )
                                            .other(
                                                EntityCreateParams.Joint.Individual.Identification
                                                    .Other
                                                    .builder()
                                                    .country("x")
                                                    .description("x")
                                                    .fileId("string")
                                                    .backFileId("string")
                                                    .expirationDate(LocalDate.parse("2019-12-27"))
                                                    .build()
                                            )
                                            .passport(
                                                EntityCreateParams.Joint.Individual.Identification
                                                    .Passport
                                                    .builder()
                                                    .country("x")
                                                    .expirationDate(LocalDate.parse("2019-12-27"))
                                                    .fileId("string")
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .name("x")
                                    .confirmedNoUsTaxId(true)
                                    .build()
                            )
                        )
                        .name("x")
                        .build()
                )
                .naturalPerson(
                    EntityCreateParams.NaturalPerson.builder()
                        .address(
                            EntityCreateParams.NaturalPerson.Address.builder()
                                .city("x")
                                .line1("x")
                                .state("x")
                                .zip("x")
                                .line2("x")
                                .build()
                        )
                        .dateOfBirth(LocalDate.parse("2019-12-27"))
                        .identification(
                            EntityCreateParams.NaturalPerson.Identification.builder()
                                .method(
                                    EntityCreateParams.NaturalPerson.Identification.Method
                                        .SOCIAL_SECURITY_NUMBER
                                )
                                .number("xxxx")
                                .driversLicense(
                                    EntityCreateParams.NaturalPerson.Identification.DriversLicense
                                        .builder()
                                        .expirationDate(LocalDate.parse("2019-12-27"))
                                        .fileId("string")
                                        .state("x")
                                        .backFileId("string")
                                        .build()
                                )
                                .other(
                                    EntityCreateParams.NaturalPerson.Identification.Other.builder()
                                        .country("x")
                                        .description("x")
                                        .fileId("string")
                                        .backFileId("string")
                                        .expirationDate(LocalDate.parse("2019-12-27"))
                                        .build()
                                )
                                .passport(
                                    EntityCreateParams.NaturalPerson.Identification.Passport
                                        .builder()
                                        .country("x")
                                        .expirationDate(LocalDate.parse("2019-12-27"))
                                        .fileId("string")
                                        .build()
                                )
                                .build()
                        )
                        .name("x")
                        .confirmedNoUsTaxId(true)
                        .build()
                )
                .supplementalDocuments(
                    listOf(
                        EntityCreateParams.SupplementalDocument.builder().fileId("string").build()
                    )
                )
                .trust(
                    EntityCreateParams.Trust.builder()
                        .address(
                            EntityCreateParams.Trust.Address.builder()
                                .city("x")
                                .line1("x")
                                .state("x")
                                .zip("x")
                                .line2("x")
                                .build()
                        )
                        .category(EntityCreateParams.Trust.Category.REVOCABLE)
                        .name("x")
                        .trustees(
                            listOf(
                                EntityCreateParams.Trust.Trustee.builder()
                                    .structure(
                                        EntityCreateParams.Trust.Trustee.Structure.INDIVIDUAL
                                    )
                                    .individual(
                                        EntityCreateParams.Trust.Trustee.Individual.builder()
                                            .address(
                                                EntityCreateParams.Trust.Trustee.Individual.Address
                                                    .builder()
                                                    .city("x")
                                                    .line1("x")
                                                    .state("x")
                                                    .zip("x")
                                                    .line2("x")
                                                    .build()
                                            )
                                            .dateOfBirth(LocalDate.parse("2019-12-27"))
                                            .identification(
                                                EntityCreateParams.Trust.Trustee.Individual
                                                    .Identification
                                                    .builder()
                                                    .method(
                                                        EntityCreateParams.Trust.Trustee.Individual
                                                            .Identification
                                                            .Method
                                                            .SOCIAL_SECURITY_NUMBER
                                                    )
                                                    .number("xxxx")
                                                    .driversLicense(
                                                        EntityCreateParams.Trust.Trustee.Individual
                                                            .Identification
                                                            .DriversLicense
                                                            .builder()
                                                            .expirationDate(
                                                                LocalDate.parse("2019-12-27")
                                                            )
                                                            .fileId("string")
                                                            .state("x")
                                                            .backFileId("string")
                                                            .build()
                                                    )
                                                    .other(
                                                        EntityCreateParams.Trust.Trustee.Individual
                                                            .Identification
                                                            .Other
                                                            .builder()
                                                            .country("x")
                                                            .description("x")
                                                            .fileId("string")
                                                            .backFileId("string")
                                                            .expirationDate(
                                                                LocalDate.parse("2019-12-27")
                                                            )
                                                            .build()
                                                    )
                                                    .passport(
                                                        EntityCreateParams.Trust.Trustee.Individual
                                                            .Identification
                                                            .Passport
                                                            .builder()
                                                            .country("x")
                                                            .expirationDate(
                                                                LocalDate.parse("2019-12-27")
                                                            )
                                                            .fileId("string")
                                                            .build()
                                                    )
                                                    .build()
                                            )
                                            .name("x")
                                            .confirmedNoUsTaxId(true)
                                            .build()
                                    )
                                    .build()
                            )
                        )
                        .formationDocumentFileId("string")
                        .formationState("x")
                        .grantor(
                            EntityCreateParams.Trust.Grantor.builder()
                                .address(
                                    EntityCreateParams.Trust.Grantor.Address.builder()
                                        .city("x")
                                        .line1("x")
                                        .state("x")
                                        .zip("x")
                                        .line2("x")
                                        .build()
                                )
                                .dateOfBirth(LocalDate.parse("2019-12-27"))
                                .identification(
                                    EntityCreateParams.Trust.Grantor.Identification.builder()
                                        .method(
                                            EntityCreateParams.Trust.Grantor.Identification.Method
                                                .SOCIAL_SECURITY_NUMBER
                                        )
                                        .number("xxxx")
                                        .driversLicense(
                                            EntityCreateParams.Trust.Grantor.Identification
                                                .DriversLicense
                                                .builder()
                                                .expirationDate(LocalDate.parse("2019-12-27"))
                                                .fileId("string")
                                                .state("x")
                                                .backFileId("string")
                                                .build()
                                        )
                                        .other(
                                            EntityCreateParams.Trust.Grantor.Identification.Other
                                                .builder()
                                                .country("x")
                                                .description("x")
                                                .fileId("string")
                                                .backFileId("string")
                                                .expirationDate(LocalDate.parse("2019-12-27"))
                                                .build()
                                        )
                                        .passport(
                                            EntityCreateParams.Trust.Grantor.Identification.Passport
                                                .builder()
                                                .country("x")
                                                .expirationDate(LocalDate.parse("2019-12-27"))
                                                .fileId("string")
                                                .build()
                                        )
                                        .build()
                                )
                                .name("x")
                                .confirmedNoUsTaxId(true)
                                .build()
                        )
                        .taxIdentifier("x")
                        .build()
                )
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.structure()).isEqualTo(EntityCreateParams.Structure.CORPORATION)
        assertThat(body.corporation())
            .isEqualTo(
                EntityCreateParams.Corporation.builder()
                    .address(
                        EntityCreateParams.Corporation.Address.builder()
                            .city("x")
                            .line1("x")
                            .state("x")
                            .zip("x")
                            .line2("x")
                            .build()
                    )
                    .beneficialOwners(
                        listOf(
                            EntityCreateParams.Corporation.BeneficialOwner.builder()
                                .individual(
                                    EntityCreateParams.Corporation.BeneficialOwner.Individual
                                        .builder()
                                        .address(
                                            EntityCreateParams.Corporation.BeneficialOwner
                                                .Individual
                                                .Address
                                                .builder()
                                                .city("x")
                                                .line1("x")
                                                .state("x")
                                                .zip("x")
                                                .line2("x")
                                                .build()
                                        )
                                        .dateOfBirth(LocalDate.parse("2019-12-27"))
                                        .identification(
                                            EntityCreateParams.Corporation.BeneficialOwner
                                                .Individual
                                                .Identification
                                                .builder()
                                                .method(
                                                    EntityCreateParams.Corporation.BeneficialOwner
                                                        .Individual
                                                        .Identification
                                                        .Method
                                                        .SOCIAL_SECURITY_NUMBER
                                                )
                                                .number("xxxx")
                                                .driversLicense(
                                                    EntityCreateParams.Corporation.BeneficialOwner
                                                        .Individual
                                                        .Identification
                                                        .DriversLicense
                                                        .builder()
                                                        .expirationDate(
                                                            LocalDate.parse("2019-12-27")
                                                        )
                                                        .fileId("string")
                                                        .state("x")
                                                        .backFileId("string")
                                                        .build()
                                                )
                                                .other(
                                                    EntityCreateParams.Corporation.BeneficialOwner
                                                        .Individual
                                                        .Identification
                                                        .Other
                                                        .builder()
                                                        .country("x")
                                                        .description("x")
                                                        .fileId("string")
                                                        .backFileId("string")
                                                        .expirationDate(
                                                            LocalDate.parse("2019-12-27")
                                                        )
                                                        .build()
                                                )
                                                .passport(
                                                    EntityCreateParams.Corporation.BeneficialOwner
                                                        .Individual
                                                        .Identification
                                                        .Passport
                                                        .builder()
                                                        .country("x")
                                                        .expirationDate(
                                                            LocalDate.parse("2019-12-27")
                                                        )
                                                        .fileId("string")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .name("x")
                                        .confirmedNoUsTaxId(true)
                                        .build()
                                )
                                .prongs(
                                    listOf(
                                        EntityCreateParams.Corporation.BeneficialOwner.Prong
                                            .OWNERSHIP
                                    )
                                )
                                .companyTitle("x")
                                .build()
                        )
                    )
                    .name("x")
                    .taxIdentifier("x")
                    .incorporationState("x")
                    .industryCode("x")
                    .website("string")
                    .build()
            )
        assertThat(body.description()).isEqualTo("x")
        assertThat(body.joint())
            .isEqualTo(
                EntityCreateParams.Joint.builder()
                    .individuals(
                        listOf(
                            EntityCreateParams.Joint.Individual.builder()
                                .address(
                                    EntityCreateParams.Joint.Individual.Address.builder()
                                        .city("x")
                                        .line1("x")
                                        .state("x")
                                        .zip("x")
                                        .line2("x")
                                        .build()
                                )
                                .dateOfBirth(LocalDate.parse("2019-12-27"))
                                .identification(
                                    EntityCreateParams.Joint.Individual.Identification.builder()
                                        .method(
                                            EntityCreateParams.Joint.Individual.Identification
                                                .Method
                                                .SOCIAL_SECURITY_NUMBER
                                        )
                                        .number("xxxx")
                                        .driversLicense(
                                            EntityCreateParams.Joint.Individual.Identification
                                                .DriversLicense
                                                .builder()
                                                .expirationDate(LocalDate.parse("2019-12-27"))
                                                .fileId("string")
                                                .state("x")
                                                .backFileId("string")
                                                .build()
                                        )
                                        .other(
                                            EntityCreateParams.Joint.Individual.Identification.Other
                                                .builder()
                                                .country("x")
                                                .description("x")
                                                .fileId("string")
                                                .backFileId("string")
                                                .expirationDate(LocalDate.parse("2019-12-27"))
                                                .build()
                                        )
                                        .passport(
                                            EntityCreateParams.Joint.Individual.Identification
                                                .Passport
                                                .builder()
                                                .country("x")
                                                .expirationDate(LocalDate.parse("2019-12-27"))
                                                .fileId("string")
                                                .build()
                                        )
                                        .build()
                                )
                                .name("x")
                                .confirmedNoUsTaxId(true)
                                .build()
                        )
                    )
                    .name("x")
                    .build()
            )
        assertThat(body.naturalPerson())
            .isEqualTo(
                EntityCreateParams.NaturalPerson.builder()
                    .address(
                        EntityCreateParams.NaturalPerson.Address.builder()
                            .city("x")
                            .line1("x")
                            .state("x")
                            .zip("x")
                            .line2("x")
                            .build()
                    )
                    .dateOfBirth(LocalDate.parse("2019-12-27"))
                    .identification(
                        EntityCreateParams.NaturalPerson.Identification.builder()
                            .method(
                                EntityCreateParams.NaturalPerson.Identification.Method
                                    .SOCIAL_SECURITY_NUMBER
                            )
                            .number("xxxx")
                            .driversLicense(
                                EntityCreateParams.NaturalPerson.Identification.DriversLicense
                                    .builder()
                                    .expirationDate(LocalDate.parse("2019-12-27"))
                                    .fileId("string")
                                    .state("x")
                                    .backFileId("string")
                                    .build()
                            )
                            .other(
                                EntityCreateParams.NaturalPerson.Identification.Other.builder()
                                    .country("x")
                                    .description("x")
                                    .fileId("string")
                                    .backFileId("string")
                                    .expirationDate(LocalDate.parse("2019-12-27"))
                                    .build()
                            )
                            .passport(
                                EntityCreateParams.NaturalPerson.Identification.Passport.builder()
                                    .country("x")
                                    .expirationDate(LocalDate.parse("2019-12-27"))
                                    .fileId("string")
                                    .build()
                            )
                            .build()
                    )
                    .name("x")
                    .confirmedNoUsTaxId(true)
                    .build()
            )
        assertThat(body.supplementalDocuments())
            .isEqualTo(
                listOf(EntityCreateParams.SupplementalDocument.builder().fileId("string").build())
            )
        assertThat(body.trust())
            .isEqualTo(
                EntityCreateParams.Trust.builder()
                    .address(
                        EntityCreateParams.Trust.Address.builder()
                            .city("x")
                            .line1("x")
                            .state("x")
                            .zip("x")
                            .line2("x")
                            .build()
                    )
                    .category(EntityCreateParams.Trust.Category.REVOCABLE)
                    .name("x")
                    .trustees(
                        listOf(
                            EntityCreateParams.Trust.Trustee.builder()
                                .structure(EntityCreateParams.Trust.Trustee.Structure.INDIVIDUAL)
                                .individual(
                                    EntityCreateParams.Trust.Trustee.Individual.builder()
                                        .address(
                                            EntityCreateParams.Trust.Trustee.Individual.Address
                                                .builder()
                                                .city("x")
                                                .line1("x")
                                                .state("x")
                                                .zip("x")
                                                .line2("x")
                                                .build()
                                        )
                                        .dateOfBirth(LocalDate.parse("2019-12-27"))
                                        .identification(
                                            EntityCreateParams.Trust.Trustee.Individual
                                                .Identification
                                                .builder()
                                                .method(
                                                    EntityCreateParams.Trust.Trustee.Individual
                                                        .Identification
                                                        .Method
                                                        .SOCIAL_SECURITY_NUMBER
                                                )
                                                .number("xxxx")
                                                .driversLicense(
                                                    EntityCreateParams.Trust.Trustee.Individual
                                                        .Identification
                                                        .DriversLicense
                                                        .builder()
                                                        .expirationDate(
                                                            LocalDate.parse("2019-12-27")
                                                        )
                                                        .fileId("string")
                                                        .state("x")
                                                        .backFileId("string")
                                                        .build()
                                                )
                                                .other(
                                                    EntityCreateParams.Trust.Trustee.Individual
                                                        .Identification
                                                        .Other
                                                        .builder()
                                                        .country("x")
                                                        .description("x")
                                                        .fileId("string")
                                                        .backFileId("string")
                                                        .expirationDate(
                                                            LocalDate.parse("2019-12-27")
                                                        )
                                                        .build()
                                                )
                                                .passport(
                                                    EntityCreateParams.Trust.Trustee.Individual
                                                        .Identification
                                                        .Passport
                                                        .builder()
                                                        .country("x")
                                                        .expirationDate(
                                                            LocalDate.parse("2019-12-27")
                                                        )
                                                        .fileId("string")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .name("x")
                                        .confirmedNoUsTaxId(true)
                                        .build()
                                )
                                .build()
                        )
                    )
                    .formationDocumentFileId("string")
                    .formationState("x")
                    .grantor(
                        EntityCreateParams.Trust.Grantor.builder()
                            .address(
                                EntityCreateParams.Trust.Grantor.Address.builder()
                                    .city("x")
                                    .line1("x")
                                    .state("x")
                                    .zip("x")
                                    .line2("x")
                                    .build()
                            )
                            .dateOfBirth(LocalDate.parse("2019-12-27"))
                            .identification(
                                EntityCreateParams.Trust.Grantor.Identification.builder()
                                    .method(
                                        EntityCreateParams.Trust.Grantor.Identification.Method
                                            .SOCIAL_SECURITY_NUMBER
                                    )
                                    .number("xxxx")
                                    .driversLicense(
                                        EntityCreateParams.Trust.Grantor.Identification
                                            .DriversLicense
                                            .builder()
                                            .expirationDate(LocalDate.parse("2019-12-27"))
                                            .fileId("string")
                                            .state("x")
                                            .backFileId("string")
                                            .build()
                                    )
                                    .other(
                                        EntityCreateParams.Trust.Grantor.Identification.Other
                                            .builder()
                                            .country("x")
                                            .description("x")
                                            .fileId("string")
                                            .backFileId("string")
                                            .expirationDate(LocalDate.parse("2019-12-27"))
                                            .build()
                                    )
                                    .passport(
                                        EntityCreateParams.Trust.Grantor.Identification.Passport
                                            .builder()
                                            .country("x")
                                            .expirationDate(LocalDate.parse("2019-12-27"))
                                            .fileId("string")
                                            .build()
                                    )
                                    .build()
                            )
                            .name("x")
                            .confirmedNoUsTaxId(true)
                            .build()
                    )
                    .taxIdentifier("x")
                    .build()
            )
    }

    @Test
    fun getBodyWithoutOptionalFields() {
        val params =
            EntityCreateParams.builder().structure(EntityCreateParams.Structure.CORPORATION).build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.structure()).isEqualTo(EntityCreateParams.Structure.CORPORATION)
    }
}
