package com.increase.api.models

import java.time.LocalDate
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class InterestPaymentSimulationResultTest {

    @Test
    fun createInterestPaymentSimulationResult() {
        val interestPaymentSimulationResult =
            InterestPaymentSimulationResult.builder()
                .transaction(
                    InterestPaymentSimulationResult.Transaction.builder()
                        .id("string")
                        .accountId("string")
                        .amount(123L)
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .currency(InterestPaymentSimulationResult.Transaction.Currency.CAD)
                        .description("string")
                        .routeId("string")
                        .routeType(
                            InterestPaymentSimulationResult.Transaction.RouteType.ACCOUNT_NUMBER
                        )
                        .source(
                            InterestPaymentSimulationResult.Transaction.Source.builder()
                                .accountTransferIntention(
                                    InterestPaymentSimulationResult.Transaction.Source
                                        .AccountTransferIntention
                                        .builder()
                                        .amount(123L)
                                        .currency(
                                            InterestPaymentSimulationResult.Transaction.Source
                                                .AccountTransferIntention
                                                .Currency
                                                .CAD
                                        )
                                        .description("string")
                                        .destinationAccountId("string")
                                        .sourceAccountId("string")
                                        .transferId("string")
                                        .build()
                                )
                                .achTransferIntention(
                                    InterestPaymentSimulationResult.Transaction.Source
                                        .AchTransferIntention
                                        .builder()
                                        .accountNumber("string")
                                        .amount(123L)
                                        .routingNumber("string")
                                        .statementDescriptor("string")
                                        .transferId("string")
                                        .build()
                                )
                                .achTransferRejection(
                                    InterestPaymentSimulationResult.Transaction.Source
                                        .AchTransferRejection
                                        .builder()
                                        .transferId("string")
                                        .build()
                                )
                                .achTransferReturn(
                                    InterestPaymentSimulationResult.Transaction.Source
                                        .AchTransferReturn
                                        .builder()
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .rawReturnReasonCode("string")
                                        .returnReasonCode(
                                            InterestPaymentSimulationResult.Transaction.Source
                                                .AchTransferReturn
                                                .ReturnReasonCode
                                                .INSUFFICIENT_FUND
                                        )
                                        .transactionId("string")
                                        .transferId("string")
                                        .build()
                                )
                                .cardDisputeAcceptance(
                                    InterestPaymentSimulationResult.Transaction.Source
                                        .CardDisputeAcceptance
                                        .builder()
                                        .acceptedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .cardDisputeId("string")
                                        .transactionId("string")
                                        .build()
                                )
                                .cardRefund(
                                    InterestPaymentSimulationResult.Transaction.Source.CardRefund
                                        .builder()
                                        .id("string")
                                        .amount(123L)
                                        .currency(
                                            InterestPaymentSimulationResult.Transaction.Source
                                                .CardRefund
                                                .Currency
                                                .CAD
                                        )
                                        .merchantAcceptorId("string")
                                        .merchantCategoryCode("string")
                                        .merchantCity("string")
                                        .merchantCountry("string")
                                        .merchantName("string")
                                        .merchantState("string")
                                        .transactionId("string")
                                        .type(
                                            InterestPaymentSimulationResult.Transaction.Source
                                                .CardRefund
                                                .Type
                                                .CARD_REFUND
                                        )
                                        .build()
                                )
                                .cardRevenuePayment(
                                    InterestPaymentSimulationResult.Transaction.Source
                                        .CardRevenuePayment
                                        .builder()
                                        .amount(123L)
                                        .currency(
                                            InterestPaymentSimulationResult.Transaction.Source
                                                .CardRevenuePayment
                                                .Currency
                                                .CAD
                                        )
                                        .periodEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .periodStart(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .transactedOnAccountId("string")
                                        .build()
                                )
                                .cardSettlement(
                                    InterestPaymentSimulationResult.Transaction.Source
                                        .CardSettlement
                                        .builder()
                                        .id("string")
                                        .amount(123L)
                                        .cardAuthorization("string")
                                        .currency(
                                            InterestPaymentSimulationResult.Transaction.Source
                                                .CardSettlement
                                                .Currency
                                                .CAD
                                        )
                                        .merchantAcceptorId("string")
                                        .merchantCategoryCode("string")
                                        .merchantCity("string")
                                        .merchantCountry("string")
                                        .merchantName("string")
                                        .merchantState("string")
                                        .pendingTransactionId("string")
                                        .presentmentAmount(123L)
                                        .presentmentCurrency("string")
                                        .transactionId("string")
                                        .type(
                                            InterestPaymentSimulationResult.Transaction.Source
                                                .CardSettlement
                                                .Type
                                                .CARD_SETTLEMENT
                                        )
                                        .build()
                                )
                                .category(
                                    InterestPaymentSimulationResult.Transaction.Source.Category
                                        .ACCOUNT_TRANSFER_INTENTION
                                )
                                .checkDepositAcceptance(
                                    InterestPaymentSimulationResult.Transaction.Source
                                        .CheckDepositAcceptance
                                        .builder()
                                        .accountNumber("string")
                                        .amount(123L)
                                        .auxiliaryOnUs("string")
                                        .checkDepositId("string")
                                        .currency(
                                            InterestPaymentSimulationResult.Transaction.Source
                                                .CheckDepositAcceptance
                                                .Currency
                                                .CAD
                                        )
                                        .routingNumber("string")
                                        .serialNumber("string")
                                        .build()
                                )
                                .checkDepositReturn(
                                    InterestPaymentSimulationResult.Transaction.Source
                                        .CheckDepositReturn
                                        .builder()
                                        .amount(123L)
                                        .checkDepositId("string")
                                        .currency(
                                            InterestPaymentSimulationResult.Transaction.Source
                                                .CheckDepositReturn
                                                .Currency
                                                .CAD
                                        )
                                        .returnReason(
                                            InterestPaymentSimulationResult.Transaction.Source
                                                .CheckDepositReturn
                                                .ReturnReason
                                                .ACH_CONVERSION_NOT_SUPPORTED
                                        )
                                        .returnedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .transactionId("string")
                                        .build()
                                )
                                .checkTransferDeposit(
                                    InterestPaymentSimulationResult.Transaction.Source
                                        .CheckTransferDeposit
                                        .builder()
                                        .backImageFileId("string")
                                        .depositedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .frontImageFileId("string")
                                        .transactionId("string")
                                        .type(
                                            InterestPaymentSimulationResult.Transaction.Source
                                                .CheckTransferDeposit
                                                .Type
                                                .CHECK_TRANSFER_DEPOSIT
                                        )
                                        .build()
                                )
                                .checkTransferIntention(
                                    InterestPaymentSimulationResult.Transaction.Source
                                        .CheckTransferIntention
                                        .builder()
                                        .addressCity("string")
                                        .addressLine1("string")
                                        .addressLine2("string")
                                        .addressState("string")
                                        .addressZip("string")
                                        .amount(123L)
                                        .currency(
                                            InterestPaymentSimulationResult.Transaction.Source
                                                .CheckTransferIntention
                                                .Currency
                                                .CAD
                                        )
                                        .recipientName("string")
                                        .transferId("string")
                                        .build()
                                )
                                .checkTransferRejection(
                                    InterestPaymentSimulationResult.Transaction.Source
                                        .CheckTransferRejection
                                        .builder()
                                        .transferId("string")
                                        .build()
                                )
                                .checkTransferStopPaymentRequest(
                                    InterestPaymentSimulationResult.Transaction.Source
                                        .CheckTransferStopPaymentRequest
                                        .builder()
                                        .reason(
                                            InterestPaymentSimulationResult.Transaction.Source
                                                .CheckTransferStopPaymentRequest
                                                .Reason
                                                .MAIL_DELIVERY_FAILED
                                        )
                                        .requestedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .transferId("string")
                                        .type(
                                            InterestPaymentSimulationResult.Transaction.Source
                                                .CheckTransferStopPaymentRequest
                                                .Type
                                                .CHECK_TRANSFER_STOP_PAYMENT_REQUEST
                                        )
                                        .build()
                                )
                                .feePayment(
                                    InterestPaymentSimulationResult.Transaction.Source.FeePayment
                                        .builder()
                                        .amount(123L)
                                        .currency(
                                            InterestPaymentSimulationResult.Transaction.Source
                                                .FeePayment
                                                .Currency
                                                .CAD
                                        )
                                        .feePeriodStart(LocalDate.parse("2019-12-27"))
                                        .build()
                                )
                                .inboundAchTransfer(
                                    InterestPaymentSimulationResult.Transaction.Source
                                        .InboundAchTransfer
                                        .builder()
                                        .amount(123L)
                                        .originatorCompanyDescriptiveDate("string")
                                        .originatorCompanyDiscretionaryData("string")
                                        .originatorCompanyEntryDescription("string")
                                        .originatorCompanyId("string")
                                        .originatorCompanyName("string")
                                        .receiverIdNumber("string")
                                        .receiverName("string")
                                        .traceNumber("string")
                                        .build()
                                )
                                .inboundCheck(
                                    InterestPaymentSimulationResult.Transaction.Source.InboundCheck
                                        .builder()
                                        .amount(123L)
                                        .checkFrontImageFileId("string")
                                        .checkNumber("string")
                                        .checkRearImageFileId("string")
                                        .currency(
                                            InterestPaymentSimulationResult.Transaction.Source
                                                .InboundCheck
                                                .Currency
                                                .CAD
                                        )
                                        .build()
                                )
                                .inboundInternationalAchTransfer(
                                    InterestPaymentSimulationResult.Transaction.Source
                                        .InboundInternationalAchTransfer
                                        .builder()
                                        .amount(123L)
                                        .destinationCountryCode("string")
                                        .destinationCurrencyCode("string")
                                        .foreignExchangeIndicator("string")
                                        .foreignExchangeReference("string")
                                        .foreignExchangeReferenceIndicator("string")
                                        .foreignPaymentAmount(123L)
                                        .foreignTraceNumber("string")
                                        .internationalTransactionTypeCode("string")
                                        .originatingCurrencyCode("string")
                                        .originatingDepositoryFinancialInstitutionBranchCountry(
                                            "string"
                                        )
                                        .originatingDepositoryFinancialInstitutionId("string")
                                        .originatingDepositoryFinancialInstitutionIdQualifier(
                                            "string"
                                        )
                                        .originatingDepositoryFinancialInstitutionName("string")
                                        .originatorCity("string")
                                        .originatorCompanyEntryDescription("string")
                                        .originatorCountry("string")
                                        .originatorIdentification("string")
                                        .originatorName("string")
                                        .originatorPostalCode("string")
                                        .originatorStateOrProvince("string")
                                        .originatorStreetAddress("string")
                                        .paymentRelatedInformation("string")
                                        .paymentRelatedInformation2("string")
                                        .receiverCity("string")
                                        .receiverCountry("string")
                                        .receiverIdentificationNumber("string")
                                        .receiverPostalCode("string")
                                        .receiverStateOrProvince("string")
                                        .receiverStreetAddress("string")
                                        .receivingCompanyOrIndividualName("string")
                                        .receivingDepositoryFinancialInstitutionCountry("string")
                                        .receivingDepositoryFinancialInstitutionId("string")
                                        .receivingDepositoryFinancialInstitutionIdQualifier(
                                            "string"
                                        )
                                        .receivingDepositoryFinancialInstitutionName("string")
                                        .traceNumber("string")
                                        .build()
                                )
                                .inboundRealTimePaymentsTransferConfirmation(
                                    InterestPaymentSimulationResult.Transaction.Source
                                        .InboundRealTimePaymentsTransferConfirmation
                                        .builder()
                                        .amount(123L)
                                        .creditorName("string")
                                        .currency(
                                            InterestPaymentSimulationResult.Transaction.Source
                                                .InboundRealTimePaymentsTransferConfirmation
                                                .Currency
                                                .CAD
                                        )
                                        .debtorAccountNumber("string")
                                        .debtorName("string")
                                        .debtorRoutingNumber("string")
                                        .remittanceInformation("string")
                                        .transactionIdentification("string")
                                        .build()
                                )
                                .inboundWireDrawdownPayment(
                                    InterestPaymentSimulationResult.Transaction.Source
                                        .InboundWireDrawdownPayment
                                        .builder()
                                        .amount(123L)
                                        .beneficiaryAddressLine1("string")
                                        .beneficiaryAddressLine2("string")
                                        .beneficiaryAddressLine3("string")
                                        .beneficiaryName("string")
                                        .beneficiaryReference("string")
                                        .description("string")
                                        .inputMessageAccountabilityData("string")
                                        .originatorAddressLine1("string")
                                        .originatorAddressLine2("string")
                                        .originatorAddressLine3("string")
                                        .originatorName("string")
                                        .originatorToBeneficiaryInformation("string")
                                        .build()
                                )
                                .inboundWireDrawdownPaymentReversal(
                                    InterestPaymentSimulationResult.Transaction.Source
                                        .InboundWireDrawdownPaymentReversal
                                        .builder()
                                        .amount(123L)
                                        .description("string")
                                        .inputCycleDate(LocalDate.parse("2019-12-27"))
                                        .inputMessageAccountabilityData("string")
                                        .inputSequenceNumber("string")
                                        .inputSource("string")
                                        .previousMessageInputCycleDate(
                                            LocalDate.parse("2019-12-27")
                                        )
                                        .previousMessageInputMessageAccountabilityData("string")
                                        .previousMessageInputSequenceNumber("string")
                                        .previousMessageInputSource("string")
                                        .build()
                                )
                                .inboundWireReversal(
                                    InterestPaymentSimulationResult.Transaction.Source
                                        .InboundWireReversal
                                        .builder()
                                        .amount(123L)
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .description("string")
                                        .financialInstitutionToFinancialInstitutionInformation(
                                            "string"
                                        )
                                        .inputCycleDate(LocalDate.parse("2019-12-27"))
                                        .inputMessageAccountabilityData("string")
                                        .inputSequenceNumber("string")
                                        .inputSource("string")
                                        .previousMessageInputCycleDate(
                                            LocalDate.parse("2019-12-27")
                                        )
                                        .previousMessageInputMessageAccountabilityData("string")
                                        .previousMessageInputSequenceNumber("string")
                                        .previousMessageInputSource("string")
                                        .receiverFinancialInstitutionInformation("string")
                                        .transactionId("string")
                                        .wireTransferId("string")
                                        .build()
                                )
                                .inboundWireTransfer(
                                    InterestPaymentSimulationResult.Transaction.Source
                                        .InboundWireTransfer
                                        .builder()
                                        .amount(123L)
                                        .beneficiaryAddressLine1("string")
                                        .beneficiaryAddressLine2("string")
                                        .beneficiaryAddressLine3("string")
                                        .beneficiaryName("string")
                                        .beneficiaryReference("string")
                                        .description("string")
                                        .inputMessageAccountabilityData("string")
                                        .originatorAddressLine1("string")
                                        .originatorAddressLine2("string")
                                        .originatorAddressLine3("string")
                                        .originatorName("string")
                                        .originatorToBeneficiaryInformation("string")
                                        .originatorToBeneficiaryInformationLine1("string")
                                        .originatorToBeneficiaryInformationLine2("string")
                                        .originatorToBeneficiaryInformationLine3("string")
                                        .originatorToBeneficiaryInformationLine4("string")
                                        .build()
                                )
                                .interestPayment(
                                    InterestPaymentSimulationResult.Transaction.Source
                                        .InterestPayment
                                        .builder()
                                        .accruedOnAccountId("string")
                                        .amount(123L)
                                        .currency(
                                            InterestPaymentSimulationResult.Transaction.Source
                                                .InterestPayment
                                                .Currency
                                                .CAD
                                        )
                                        .periodEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .periodStart(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .build()
                                )
                                .internalSource(
                                    InterestPaymentSimulationResult.Transaction.Source
                                        .InternalSource
                                        .builder()
                                        .amount(123L)
                                        .currency(
                                            InterestPaymentSimulationResult.Transaction.Source
                                                .InternalSource
                                                .Currency
                                                .CAD
                                        )
                                        .reason(
                                            InterestPaymentSimulationResult.Transaction.Source
                                                .InternalSource
                                                .Reason
                                                .ACCOUNT_CLOSURE
                                        )
                                        .build()
                                )
                                .realTimePaymentsTransferAcknowledgement(
                                    InterestPaymentSimulationResult.Transaction.Source
                                        .RealTimePaymentsTransferAcknowledgement
                                        .builder()
                                        .amount(123L)
                                        .destinationAccountNumber("string")
                                        .destinationRoutingNumber("string")
                                        .remittanceInformation("string")
                                        .transferId("string")
                                        .build()
                                )
                                .sampleFunds(
                                    InterestPaymentSimulationResult.Transaction.Source.SampleFunds
                                        .builder()
                                        .originator("string")
                                        .build()
                                )
                                .wireTransferIntention(
                                    InterestPaymentSimulationResult.Transaction.Source
                                        .WireTransferIntention
                                        .builder()
                                        .accountNumber("string")
                                        .amount(123L)
                                        .messageToRecipient("string")
                                        .routingNumber("string")
                                        .transferId("string")
                                        .build()
                                )
                                .wireTransferRejection(
                                    InterestPaymentSimulationResult.Transaction.Source
                                        .WireTransferRejection
                                        .builder()
                                        .transferId("string")
                                        .build()
                                )
                                .build()
                        )
                        .type(InterestPaymentSimulationResult.Transaction.Type.TRANSACTION)
                        .build()
                )
                .type(InterestPaymentSimulationResult.Type.INTEREST_PAYMENT_SIMULATION_RESULT)
                .build()
        assertThat(interestPaymentSimulationResult).isNotNull
        assertThat(interestPaymentSimulationResult.transaction())
            .isEqualTo(
                InterestPaymentSimulationResult.Transaction.builder()
                    .id("string")
                    .accountId("string")
                    .amount(123L)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .currency(InterestPaymentSimulationResult.Transaction.Currency.CAD)
                    .description("string")
                    .routeId("string")
                    .routeType(InterestPaymentSimulationResult.Transaction.RouteType.ACCOUNT_NUMBER)
                    .source(
                        InterestPaymentSimulationResult.Transaction.Source.builder()
                            .accountTransferIntention(
                                InterestPaymentSimulationResult.Transaction.Source
                                    .AccountTransferIntention
                                    .builder()
                                    .amount(123L)
                                    .currency(
                                        InterestPaymentSimulationResult.Transaction.Source
                                            .AccountTransferIntention
                                            .Currency
                                            .CAD
                                    )
                                    .description("string")
                                    .destinationAccountId("string")
                                    .sourceAccountId("string")
                                    .transferId("string")
                                    .build()
                            )
                            .achTransferIntention(
                                InterestPaymentSimulationResult.Transaction.Source
                                    .AchTransferIntention
                                    .builder()
                                    .accountNumber("string")
                                    .amount(123L)
                                    .routingNumber("string")
                                    .statementDescriptor("string")
                                    .transferId("string")
                                    .build()
                            )
                            .achTransferRejection(
                                InterestPaymentSimulationResult.Transaction.Source
                                    .AchTransferRejection
                                    .builder()
                                    .transferId("string")
                                    .build()
                            )
                            .achTransferReturn(
                                InterestPaymentSimulationResult.Transaction.Source.AchTransferReturn
                                    .builder()
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .rawReturnReasonCode("string")
                                    .returnReasonCode(
                                        InterestPaymentSimulationResult.Transaction.Source
                                            .AchTransferReturn
                                            .ReturnReasonCode
                                            .INSUFFICIENT_FUND
                                    )
                                    .transactionId("string")
                                    .transferId("string")
                                    .build()
                            )
                            .cardDisputeAcceptance(
                                InterestPaymentSimulationResult.Transaction.Source
                                    .CardDisputeAcceptance
                                    .builder()
                                    .acceptedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .cardDisputeId("string")
                                    .transactionId("string")
                                    .build()
                            )
                            .cardRefund(
                                InterestPaymentSimulationResult.Transaction.Source.CardRefund
                                    .builder()
                                    .id("string")
                                    .amount(123L)
                                    .currency(
                                        InterestPaymentSimulationResult.Transaction.Source
                                            .CardRefund
                                            .Currency
                                            .CAD
                                    )
                                    .merchantAcceptorId("string")
                                    .merchantCategoryCode("string")
                                    .merchantCity("string")
                                    .merchantCountry("string")
                                    .merchantName("string")
                                    .merchantState("string")
                                    .transactionId("string")
                                    .type(
                                        InterestPaymentSimulationResult.Transaction.Source
                                            .CardRefund
                                            .Type
                                            .CARD_REFUND
                                    )
                                    .build()
                            )
                            .cardRevenuePayment(
                                InterestPaymentSimulationResult.Transaction.Source
                                    .CardRevenuePayment
                                    .builder()
                                    .amount(123L)
                                    .currency(
                                        InterestPaymentSimulationResult.Transaction.Source
                                            .CardRevenuePayment
                                            .Currency
                                            .CAD
                                    )
                                    .periodEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .periodStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .transactedOnAccountId("string")
                                    .build()
                            )
                            .cardSettlement(
                                InterestPaymentSimulationResult.Transaction.Source.CardSettlement
                                    .builder()
                                    .id("string")
                                    .amount(123L)
                                    .cardAuthorization("string")
                                    .currency(
                                        InterestPaymentSimulationResult.Transaction.Source
                                            .CardSettlement
                                            .Currency
                                            .CAD
                                    )
                                    .merchantAcceptorId("string")
                                    .merchantCategoryCode("string")
                                    .merchantCity("string")
                                    .merchantCountry("string")
                                    .merchantName("string")
                                    .merchantState("string")
                                    .pendingTransactionId("string")
                                    .presentmentAmount(123L)
                                    .presentmentCurrency("string")
                                    .transactionId("string")
                                    .type(
                                        InterestPaymentSimulationResult.Transaction.Source
                                            .CardSettlement
                                            .Type
                                            .CARD_SETTLEMENT
                                    )
                                    .build()
                            )
                            .category(
                                InterestPaymentSimulationResult.Transaction.Source.Category
                                    .ACCOUNT_TRANSFER_INTENTION
                            )
                            .checkDepositAcceptance(
                                InterestPaymentSimulationResult.Transaction.Source
                                    .CheckDepositAcceptance
                                    .builder()
                                    .accountNumber("string")
                                    .amount(123L)
                                    .auxiliaryOnUs("string")
                                    .checkDepositId("string")
                                    .currency(
                                        InterestPaymentSimulationResult.Transaction.Source
                                            .CheckDepositAcceptance
                                            .Currency
                                            .CAD
                                    )
                                    .routingNumber("string")
                                    .serialNumber("string")
                                    .build()
                            )
                            .checkDepositReturn(
                                InterestPaymentSimulationResult.Transaction.Source
                                    .CheckDepositReturn
                                    .builder()
                                    .amount(123L)
                                    .checkDepositId("string")
                                    .currency(
                                        InterestPaymentSimulationResult.Transaction.Source
                                            .CheckDepositReturn
                                            .Currency
                                            .CAD
                                    )
                                    .returnReason(
                                        InterestPaymentSimulationResult.Transaction.Source
                                            .CheckDepositReturn
                                            .ReturnReason
                                            .ACH_CONVERSION_NOT_SUPPORTED
                                    )
                                    .returnedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .transactionId("string")
                                    .build()
                            )
                            .checkTransferDeposit(
                                InterestPaymentSimulationResult.Transaction.Source
                                    .CheckTransferDeposit
                                    .builder()
                                    .backImageFileId("string")
                                    .depositedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .frontImageFileId("string")
                                    .transactionId("string")
                                    .type(
                                        InterestPaymentSimulationResult.Transaction.Source
                                            .CheckTransferDeposit
                                            .Type
                                            .CHECK_TRANSFER_DEPOSIT
                                    )
                                    .build()
                            )
                            .checkTransferIntention(
                                InterestPaymentSimulationResult.Transaction.Source
                                    .CheckTransferIntention
                                    .builder()
                                    .addressCity("string")
                                    .addressLine1("string")
                                    .addressLine2("string")
                                    .addressState("string")
                                    .addressZip("string")
                                    .amount(123L)
                                    .currency(
                                        InterestPaymentSimulationResult.Transaction.Source
                                            .CheckTransferIntention
                                            .Currency
                                            .CAD
                                    )
                                    .recipientName("string")
                                    .transferId("string")
                                    .build()
                            )
                            .checkTransferRejection(
                                InterestPaymentSimulationResult.Transaction.Source
                                    .CheckTransferRejection
                                    .builder()
                                    .transferId("string")
                                    .build()
                            )
                            .checkTransferStopPaymentRequest(
                                InterestPaymentSimulationResult.Transaction.Source
                                    .CheckTransferStopPaymentRequest
                                    .builder()
                                    .reason(
                                        InterestPaymentSimulationResult.Transaction.Source
                                            .CheckTransferStopPaymentRequest
                                            .Reason
                                            .MAIL_DELIVERY_FAILED
                                    )
                                    .requestedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .transferId("string")
                                    .type(
                                        InterestPaymentSimulationResult.Transaction.Source
                                            .CheckTransferStopPaymentRequest
                                            .Type
                                            .CHECK_TRANSFER_STOP_PAYMENT_REQUEST
                                    )
                                    .build()
                            )
                            .feePayment(
                                InterestPaymentSimulationResult.Transaction.Source.FeePayment
                                    .builder()
                                    .amount(123L)
                                    .currency(
                                        InterestPaymentSimulationResult.Transaction.Source
                                            .FeePayment
                                            .Currency
                                            .CAD
                                    )
                                    .feePeriodStart(LocalDate.parse("2019-12-27"))
                                    .build()
                            )
                            .inboundAchTransfer(
                                InterestPaymentSimulationResult.Transaction.Source
                                    .InboundAchTransfer
                                    .builder()
                                    .amount(123L)
                                    .originatorCompanyDescriptiveDate("string")
                                    .originatorCompanyDiscretionaryData("string")
                                    .originatorCompanyEntryDescription("string")
                                    .originatorCompanyId("string")
                                    .originatorCompanyName("string")
                                    .receiverIdNumber("string")
                                    .receiverName("string")
                                    .traceNumber("string")
                                    .build()
                            )
                            .inboundCheck(
                                InterestPaymentSimulationResult.Transaction.Source.InboundCheck
                                    .builder()
                                    .amount(123L)
                                    .checkFrontImageFileId("string")
                                    .checkNumber("string")
                                    .checkRearImageFileId("string")
                                    .currency(
                                        InterestPaymentSimulationResult.Transaction.Source
                                            .InboundCheck
                                            .Currency
                                            .CAD
                                    )
                                    .build()
                            )
                            .inboundInternationalAchTransfer(
                                InterestPaymentSimulationResult.Transaction.Source
                                    .InboundInternationalAchTransfer
                                    .builder()
                                    .amount(123L)
                                    .destinationCountryCode("string")
                                    .destinationCurrencyCode("string")
                                    .foreignExchangeIndicator("string")
                                    .foreignExchangeReference("string")
                                    .foreignExchangeReferenceIndicator("string")
                                    .foreignPaymentAmount(123L)
                                    .foreignTraceNumber("string")
                                    .internationalTransactionTypeCode("string")
                                    .originatingCurrencyCode("string")
                                    .originatingDepositoryFinancialInstitutionBranchCountry(
                                        "string"
                                    )
                                    .originatingDepositoryFinancialInstitutionId("string")
                                    .originatingDepositoryFinancialInstitutionIdQualifier("string")
                                    .originatingDepositoryFinancialInstitutionName("string")
                                    .originatorCity("string")
                                    .originatorCompanyEntryDescription("string")
                                    .originatorCountry("string")
                                    .originatorIdentification("string")
                                    .originatorName("string")
                                    .originatorPostalCode("string")
                                    .originatorStateOrProvince("string")
                                    .originatorStreetAddress("string")
                                    .paymentRelatedInformation("string")
                                    .paymentRelatedInformation2("string")
                                    .receiverCity("string")
                                    .receiverCountry("string")
                                    .receiverIdentificationNumber("string")
                                    .receiverPostalCode("string")
                                    .receiverStateOrProvince("string")
                                    .receiverStreetAddress("string")
                                    .receivingCompanyOrIndividualName("string")
                                    .receivingDepositoryFinancialInstitutionCountry("string")
                                    .receivingDepositoryFinancialInstitutionId("string")
                                    .receivingDepositoryFinancialInstitutionIdQualifier("string")
                                    .receivingDepositoryFinancialInstitutionName("string")
                                    .traceNumber("string")
                                    .build()
                            )
                            .inboundRealTimePaymentsTransferConfirmation(
                                InterestPaymentSimulationResult.Transaction.Source
                                    .InboundRealTimePaymentsTransferConfirmation
                                    .builder()
                                    .amount(123L)
                                    .creditorName("string")
                                    .currency(
                                        InterestPaymentSimulationResult.Transaction.Source
                                            .InboundRealTimePaymentsTransferConfirmation
                                            .Currency
                                            .CAD
                                    )
                                    .debtorAccountNumber("string")
                                    .debtorName("string")
                                    .debtorRoutingNumber("string")
                                    .remittanceInformation("string")
                                    .transactionIdentification("string")
                                    .build()
                            )
                            .inboundWireDrawdownPayment(
                                InterestPaymentSimulationResult.Transaction.Source
                                    .InboundWireDrawdownPayment
                                    .builder()
                                    .amount(123L)
                                    .beneficiaryAddressLine1("string")
                                    .beneficiaryAddressLine2("string")
                                    .beneficiaryAddressLine3("string")
                                    .beneficiaryName("string")
                                    .beneficiaryReference("string")
                                    .description("string")
                                    .inputMessageAccountabilityData("string")
                                    .originatorAddressLine1("string")
                                    .originatorAddressLine2("string")
                                    .originatorAddressLine3("string")
                                    .originatorName("string")
                                    .originatorToBeneficiaryInformation("string")
                                    .build()
                            )
                            .inboundWireDrawdownPaymentReversal(
                                InterestPaymentSimulationResult.Transaction.Source
                                    .InboundWireDrawdownPaymentReversal
                                    .builder()
                                    .amount(123L)
                                    .description("string")
                                    .inputCycleDate(LocalDate.parse("2019-12-27"))
                                    .inputMessageAccountabilityData("string")
                                    .inputSequenceNumber("string")
                                    .inputSource("string")
                                    .previousMessageInputCycleDate(LocalDate.parse("2019-12-27"))
                                    .previousMessageInputMessageAccountabilityData("string")
                                    .previousMessageInputSequenceNumber("string")
                                    .previousMessageInputSource("string")
                                    .build()
                            )
                            .inboundWireReversal(
                                InterestPaymentSimulationResult.Transaction.Source
                                    .InboundWireReversal
                                    .builder()
                                    .amount(123L)
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .description("string")
                                    .financialInstitutionToFinancialInstitutionInformation("string")
                                    .inputCycleDate(LocalDate.parse("2019-12-27"))
                                    .inputMessageAccountabilityData("string")
                                    .inputSequenceNumber("string")
                                    .inputSource("string")
                                    .previousMessageInputCycleDate(LocalDate.parse("2019-12-27"))
                                    .previousMessageInputMessageAccountabilityData("string")
                                    .previousMessageInputSequenceNumber("string")
                                    .previousMessageInputSource("string")
                                    .receiverFinancialInstitutionInformation("string")
                                    .transactionId("string")
                                    .wireTransferId("string")
                                    .build()
                            )
                            .inboundWireTransfer(
                                InterestPaymentSimulationResult.Transaction.Source
                                    .InboundWireTransfer
                                    .builder()
                                    .amount(123L)
                                    .beneficiaryAddressLine1("string")
                                    .beneficiaryAddressLine2("string")
                                    .beneficiaryAddressLine3("string")
                                    .beneficiaryName("string")
                                    .beneficiaryReference("string")
                                    .description("string")
                                    .inputMessageAccountabilityData("string")
                                    .originatorAddressLine1("string")
                                    .originatorAddressLine2("string")
                                    .originatorAddressLine3("string")
                                    .originatorName("string")
                                    .originatorToBeneficiaryInformation("string")
                                    .originatorToBeneficiaryInformationLine1("string")
                                    .originatorToBeneficiaryInformationLine2("string")
                                    .originatorToBeneficiaryInformationLine3("string")
                                    .originatorToBeneficiaryInformationLine4("string")
                                    .build()
                            )
                            .interestPayment(
                                InterestPaymentSimulationResult.Transaction.Source.InterestPayment
                                    .builder()
                                    .accruedOnAccountId("string")
                                    .amount(123L)
                                    .currency(
                                        InterestPaymentSimulationResult.Transaction.Source
                                            .InterestPayment
                                            .Currency
                                            .CAD
                                    )
                                    .periodEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .periodStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .internalSource(
                                InterestPaymentSimulationResult.Transaction.Source.InternalSource
                                    .builder()
                                    .amount(123L)
                                    .currency(
                                        InterestPaymentSimulationResult.Transaction.Source
                                            .InternalSource
                                            .Currency
                                            .CAD
                                    )
                                    .reason(
                                        InterestPaymentSimulationResult.Transaction.Source
                                            .InternalSource
                                            .Reason
                                            .ACCOUNT_CLOSURE
                                    )
                                    .build()
                            )
                            .realTimePaymentsTransferAcknowledgement(
                                InterestPaymentSimulationResult.Transaction.Source
                                    .RealTimePaymentsTransferAcknowledgement
                                    .builder()
                                    .amount(123L)
                                    .destinationAccountNumber("string")
                                    .destinationRoutingNumber("string")
                                    .remittanceInformation("string")
                                    .transferId("string")
                                    .build()
                            )
                            .sampleFunds(
                                InterestPaymentSimulationResult.Transaction.Source.SampleFunds
                                    .builder()
                                    .originator("string")
                                    .build()
                            )
                            .wireTransferIntention(
                                InterestPaymentSimulationResult.Transaction.Source
                                    .WireTransferIntention
                                    .builder()
                                    .accountNumber("string")
                                    .amount(123L)
                                    .messageToRecipient("string")
                                    .routingNumber("string")
                                    .transferId("string")
                                    .build()
                            )
                            .wireTransferRejection(
                                InterestPaymentSimulationResult.Transaction.Source
                                    .WireTransferRejection
                                    .builder()
                                    .transferId("string")
                                    .build()
                            )
                            .build()
                    )
                    .type(InterestPaymentSimulationResult.Transaction.Type.TRANSACTION)
                    .build()
            )
        assertThat(interestPaymentSimulationResult.type())
            .isEqualTo(InterestPaymentSimulationResult.Type.INTEREST_PAYMENT_SIMULATION_RESULT)
    }
}
