// File generated from our OpenAPI spec by Stainless.

package com.increase.api.models.exports

import java.time.LocalDate
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ExportCreateParamsTest {

    @Test
    fun create() {
        ExportCreateParams.builder()
            .category(ExportCreateParams.Category.TRANSACTION_CSV)
            .accountStatementBai2(
                ExportCreateParams.AccountStatementBai2.builder()
                    .accountId("account_id")
                    .effectiveDate(LocalDate.parse("2019-12-27"))
                    .programId("program_id")
                    .build()
            )
            .accountStatementOfx(
                ExportCreateParams.AccountStatementOfx.builder()
                    .accountId("account_id")
                    .createdAt(
                        ExportCreateParams.AccountStatementOfx.CreatedAt.builder()
                            .after(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .before(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .onOrAfter(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .onOrBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .build()
            )
            .accountVerificationLetter(
                ExportCreateParams.AccountVerificationLetter.builder()
                    .accountNumberId("account_number_id")
                    .balanceDate(LocalDate.parse("2019-12-27"))
                    .build()
            )
            .balanceCsv(
                ExportCreateParams.BalanceCsv.builder()
                    .accountId("account_id")
                    .createdAt(
                        ExportCreateParams.BalanceCsv.CreatedAt.builder()
                            .after(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .before(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .onOrAfter(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .onOrBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .build()
            )
            .bookkeepingAccountBalanceCsv(
                ExportCreateParams.BookkeepingAccountBalanceCsv.builder()
                    .bookkeepingAccountId("bookkeeping_account_id")
                    .createdAt(
                        ExportCreateParams.BookkeepingAccountBalanceCsv.CreatedAt.builder()
                            .after(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .before(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .onOrAfter(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .onOrBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .build()
            )
            .entityCsv(ExportCreateParams.EntityCsv.builder().build())
            .fundingInstructions(
                ExportCreateParams.FundingInstructions.builder()
                    .accountNumberId("account_number_id")
                    .build()
            )
            .transactionCsv(
                ExportCreateParams.TransactionCsv.builder()
                    .accountId("account_in71c4amph0vgo2qllky")
                    .createdAt(
                        ExportCreateParams.TransactionCsv.CreatedAt.builder()
                            .after(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .before(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .onOrAfter(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .onOrBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .build()
            )
            .vendorCsv(ExportCreateParams.VendorCsv.builder().build())
            .voidedCheck(
                ExportCreateParams.VoidedCheck.builder()
                    .accountNumberId("account_number_id")
                    .addPayer(ExportCreateParams.VoidedCheck.Payer.builder().line("x").build())
                    .build()
            )
            .build()
    }

    @Test
    fun body() {
        val params =
            ExportCreateParams.builder()
                .category(ExportCreateParams.Category.TRANSACTION_CSV)
                .accountStatementBai2(
                    ExportCreateParams.AccountStatementBai2.builder()
                        .accountId("account_id")
                        .effectiveDate(LocalDate.parse("2019-12-27"))
                        .programId("program_id")
                        .build()
                )
                .accountStatementOfx(
                    ExportCreateParams.AccountStatementOfx.builder()
                        .accountId("account_id")
                        .createdAt(
                            ExportCreateParams.AccountStatementOfx.CreatedAt.builder()
                                .after(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .before(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .onOrAfter(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .onOrBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .build()
                )
                .accountVerificationLetter(
                    ExportCreateParams.AccountVerificationLetter.builder()
                        .accountNumberId("account_number_id")
                        .balanceDate(LocalDate.parse("2019-12-27"))
                        .build()
                )
                .balanceCsv(
                    ExportCreateParams.BalanceCsv.builder()
                        .accountId("account_id")
                        .createdAt(
                            ExportCreateParams.BalanceCsv.CreatedAt.builder()
                                .after(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .before(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .onOrAfter(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .onOrBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .build()
                )
                .bookkeepingAccountBalanceCsv(
                    ExportCreateParams.BookkeepingAccountBalanceCsv.builder()
                        .bookkeepingAccountId("bookkeeping_account_id")
                        .createdAt(
                            ExportCreateParams.BookkeepingAccountBalanceCsv.CreatedAt.builder()
                                .after(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .before(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .onOrAfter(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .onOrBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .build()
                )
                .entityCsv(ExportCreateParams.EntityCsv.builder().build())
                .fundingInstructions(
                    ExportCreateParams.FundingInstructions.builder()
                        .accountNumberId("account_number_id")
                        .build()
                )
                .transactionCsv(
                    ExportCreateParams.TransactionCsv.builder()
                        .accountId("account_in71c4amph0vgo2qllky")
                        .createdAt(
                            ExportCreateParams.TransactionCsv.CreatedAt.builder()
                                .after(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .before(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .onOrAfter(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .onOrBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .build()
                )
                .vendorCsv(ExportCreateParams.VendorCsv.builder().build())
                .voidedCheck(
                    ExportCreateParams.VoidedCheck.builder()
                        .accountNumberId("account_number_id")
                        .addPayer(ExportCreateParams.VoidedCheck.Payer.builder().line("x").build())
                        .build()
                )
                .build()

        val body = params._body()

        assertThat(body.category()).isEqualTo(ExportCreateParams.Category.TRANSACTION_CSV)
        assertThat(body.accountStatementBai2())
            .isEqualTo(
                ExportCreateParams.AccountStatementBai2.builder()
                    .accountId("account_id")
                    .effectiveDate(LocalDate.parse("2019-12-27"))
                    .programId("program_id")
                    .build()
            )
        assertThat(body.accountStatementOfx())
            .isEqualTo(
                ExportCreateParams.AccountStatementOfx.builder()
                    .accountId("account_id")
                    .createdAt(
                        ExportCreateParams.AccountStatementOfx.CreatedAt.builder()
                            .after(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .before(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .onOrAfter(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .onOrBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .build()
            )
        assertThat(body.accountVerificationLetter())
            .isEqualTo(
                ExportCreateParams.AccountVerificationLetter.builder()
                    .accountNumberId("account_number_id")
                    .balanceDate(LocalDate.parse("2019-12-27"))
                    .build()
            )
        assertThat(body.balanceCsv())
            .isEqualTo(
                ExportCreateParams.BalanceCsv.builder()
                    .accountId("account_id")
                    .createdAt(
                        ExportCreateParams.BalanceCsv.CreatedAt.builder()
                            .after(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .before(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .onOrAfter(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .onOrBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .build()
            )
        assertThat(body.bookkeepingAccountBalanceCsv())
            .isEqualTo(
                ExportCreateParams.BookkeepingAccountBalanceCsv.builder()
                    .bookkeepingAccountId("bookkeeping_account_id")
                    .createdAt(
                        ExportCreateParams.BookkeepingAccountBalanceCsv.CreatedAt.builder()
                            .after(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .before(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .onOrAfter(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .onOrBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .build()
            )
        assertThat(body.entityCsv()).isEqualTo(ExportCreateParams.EntityCsv.builder().build())
        assertThat(body.fundingInstructions())
            .isEqualTo(
                ExportCreateParams.FundingInstructions.builder()
                    .accountNumberId("account_number_id")
                    .build()
            )
        assertThat(body.transactionCsv())
            .isEqualTo(
                ExportCreateParams.TransactionCsv.builder()
                    .accountId("account_in71c4amph0vgo2qllky")
                    .createdAt(
                        ExportCreateParams.TransactionCsv.CreatedAt.builder()
                            .after(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .before(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .onOrAfter(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .onOrBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .build()
            )
        assertThat(body.vendorCsv()).isEqualTo(ExportCreateParams.VendorCsv.builder().build())
        assertThat(body.voidedCheck())
            .isEqualTo(
                ExportCreateParams.VoidedCheck.builder()
                    .accountNumberId("account_number_id")
                    .addPayer(ExportCreateParams.VoidedCheck.Payer.builder().line("x").build())
                    .build()
            )
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            ExportCreateParams.builder()
                .category(ExportCreateParams.Category.TRANSACTION_CSV)
                .build()

        val body = params._body()

        assertThat(body.category()).isEqualTo(ExportCreateParams.Category.TRANSACTION_CSV)
    }
}
