// File generated from our OpenAPI spec by Stainless.

package com.increase.api.models.cards

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CardCreateParamsTest {

    @Test
    fun create() {
        CardCreateParams.builder()
            .accountId("account_in71c4amph0vgo2qllky")
            .authorizationControls(
                CardCreateParams.AuthorizationControls.builder()
                    .maximumAuthorizationCount(
                        CardCreateParams.AuthorizationControls.MaximumAuthorizationCount.builder()
                            .allTime(0L)
                            .build()
                    )
                    .merchantAcceptorIdentifier(
                        CardCreateParams.AuthorizationControls.MerchantAcceptorIdentifier.builder()
                            .addAllowed(
                                CardCreateParams.AuthorizationControls.MerchantAcceptorIdentifier
                                    .Allowed
                                    .builder()
                                    .identifier("x")
                                    .build()
                            )
                            .addBlocked(
                                CardCreateParams.AuthorizationControls.MerchantAcceptorIdentifier
                                    .Blocked
                                    .builder()
                                    .identifier("x")
                                    .build()
                            )
                            .build()
                    )
                    .merchantCategoryCode(
                        CardCreateParams.AuthorizationControls.MerchantCategoryCode.builder()
                            .addAllowed(
                                CardCreateParams.AuthorizationControls.MerchantCategoryCode.Allowed
                                    .builder()
                                    .code("xxxx")
                                    .build()
                            )
                            .addBlocked(
                                CardCreateParams.AuthorizationControls.MerchantCategoryCode.Blocked
                                    .builder()
                                    .code("xxxx")
                                    .build()
                            )
                            .build()
                    )
                    .merchantCountry(
                        CardCreateParams.AuthorizationControls.MerchantCountry.builder()
                            .addAllowed(
                                CardCreateParams.AuthorizationControls.MerchantCountry.Allowed
                                    .builder()
                                    .country("xx")
                                    .build()
                            )
                            .addBlocked(
                                CardCreateParams.AuthorizationControls.MerchantCountry.Blocked
                                    .builder()
                                    .country("xx")
                                    .build()
                            )
                            .build()
                    )
                    .addSpendingLimit(
                        CardCreateParams.AuthorizationControls.SpendingLimit.builder()
                            .interval(
                                CardCreateParams.AuthorizationControls.SpendingLimit.Interval
                                    .ALL_TIME
                            )
                            .settlementAmount(0L)
                            .addMerchantCategoryCode(
                                CardCreateParams.AuthorizationControls.SpendingLimit
                                    .MerchantCategoryCode
                                    .builder()
                                    .code("x")
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
            .billingAddress(
                CardCreateParams.BillingAddress.builder()
                    .city("x")
                    .line1("x")
                    .postalCode("x")
                    .state("x")
                    .line2("x")
                    .build()
            )
            .description("Card for Ian Crease")
            .digitalWallet(
                CardCreateParams.DigitalWallet.builder()
                    .digitalCardProfileId("digital_card_profile_id")
                    .email("dev@stainless.com")
                    .phone("x")
                    .build()
            )
            .entityId("entity_id")
            .build()
    }

    @Test
    fun body() {
        val params =
            CardCreateParams.builder()
                .accountId("account_in71c4amph0vgo2qllky")
                .authorizationControls(
                    CardCreateParams.AuthorizationControls.builder()
                        .maximumAuthorizationCount(
                            CardCreateParams.AuthorizationControls.MaximumAuthorizationCount
                                .builder()
                                .allTime(0L)
                                .build()
                        )
                        .merchantAcceptorIdentifier(
                            CardCreateParams.AuthorizationControls.MerchantAcceptorIdentifier
                                .builder()
                                .addAllowed(
                                    CardCreateParams.AuthorizationControls
                                        .MerchantAcceptorIdentifier
                                        .Allowed
                                        .builder()
                                        .identifier("x")
                                        .build()
                                )
                                .addBlocked(
                                    CardCreateParams.AuthorizationControls
                                        .MerchantAcceptorIdentifier
                                        .Blocked
                                        .builder()
                                        .identifier("x")
                                        .build()
                                )
                                .build()
                        )
                        .merchantCategoryCode(
                            CardCreateParams.AuthorizationControls.MerchantCategoryCode.builder()
                                .addAllowed(
                                    CardCreateParams.AuthorizationControls.MerchantCategoryCode
                                        .Allowed
                                        .builder()
                                        .code("xxxx")
                                        .build()
                                )
                                .addBlocked(
                                    CardCreateParams.AuthorizationControls.MerchantCategoryCode
                                        .Blocked
                                        .builder()
                                        .code("xxxx")
                                        .build()
                                )
                                .build()
                        )
                        .merchantCountry(
                            CardCreateParams.AuthorizationControls.MerchantCountry.builder()
                                .addAllowed(
                                    CardCreateParams.AuthorizationControls.MerchantCountry.Allowed
                                        .builder()
                                        .country("xx")
                                        .build()
                                )
                                .addBlocked(
                                    CardCreateParams.AuthorizationControls.MerchantCountry.Blocked
                                        .builder()
                                        .country("xx")
                                        .build()
                                )
                                .build()
                        )
                        .addSpendingLimit(
                            CardCreateParams.AuthorizationControls.SpendingLimit.builder()
                                .interval(
                                    CardCreateParams.AuthorizationControls.SpendingLimit.Interval
                                        .ALL_TIME
                                )
                                .settlementAmount(0L)
                                .addMerchantCategoryCode(
                                    CardCreateParams.AuthorizationControls.SpendingLimit
                                        .MerchantCategoryCode
                                        .builder()
                                        .code("x")
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .billingAddress(
                    CardCreateParams.BillingAddress.builder()
                        .city("x")
                        .line1("x")
                        .postalCode("x")
                        .state("x")
                        .line2("x")
                        .build()
                )
                .description("Card for Ian Crease")
                .digitalWallet(
                    CardCreateParams.DigitalWallet.builder()
                        .digitalCardProfileId("digital_card_profile_id")
                        .email("dev@stainless.com")
                        .phone("x")
                        .build()
                )
                .entityId("entity_id")
                .build()

        val body = params._body()

        assertThat(body.accountId()).isEqualTo("account_in71c4amph0vgo2qllky")
        assertThat(body.authorizationControls())
            .isEqualTo(
                CardCreateParams.AuthorizationControls.builder()
                    .maximumAuthorizationCount(
                        CardCreateParams.AuthorizationControls.MaximumAuthorizationCount.builder()
                            .allTime(0L)
                            .build()
                    )
                    .merchantAcceptorIdentifier(
                        CardCreateParams.AuthorizationControls.MerchantAcceptorIdentifier.builder()
                            .addAllowed(
                                CardCreateParams.AuthorizationControls.MerchantAcceptorIdentifier
                                    .Allowed
                                    .builder()
                                    .identifier("x")
                                    .build()
                            )
                            .addBlocked(
                                CardCreateParams.AuthorizationControls.MerchantAcceptorIdentifier
                                    .Blocked
                                    .builder()
                                    .identifier("x")
                                    .build()
                            )
                            .build()
                    )
                    .merchantCategoryCode(
                        CardCreateParams.AuthorizationControls.MerchantCategoryCode.builder()
                            .addAllowed(
                                CardCreateParams.AuthorizationControls.MerchantCategoryCode.Allowed
                                    .builder()
                                    .code("xxxx")
                                    .build()
                            )
                            .addBlocked(
                                CardCreateParams.AuthorizationControls.MerchantCategoryCode.Blocked
                                    .builder()
                                    .code("xxxx")
                                    .build()
                            )
                            .build()
                    )
                    .merchantCountry(
                        CardCreateParams.AuthorizationControls.MerchantCountry.builder()
                            .addAllowed(
                                CardCreateParams.AuthorizationControls.MerchantCountry.Allowed
                                    .builder()
                                    .country("xx")
                                    .build()
                            )
                            .addBlocked(
                                CardCreateParams.AuthorizationControls.MerchantCountry.Blocked
                                    .builder()
                                    .country("xx")
                                    .build()
                            )
                            .build()
                    )
                    .addSpendingLimit(
                        CardCreateParams.AuthorizationControls.SpendingLimit.builder()
                            .interval(
                                CardCreateParams.AuthorizationControls.SpendingLimit.Interval
                                    .ALL_TIME
                            )
                            .settlementAmount(0L)
                            .addMerchantCategoryCode(
                                CardCreateParams.AuthorizationControls.SpendingLimit
                                    .MerchantCategoryCode
                                    .builder()
                                    .code("x")
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(body.billingAddress())
            .isEqualTo(
                CardCreateParams.BillingAddress.builder()
                    .city("x")
                    .line1("x")
                    .postalCode("x")
                    .state("x")
                    .line2("x")
                    .build()
            )
        assertThat(body.description()).isEqualTo("Card for Ian Crease")
        assertThat(body.digitalWallet())
            .isEqualTo(
                CardCreateParams.DigitalWallet.builder()
                    .digitalCardProfileId("digital_card_profile_id")
                    .email("dev@stainless.com")
                    .phone("x")
                    .build()
            )
        assertThat(body.entityId()).isEqualTo("entity_id")
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params = CardCreateParams.builder().accountId("account_in71c4amph0vgo2qllky").build()

        val body = params._body()

        assertThat(body.accountId()).isEqualTo("account_in71c4amph0vgo2qllky")
    }
}
