// File generated from our OpenAPI spec by Stainless.

package com.increase.api.models.entities

import java.time.LocalDate
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class EntityUpdateParamsTest {

    @Test
    fun create() {
        EntityUpdateParams.builder()
            .entityId("entity_n8y8tnk2p9339ti393yi")
            .corporation(
                EntityUpdateParams.Corporation.builder()
                    .address(
                        EntityUpdateParams.Corporation.Address.builder()
                            .city("New York")
                            .country("US")
                            .line1("33 Liberty Street")
                            .line2("Unit 2")
                            .state("NY")
                            .zip("10045")
                            .build()
                    )
                    .email("dev@stainless.com")
                    .incorporationState("x")
                    .industryCode("x")
                    .legalIdentifier(
                        EntityUpdateParams.Corporation.LegalIdentifier.builder()
                            .value("x")
                            .category(
                                EntityUpdateParams.Corporation.LegalIdentifier.Category
                                    .US_EMPLOYER_IDENTIFICATION_NUMBER
                            )
                            .build()
                    )
                    .name("x")
                    .website("website")
                    .build()
            )
            .detailsConfirmedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
            .governmentAuthority(
                EntityUpdateParams.GovernmentAuthority.builder()
                    .address(
                        EntityUpdateParams.GovernmentAuthority.Address.builder()
                            .city("x")
                            .line1("x")
                            .state("xx")
                            .zip("x")
                            .line2("x")
                            .build()
                    )
                    .name("x")
                    .build()
            )
            .naturalPerson(
                EntityUpdateParams.NaturalPerson.builder()
                    .address(
                        EntityUpdateParams.NaturalPerson.Address.builder()
                            .city("x")
                            .country("x")
                            .line1("x")
                            .line2("x")
                            .state("x")
                            .zip("x")
                            .build()
                    )
                    .confirmedNoUsTaxId(true)
                    .identification(
                        EntityUpdateParams.NaturalPerson.Identification.builder()
                            .method(
                                EntityUpdateParams.NaturalPerson.Identification.Method
                                    .SOCIAL_SECURITY_NUMBER
                            )
                            .number("xxxx")
                            .driversLicense(
                                EntityUpdateParams.NaturalPerson.Identification.DriversLicense
                                    .builder()
                                    .expirationDate(LocalDate.parse("2019-12-27"))
                                    .fileId("file_id")
                                    .state("xx")
                                    .backFileId("back_file_id")
                                    .build()
                            )
                            .other(
                                EntityUpdateParams.NaturalPerson.Identification.Other.builder()
                                    .country("x")
                                    .description("x")
                                    .fileId("file_id")
                                    .backFileId("back_file_id")
                                    .expirationDate(LocalDate.parse("2019-12-27"))
                                    .build()
                            )
                            .passport(
                                EntityUpdateParams.NaturalPerson.Identification.Passport.builder()
                                    .country("x")
                                    .expirationDate(LocalDate.parse("2019-12-27"))
                                    .fileId("file_id")
                                    .build()
                            )
                            .build()
                    )
                    .name("x")
                    .build()
            )
            .riskRating(
                EntityUpdateParams.RiskRating.builder()
                    .ratedAt(OffsetDateTime.parse("2020-01-31T23:59:59Z"))
                    .rating(EntityUpdateParams.RiskRating.Rating.LOW)
                    .build()
            )
            .soleProprietorship(
                EntityUpdateParams.SoleProprietorship.builder()
                    .address(
                        EntityUpdateParams.SoleProprietorship.Address.builder()
                            .city("x")
                            .line1("x")
                            .state("xx")
                            .zip("x")
                            .line2("x")
                            .build()
                    )
                    .email("dev@stainless.com")
                    .soleProprietor(
                        EntityUpdateParams.SoleProprietorship.SoleProprietor.builder()
                            .address(
                                EntityUpdateParams.SoleProprietorship.SoleProprietor.Address
                                    .builder()
                                    .city("x")
                                    .country("x")
                                    .line1("x")
                                    .line2("x")
                                    .state("x")
                                    .zip("x")
                                    .build()
                            )
                            .identification(
                                EntityUpdateParams.SoleProprietorship.SoleProprietor.Identification
                                    .builder()
                                    .method(
                                        EntityUpdateParams.SoleProprietorship.SoleProprietor
                                            .Identification
                                            .Method
                                            .SOCIAL_SECURITY_NUMBER
                                    )
                                    .number("xxxx")
                                    .driversLicense(
                                        EntityUpdateParams.SoleProprietorship.SoleProprietor
                                            .Identification
                                            .DriversLicense
                                            .builder()
                                            .expirationDate(LocalDate.parse("2019-12-27"))
                                            .fileId("file_id")
                                            .state("xx")
                                            .backFileId("back_file_id")
                                            .build()
                                    )
                                    .other(
                                        EntityUpdateParams.SoleProprietorship.SoleProprietor
                                            .Identification
                                            .Other
                                            .builder()
                                            .country("x")
                                            .description("x")
                                            .fileId("file_id")
                                            .backFileId("back_file_id")
                                            .expirationDate(LocalDate.parse("2019-12-27"))
                                            .build()
                                    )
                                    .passport(
                                        EntityUpdateParams.SoleProprietorship.SoleProprietor
                                            .Identification
                                            .Passport
                                            .builder()
                                            .country("x")
                                            .expirationDate(LocalDate.parse("2019-12-27"))
                                            .fileId("file_id")
                                            .build()
                                    )
                                    .build()
                            )
                            .name("x")
                            .build()
                    )
                    .taxIdentifier("x")
                    .website("website")
                    .build()
            )
            .addTermsAgreement(
                EntityUpdateParams.TermsAgreement.builder()
                    .agreedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .ipAddress("x")
                    .termsUrl("x")
                    .build()
            )
            .thirdPartyVerification(
                EntityUpdateParams.ThirdPartyVerification.builder()
                    .reference("x")
                    .vendor(EntityUpdateParams.ThirdPartyVerification.Vendor.ALLOY)
                    .build()
            )
            .trust(
                EntityUpdateParams.Trust.builder()
                    .address(
                        EntityUpdateParams.Trust.Address.builder()
                            .city("x")
                            .line1("x")
                            .state("xx")
                            .zip("x")
                            .line2("x")
                            .build()
                    )
                    .grantor(
                        EntityUpdateParams.Trust.Grantor.builder()
                            .address(
                                EntityUpdateParams.Trust.Grantor.Address.builder()
                                    .city("x")
                                    .country("x")
                                    .line1("x")
                                    .line2("x")
                                    .state("x")
                                    .zip("x")
                                    .build()
                            )
                            .dateOfBirth(LocalDate.parse("2019-12-27"))
                            .identification(
                                EntityUpdateParams.Trust.Grantor.Identification.builder()
                                    .method(
                                        EntityUpdateParams.Trust.Grantor.Identification.Method
                                            .SOCIAL_SECURITY_NUMBER
                                    )
                                    .number("xxxx")
                                    .driversLicense(
                                        EntityUpdateParams.Trust.Grantor.Identification
                                            .DriversLicense
                                            .builder()
                                            .expirationDate(LocalDate.parse("2019-12-27"))
                                            .fileId("file_id")
                                            .state("xx")
                                            .backFileId("back_file_id")
                                            .build()
                                    )
                                    .other(
                                        EntityUpdateParams.Trust.Grantor.Identification.Other
                                            .builder()
                                            .country("x")
                                            .description("x")
                                            .fileId("file_id")
                                            .backFileId("back_file_id")
                                            .expirationDate(LocalDate.parse("2019-12-27"))
                                            .build()
                                    )
                                    .passport(
                                        EntityUpdateParams.Trust.Grantor.Identification.Passport
                                            .builder()
                                            .country("x")
                                            .expirationDate(LocalDate.parse("2019-12-27"))
                                            .fileId("file_id")
                                            .build()
                                    )
                                    .build()
                            )
                            .name("x")
                            .confirmedNoUsTaxId(true)
                            .build()
                    )
                    .name("x")
                    .addTrustee(
                        EntityUpdateParams.Trust.Trustee.builder()
                            .structure(EntityUpdateParams.Trust.Trustee.Structure.INDIVIDUAL)
                            .individual(
                                EntityUpdateParams.Trust.Trustee.Individual.builder()
                                    .address(
                                        EntityUpdateParams.Trust.Trustee.Individual.Address
                                            .builder()
                                            .city("x")
                                            .country("x")
                                            .line1("x")
                                            .line2("x")
                                            .state("x")
                                            .zip("x")
                                            .build()
                                    )
                                    .dateOfBirth(LocalDate.parse("2019-12-27"))
                                    .identification(
                                        EntityUpdateParams.Trust.Trustee.Individual.Identification
                                            .builder()
                                            .method(
                                                EntityUpdateParams.Trust.Trustee.Individual
                                                    .Identification
                                                    .Method
                                                    .SOCIAL_SECURITY_NUMBER
                                            )
                                            .number("xxxx")
                                            .driversLicense(
                                                EntityUpdateParams.Trust.Trustee.Individual
                                                    .Identification
                                                    .DriversLicense
                                                    .builder()
                                                    .expirationDate(LocalDate.parse("2019-12-27"))
                                                    .fileId("file_id")
                                                    .state("xx")
                                                    .backFileId("back_file_id")
                                                    .build()
                                            )
                                            .other(
                                                EntityUpdateParams.Trust.Trustee.Individual
                                                    .Identification
                                                    .Other
                                                    .builder()
                                                    .country("x")
                                                    .description("x")
                                                    .fileId("file_id")
                                                    .backFileId("back_file_id")
                                                    .expirationDate(LocalDate.parse("2019-12-27"))
                                                    .build()
                                            )
                                            .passport(
                                                EntityUpdateParams.Trust.Trustee.Individual
                                                    .Identification
                                                    .Passport
                                                    .builder()
                                                    .country("x")
                                                    .expirationDate(LocalDate.parse("2019-12-27"))
                                                    .fileId("file_id")
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .name("x")
                                    .confirmedNoUsTaxId(true)
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
            .build()
    }

    @Test
    fun pathParams() {
        val params = EntityUpdateParams.builder().entityId("entity_n8y8tnk2p9339ti393yi").build()

        assertThat(params._pathParam(0)).isEqualTo("entity_n8y8tnk2p9339ti393yi")
        // out-of-bound path param
        assertThat(params._pathParam(1)).isEqualTo("")
    }

    @Test
    fun body() {
        val params =
            EntityUpdateParams.builder()
                .entityId("entity_n8y8tnk2p9339ti393yi")
                .corporation(
                    EntityUpdateParams.Corporation.builder()
                        .address(
                            EntityUpdateParams.Corporation.Address.builder()
                                .city("New York")
                                .country("US")
                                .line1("33 Liberty Street")
                                .line2("Unit 2")
                                .state("NY")
                                .zip("10045")
                                .build()
                        )
                        .email("dev@stainless.com")
                        .incorporationState("x")
                        .industryCode("x")
                        .legalIdentifier(
                            EntityUpdateParams.Corporation.LegalIdentifier.builder()
                                .value("x")
                                .category(
                                    EntityUpdateParams.Corporation.LegalIdentifier.Category
                                        .US_EMPLOYER_IDENTIFICATION_NUMBER
                                )
                                .build()
                        )
                        .name("x")
                        .website("website")
                        .build()
                )
                .detailsConfirmedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .governmentAuthority(
                    EntityUpdateParams.GovernmentAuthority.builder()
                        .address(
                            EntityUpdateParams.GovernmentAuthority.Address.builder()
                                .city("x")
                                .line1("x")
                                .state("xx")
                                .zip("x")
                                .line2("x")
                                .build()
                        )
                        .name("x")
                        .build()
                )
                .naturalPerson(
                    EntityUpdateParams.NaturalPerson.builder()
                        .address(
                            EntityUpdateParams.NaturalPerson.Address.builder()
                                .city("x")
                                .country("x")
                                .line1("x")
                                .line2("x")
                                .state("x")
                                .zip("x")
                                .build()
                        )
                        .confirmedNoUsTaxId(true)
                        .identification(
                            EntityUpdateParams.NaturalPerson.Identification.builder()
                                .method(
                                    EntityUpdateParams.NaturalPerson.Identification.Method
                                        .SOCIAL_SECURITY_NUMBER
                                )
                                .number("xxxx")
                                .driversLicense(
                                    EntityUpdateParams.NaturalPerson.Identification.DriversLicense
                                        .builder()
                                        .expirationDate(LocalDate.parse("2019-12-27"))
                                        .fileId("file_id")
                                        .state("xx")
                                        .backFileId("back_file_id")
                                        .build()
                                )
                                .other(
                                    EntityUpdateParams.NaturalPerson.Identification.Other.builder()
                                        .country("x")
                                        .description("x")
                                        .fileId("file_id")
                                        .backFileId("back_file_id")
                                        .expirationDate(LocalDate.parse("2019-12-27"))
                                        .build()
                                )
                                .passport(
                                    EntityUpdateParams.NaturalPerson.Identification.Passport
                                        .builder()
                                        .country("x")
                                        .expirationDate(LocalDate.parse("2019-12-27"))
                                        .fileId("file_id")
                                        .build()
                                )
                                .build()
                        )
                        .name("x")
                        .build()
                )
                .riskRating(
                    EntityUpdateParams.RiskRating.builder()
                        .ratedAt(OffsetDateTime.parse("2020-01-31T23:59:59Z"))
                        .rating(EntityUpdateParams.RiskRating.Rating.LOW)
                        .build()
                )
                .soleProprietorship(
                    EntityUpdateParams.SoleProprietorship.builder()
                        .address(
                            EntityUpdateParams.SoleProprietorship.Address.builder()
                                .city("x")
                                .line1("x")
                                .state("xx")
                                .zip("x")
                                .line2("x")
                                .build()
                        )
                        .email("dev@stainless.com")
                        .soleProprietor(
                            EntityUpdateParams.SoleProprietorship.SoleProprietor.builder()
                                .address(
                                    EntityUpdateParams.SoleProprietorship.SoleProprietor.Address
                                        .builder()
                                        .city("x")
                                        .country("x")
                                        .line1("x")
                                        .line2("x")
                                        .state("x")
                                        .zip("x")
                                        .build()
                                )
                                .identification(
                                    EntityUpdateParams.SoleProprietorship.SoleProprietor
                                        .Identification
                                        .builder()
                                        .method(
                                            EntityUpdateParams.SoleProprietorship.SoleProprietor
                                                .Identification
                                                .Method
                                                .SOCIAL_SECURITY_NUMBER
                                        )
                                        .number("xxxx")
                                        .driversLicense(
                                            EntityUpdateParams.SoleProprietorship.SoleProprietor
                                                .Identification
                                                .DriversLicense
                                                .builder()
                                                .expirationDate(LocalDate.parse("2019-12-27"))
                                                .fileId("file_id")
                                                .state("xx")
                                                .backFileId("back_file_id")
                                                .build()
                                        )
                                        .other(
                                            EntityUpdateParams.SoleProprietorship.SoleProprietor
                                                .Identification
                                                .Other
                                                .builder()
                                                .country("x")
                                                .description("x")
                                                .fileId("file_id")
                                                .backFileId("back_file_id")
                                                .expirationDate(LocalDate.parse("2019-12-27"))
                                                .build()
                                        )
                                        .passport(
                                            EntityUpdateParams.SoleProprietorship.SoleProprietor
                                                .Identification
                                                .Passport
                                                .builder()
                                                .country("x")
                                                .expirationDate(LocalDate.parse("2019-12-27"))
                                                .fileId("file_id")
                                                .build()
                                        )
                                        .build()
                                )
                                .name("x")
                                .build()
                        )
                        .taxIdentifier("x")
                        .website("website")
                        .build()
                )
                .addTermsAgreement(
                    EntityUpdateParams.TermsAgreement.builder()
                        .agreedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .ipAddress("x")
                        .termsUrl("x")
                        .build()
                )
                .thirdPartyVerification(
                    EntityUpdateParams.ThirdPartyVerification.builder()
                        .reference("x")
                        .vendor(EntityUpdateParams.ThirdPartyVerification.Vendor.ALLOY)
                        .build()
                )
                .trust(
                    EntityUpdateParams.Trust.builder()
                        .address(
                            EntityUpdateParams.Trust.Address.builder()
                                .city("x")
                                .line1("x")
                                .state("xx")
                                .zip("x")
                                .line2("x")
                                .build()
                        )
                        .grantor(
                            EntityUpdateParams.Trust.Grantor.builder()
                                .address(
                                    EntityUpdateParams.Trust.Grantor.Address.builder()
                                        .city("x")
                                        .country("x")
                                        .line1("x")
                                        .line2("x")
                                        .state("x")
                                        .zip("x")
                                        .build()
                                )
                                .dateOfBirth(LocalDate.parse("2019-12-27"))
                                .identification(
                                    EntityUpdateParams.Trust.Grantor.Identification.builder()
                                        .method(
                                            EntityUpdateParams.Trust.Grantor.Identification.Method
                                                .SOCIAL_SECURITY_NUMBER
                                        )
                                        .number("xxxx")
                                        .driversLicense(
                                            EntityUpdateParams.Trust.Grantor.Identification
                                                .DriversLicense
                                                .builder()
                                                .expirationDate(LocalDate.parse("2019-12-27"))
                                                .fileId("file_id")
                                                .state("xx")
                                                .backFileId("back_file_id")
                                                .build()
                                        )
                                        .other(
                                            EntityUpdateParams.Trust.Grantor.Identification.Other
                                                .builder()
                                                .country("x")
                                                .description("x")
                                                .fileId("file_id")
                                                .backFileId("back_file_id")
                                                .expirationDate(LocalDate.parse("2019-12-27"))
                                                .build()
                                        )
                                        .passport(
                                            EntityUpdateParams.Trust.Grantor.Identification.Passport
                                                .builder()
                                                .country("x")
                                                .expirationDate(LocalDate.parse("2019-12-27"))
                                                .fileId("file_id")
                                                .build()
                                        )
                                        .build()
                                )
                                .name("x")
                                .confirmedNoUsTaxId(true)
                                .build()
                        )
                        .name("x")
                        .addTrustee(
                            EntityUpdateParams.Trust.Trustee.builder()
                                .structure(EntityUpdateParams.Trust.Trustee.Structure.INDIVIDUAL)
                                .individual(
                                    EntityUpdateParams.Trust.Trustee.Individual.builder()
                                        .address(
                                            EntityUpdateParams.Trust.Trustee.Individual.Address
                                                .builder()
                                                .city("x")
                                                .country("x")
                                                .line1("x")
                                                .line2("x")
                                                .state("x")
                                                .zip("x")
                                                .build()
                                        )
                                        .dateOfBirth(LocalDate.parse("2019-12-27"))
                                        .identification(
                                            EntityUpdateParams.Trust.Trustee.Individual
                                                .Identification
                                                .builder()
                                                .method(
                                                    EntityUpdateParams.Trust.Trustee.Individual
                                                        .Identification
                                                        .Method
                                                        .SOCIAL_SECURITY_NUMBER
                                                )
                                                .number("xxxx")
                                                .driversLicense(
                                                    EntityUpdateParams.Trust.Trustee.Individual
                                                        .Identification
                                                        .DriversLicense
                                                        .builder()
                                                        .expirationDate(
                                                            LocalDate.parse("2019-12-27")
                                                        )
                                                        .fileId("file_id")
                                                        .state("xx")
                                                        .backFileId("back_file_id")
                                                        .build()
                                                )
                                                .other(
                                                    EntityUpdateParams.Trust.Trustee.Individual
                                                        .Identification
                                                        .Other
                                                        .builder()
                                                        .country("x")
                                                        .description("x")
                                                        .fileId("file_id")
                                                        .backFileId("back_file_id")
                                                        .expirationDate(
                                                            LocalDate.parse("2019-12-27")
                                                        )
                                                        .build()
                                                )
                                                .passport(
                                                    EntityUpdateParams.Trust.Trustee.Individual
                                                        .Identification
                                                        .Passport
                                                        .builder()
                                                        .country("x")
                                                        .expirationDate(
                                                            LocalDate.parse("2019-12-27")
                                                        )
                                                        .fileId("file_id")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .name("x")
                                        .confirmedNoUsTaxId(true)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .build()

        val body = params._body()

        assertThat(body.corporation())
            .isEqualTo(
                EntityUpdateParams.Corporation.builder()
                    .address(
                        EntityUpdateParams.Corporation.Address.builder()
                            .city("New York")
                            .country("US")
                            .line1("33 Liberty Street")
                            .line2("Unit 2")
                            .state("NY")
                            .zip("10045")
                            .build()
                    )
                    .email("dev@stainless.com")
                    .incorporationState("x")
                    .industryCode("x")
                    .legalIdentifier(
                        EntityUpdateParams.Corporation.LegalIdentifier.builder()
                            .value("x")
                            .category(
                                EntityUpdateParams.Corporation.LegalIdentifier.Category
                                    .US_EMPLOYER_IDENTIFICATION_NUMBER
                            )
                            .build()
                    )
                    .name("x")
                    .website("website")
                    .build()
            )
        assertThat(body.detailsConfirmedAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(body.governmentAuthority())
            .isEqualTo(
                EntityUpdateParams.GovernmentAuthority.builder()
                    .address(
                        EntityUpdateParams.GovernmentAuthority.Address.builder()
                            .city("x")
                            .line1("x")
                            .state("xx")
                            .zip("x")
                            .line2("x")
                            .build()
                    )
                    .name("x")
                    .build()
            )
        assertThat(body.naturalPerson())
            .isEqualTo(
                EntityUpdateParams.NaturalPerson.builder()
                    .address(
                        EntityUpdateParams.NaturalPerson.Address.builder()
                            .city("x")
                            .country("x")
                            .line1("x")
                            .line2("x")
                            .state("x")
                            .zip("x")
                            .build()
                    )
                    .confirmedNoUsTaxId(true)
                    .identification(
                        EntityUpdateParams.NaturalPerson.Identification.builder()
                            .method(
                                EntityUpdateParams.NaturalPerson.Identification.Method
                                    .SOCIAL_SECURITY_NUMBER
                            )
                            .number("xxxx")
                            .driversLicense(
                                EntityUpdateParams.NaturalPerson.Identification.DriversLicense
                                    .builder()
                                    .expirationDate(LocalDate.parse("2019-12-27"))
                                    .fileId("file_id")
                                    .state("xx")
                                    .backFileId("back_file_id")
                                    .build()
                            )
                            .other(
                                EntityUpdateParams.NaturalPerson.Identification.Other.builder()
                                    .country("x")
                                    .description("x")
                                    .fileId("file_id")
                                    .backFileId("back_file_id")
                                    .expirationDate(LocalDate.parse("2019-12-27"))
                                    .build()
                            )
                            .passport(
                                EntityUpdateParams.NaturalPerson.Identification.Passport.builder()
                                    .country("x")
                                    .expirationDate(LocalDate.parse("2019-12-27"))
                                    .fileId("file_id")
                                    .build()
                            )
                            .build()
                    )
                    .name("x")
                    .build()
            )
        assertThat(body.riskRating())
            .isEqualTo(
                EntityUpdateParams.RiskRating.builder()
                    .ratedAt(OffsetDateTime.parse("2020-01-31T23:59:59Z"))
                    .rating(EntityUpdateParams.RiskRating.Rating.LOW)
                    .build()
            )
        assertThat(body.soleProprietorship())
            .isEqualTo(
                EntityUpdateParams.SoleProprietorship.builder()
                    .address(
                        EntityUpdateParams.SoleProprietorship.Address.builder()
                            .city("x")
                            .line1("x")
                            .state("xx")
                            .zip("x")
                            .line2("x")
                            .build()
                    )
                    .email("dev@stainless.com")
                    .soleProprietor(
                        EntityUpdateParams.SoleProprietorship.SoleProprietor.builder()
                            .address(
                                EntityUpdateParams.SoleProprietorship.SoleProprietor.Address
                                    .builder()
                                    .city("x")
                                    .country("x")
                                    .line1("x")
                                    .line2("x")
                                    .state("x")
                                    .zip("x")
                                    .build()
                            )
                            .identification(
                                EntityUpdateParams.SoleProprietorship.SoleProprietor.Identification
                                    .builder()
                                    .method(
                                        EntityUpdateParams.SoleProprietorship.SoleProprietor
                                            .Identification
                                            .Method
                                            .SOCIAL_SECURITY_NUMBER
                                    )
                                    .number("xxxx")
                                    .driversLicense(
                                        EntityUpdateParams.SoleProprietorship.SoleProprietor
                                            .Identification
                                            .DriversLicense
                                            .builder()
                                            .expirationDate(LocalDate.parse("2019-12-27"))
                                            .fileId("file_id")
                                            .state("xx")
                                            .backFileId("back_file_id")
                                            .build()
                                    )
                                    .other(
                                        EntityUpdateParams.SoleProprietorship.SoleProprietor
                                            .Identification
                                            .Other
                                            .builder()
                                            .country("x")
                                            .description("x")
                                            .fileId("file_id")
                                            .backFileId("back_file_id")
                                            .expirationDate(LocalDate.parse("2019-12-27"))
                                            .build()
                                    )
                                    .passport(
                                        EntityUpdateParams.SoleProprietorship.SoleProprietor
                                            .Identification
                                            .Passport
                                            .builder()
                                            .country("x")
                                            .expirationDate(LocalDate.parse("2019-12-27"))
                                            .fileId("file_id")
                                            .build()
                                    )
                                    .build()
                            )
                            .name("x")
                            .build()
                    )
                    .taxIdentifier("x")
                    .website("website")
                    .build()
            )
        assertThat(body.termsAgreements())
            .containsExactly(
                EntityUpdateParams.TermsAgreement.builder()
                    .agreedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .ipAddress("x")
                    .termsUrl("x")
                    .build()
            )
        assertThat(body.thirdPartyVerification())
            .isEqualTo(
                EntityUpdateParams.ThirdPartyVerification.builder()
                    .reference("x")
                    .vendor(EntityUpdateParams.ThirdPartyVerification.Vendor.ALLOY)
                    .build()
            )
        assertThat(body.trust())
            .isEqualTo(
                EntityUpdateParams.Trust.builder()
                    .address(
                        EntityUpdateParams.Trust.Address.builder()
                            .city("x")
                            .line1("x")
                            .state("xx")
                            .zip("x")
                            .line2("x")
                            .build()
                    )
                    .grantor(
                        EntityUpdateParams.Trust.Grantor.builder()
                            .address(
                                EntityUpdateParams.Trust.Grantor.Address.builder()
                                    .city("x")
                                    .country("x")
                                    .line1("x")
                                    .line2("x")
                                    .state("x")
                                    .zip("x")
                                    .build()
                            )
                            .dateOfBirth(LocalDate.parse("2019-12-27"))
                            .identification(
                                EntityUpdateParams.Trust.Grantor.Identification.builder()
                                    .method(
                                        EntityUpdateParams.Trust.Grantor.Identification.Method
                                            .SOCIAL_SECURITY_NUMBER
                                    )
                                    .number("xxxx")
                                    .driversLicense(
                                        EntityUpdateParams.Trust.Grantor.Identification
                                            .DriversLicense
                                            .builder()
                                            .expirationDate(LocalDate.parse("2019-12-27"))
                                            .fileId("file_id")
                                            .state("xx")
                                            .backFileId("back_file_id")
                                            .build()
                                    )
                                    .other(
                                        EntityUpdateParams.Trust.Grantor.Identification.Other
                                            .builder()
                                            .country("x")
                                            .description("x")
                                            .fileId("file_id")
                                            .backFileId("back_file_id")
                                            .expirationDate(LocalDate.parse("2019-12-27"))
                                            .build()
                                    )
                                    .passport(
                                        EntityUpdateParams.Trust.Grantor.Identification.Passport
                                            .builder()
                                            .country("x")
                                            .expirationDate(LocalDate.parse("2019-12-27"))
                                            .fileId("file_id")
                                            .build()
                                    )
                                    .build()
                            )
                            .name("x")
                            .confirmedNoUsTaxId(true)
                            .build()
                    )
                    .name("x")
                    .addTrustee(
                        EntityUpdateParams.Trust.Trustee.builder()
                            .structure(EntityUpdateParams.Trust.Trustee.Structure.INDIVIDUAL)
                            .individual(
                                EntityUpdateParams.Trust.Trustee.Individual.builder()
                                    .address(
                                        EntityUpdateParams.Trust.Trustee.Individual.Address
                                            .builder()
                                            .city("x")
                                            .country("x")
                                            .line1("x")
                                            .line2("x")
                                            .state("x")
                                            .zip("x")
                                            .build()
                                    )
                                    .dateOfBirth(LocalDate.parse("2019-12-27"))
                                    .identification(
                                        EntityUpdateParams.Trust.Trustee.Individual.Identification
                                            .builder()
                                            .method(
                                                EntityUpdateParams.Trust.Trustee.Individual
                                                    .Identification
                                                    .Method
                                                    .SOCIAL_SECURITY_NUMBER
                                            )
                                            .number("xxxx")
                                            .driversLicense(
                                                EntityUpdateParams.Trust.Trustee.Individual
                                                    .Identification
                                                    .DriversLicense
                                                    .builder()
                                                    .expirationDate(LocalDate.parse("2019-12-27"))
                                                    .fileId("file_id")
                                                    .state("xx")
                                                    .backFileId("back_file_id")
                                                    .build()
                                            )
                                            .other(
                                                EntityUpdateParams.Trust.Trustee.Individual
                                                    .Identification
                                                    .Other
                                                    .builder()
                                                    .country("x")
                                                    .description("x")
                                                    .fileId("file_id")
                                                    .backFileId("back_file_id")
                                                    .expirationDate(LocalDate.parse("2019-12-27"))
                                                    .build()
                                            )
                                            .passport(
                                                EntityUpdateParams.Trust.Trustee.Individual
                                                    .Identification
                                                    .Passport
                                                    .builder()
                                                    .country("x")
                                                    .expirationDate(LocalDate.parse("2019-12-27"))
                                                    .fileId("file_id")
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .name("x")
                                    .confirmedNoUsTaxId(true)
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params = EntityUpdateParams.builder().entityId("entity_n8y8tnk2p9339ti393yi").build()

        val body = params._body()
    }
}
